Repository kimai/kimai, pull requests merged in 2019-04, with the labels that each got.

#712 remove unused role ROLE_CUSTOMER
  config/packages/security.yaml
  src/DataFixtures/UserFixtures.php
  src/Entity/User.php
  src/Validator/Constraints/RoleValidator.php
  tests/Entity/UserTest.php
  tests/Validator/Constraints/RoleValidatorTest.php
  translations/messages.ar.xliff
  translations/messages.de.xliff
  translations/messages.en.xliff
  translations/messages.es.xliff
  translations/messages.fr.xliff
  translations/messages.hu.xliff
  translations/messages.it.xliff
  translations/messages.pt_BR.xliff
  translations/messages.ru.xliff
Labels: technical debt

#710 Update to Symfony 4.2
  .github/PULL_REQUEST_TEMPLATE.md
  .scrutinizer.yml
  .travis.yml
  CONTRIBUTING.md
  UPGRADING.md
  assets/sass/app.scss
  assets/sass/tooltip.scss
  composer.json
  composer.lock
  config/packages/admin_lte.yaml
  config/packages/twig_extensions.yaml
  public/build/app.css
  public/build/app.js
  public/build/manifest.json
  src/API/BaseApiController.php
  src/API/ConfigurationController.php
  src/API/HealthcheckController.php
  src/Command/RunCodestyleCommand.php
  src/Controller/InvoiceController.php
  src/DependencyInjection/Configuration.php
  src/Form/Extension/DocumentationLinkExtension.php
  src/Form/Extension/EnhancedChoiceTypeExtension.php
  src/Form/Extension/SelectWithApiDataExtension.php
  src/Twig/EventExtensions.php
  symfony.lock
  templates/macros/widgets.html.twig
  templates/navbar/active-entries.html.twig
  templates/navbar/recent-activities.html.twig
  templates/timesheet/index.html.twig
  tests/Command/RunCodestyleCommandTest.php
  translations/messages.de.xliff
Labels: technical debt

#717 added api/activities POST and PATCH
  config/packages/nelmio_api_doc.yaml
  src/API/ActivityController.php
  src/Form/ActivityEditForm.php
  tests/API/ActivityControllerTest.php
Labels: API, feature request

#722 remove invalid cache header
  src/Controller/ActivityController.php
  src/Controller/CalendarController.php
  src/Controller/ProjectController.php
Labels: bug

#726 added delete timesheet API endpoint
  src/API/TimesheetController.php
  tests/API/TimesheetControllerTest.php
Labels: feature request

#703 Load export type ids dynamically
  src/Controller/ExportController.php
  src/Repository/Query/ExportQuery.php
  tests/Controller/ExportControllerTest.php
  tests/Repository/Query/ExportQueryTest.php
Labels: feature request

#715 allow to overwrite config via prepend
  .scrutinizer.yml
  UPGRADING.md
  config/packages/kimai.yaml
  src/Configuration/TimesheetConfiguration.php
  src/Controller/AbstractController.php
  src/Controller/SystemConfigurationController.php
  src/Controller/TimesheetController.php
  src/Controller/TimesheetTeamController.php
  src/DataFixtures/CustomerFixtures.php
  src/DependencyInjection/AppExtension.php
  src/DependencyInjection/Configuration.php
  src/Form/Type/TimesheetModeType.php
  src/Twig/AssetExtension.php
  src/Twig/TimesheetConfigExtension.php
  templates/timesheet-team/index.html.twig
  templates/timesheet/index.html.twig
  tests/Configuration/SystemConfigurationTest.php
  tests/Configuration/TimesheetConfigurationTest.php
  tests/Controller/SystemConfigurationControllerTest.php
  tests/Twig/TimesheetConfigExtensionTest.php
  tests/Validator/Constraints/TimesheetValidatorTest.php
  translations/system-configuration.de.xliff
  translations/system-configuration.en.xliff
  translations/system-configuration.hu.xliff
Labels: feature request

#727 Updated authorization screens
  composer.json
  composer.lock
  public/build/app.css
  public/build/app.js
  public/build/manifest.json
  symfony.lock
  templates/bundles/FOSUserBundle/Security/login.html.twig
  tests/Controller/SecurityControllerTest.php
Labels: feature request, security

#734 reduce config complexity by converting php format to js format
  config/packages/kimai.yaml
  src/Configuration/LanguageFormattings.php
  src/DependencyInjection/Configuration.php
  src/Utils/MomentFormatConverter.php
  tests/Configuration/LanguageFormattingsTest.php
  tests/Utils/LocaleSettingsTest.php
  tests/Utils/MomentFormatConverterTest.php
Labels: feature request

#730 prepare release 0.9
  .github_changelog_generator
  CHANGELOG.md
  assets/app.js
  public/build/app.css
  public/build/app.js
  public/build/images/blue.png
  public/build/images/blue@2x.png
  public/build/manifest.json
  src/Constants.php
  src/DependencyInjection/Configuration.php
  translations/messages.de.xliff
  translations/messages.en.xliff
  webpack.config.js
Labels: release

#735 fix tests that failed around midnight
  tests/Timesheet/Calculator/RateCalculatorTest.php
Labels: bug

#737 theme update for swedish auth screens
  composer.lock
Labels: translation i18n

#741 use bootstrap tooltips instead of own solution
  assets/js/kimai.js
  assets/sass/app.scss
  assets/sass/tooltip.scss
  public/build/app.css
  public/build/app.js
  public/build/manifest.json
  templates/macros/widgets.html.twig
  webpack.config.js
Labels: technical debt

#738 translate time-tracking in login screen and browser title
  src/EventSubscriber/MenuSubscriber.php
  src/Twig/DatatableExtensions.php
  src/Twig/Extensions.php
  src/Twig/TitleExtension.php
  templates/base.html.twig
  templates/bundles/FOSUserBundle/Registration/confirmed.html.twig
  templates/bundles/FOSUserBundle/Registration/register.html.twig
  templates/bundles/FOSUserBundle/Resetting/request.html.twig
  templates/bundles/FOSUserBundle/Security/login.html.twig
  templates/bundles/FOSUserBundle/layout.html.twig
  templates/macros/datatables.html.twig
  templates/partials/logo_login.html.twig
  tests/Controller/SecurityControllerTest.php
  tests/Export/Renderer/AbstractRendererTest.php
  tests/Invoice/Renderer/AbstractRendererTest.php
  tests/Timesheet/UserDateTimeFactoryTest.php
  tests/Twig/DatatableExtensionsTest.php
  tests/Twig/ExtensionsTest.php
  tests/Twig/TitleExtensionTest.php
  translations/messages.ar.xliff
  translations/messages.de.xliff
  translations/messages.en.xliff
  translations/messages.es.xliff
  translations/messages.fr.xliff
  translations/messages.hu.xliff
  translations/messages.it.xliff
  translations/messages.pt_BR.xliff
  translations/messages.ru.xliff
  translations/messages.sv.xliff
Labels: translation i18n

#742 navbar block cleanup
  src/EventSubscriber/NavbarShowUserSubscriber.php
  templates/base.html.twig
  templates/bundles/AdminLTEBundle/Navbar/user.html.twig
Labels: technical debt

#739 prevent jumping icons in navbar between collapsed and open state
  assets/sass/navbar.scss
  public/build/app.css
  public/build/manifest.json
Labels: feature request
