Repository kimai/kimai, pull requests merged in 2019-05, with the labels that each got.

#733 ES6 javascript conversion
  assets/app.js
  assets/js/datatable.js
  assets/js/kimai.js
  assets/js/toolbar.js
  public/build/app.js
  public/build/manifest.json
  templates/activity/index.html.twig
  templates/customer/index.html.twig
  templates/export/index.html.twig
  templates/invoice/index.html.twig
  templates/macros/datatables.html.twig
  templates/project/index.html.twig
  templates/timesheet-team/index.html.twig
  templates/timesheet/index.html.twig
  templates/user/index.html.twig
  webpack.config.js
Labels: feature request

#750 moved shared entity fields and functions to trait
  config/packages/doctrine.yaml
  src/Entity/Activity.php
  src/Entity/Customer.php
  src/Entity/Project.php
  src/Entity/RatesTrait.php
  src/Entity/Timesheet.php
  symfony.lock
Labels: technical debt

#746 Entity actions re-designed (table buttons)
  assets/js/kimai.js
  assets/sass/datatable.scss
  public/build/app.css
  public/build/app.js
  public/build/manifest.json
  src/Twig/TitleExtension.php
  templates/activity/index.html.twig
  templates/customer/index.html.twig
  templates/invoice/template_edit.html.twig
  templates/invoice/templates.html.twig
  templates/macros/actions.html.twig
  templates/macros/datatables.html.twig
  templates/macros/widgets.html.twig
  templates/plugin/index.html.twig
  templates/project/index.html.twig
  templates/timesheet-team/index.html.twig
  templates/timesheet/index.html.twig
  templates/user/index.html.twig
  templates/user/layout.html.twig
  templates/user/profile.html.twig
  translations/actions.de.xliff
  translations/actions.en.xliff
Labels: technical debt

#751 colors for visual grouping of customer, projects and activities
  assets/sass/app.scss
  assets/sass/datatable-extensions.scss
  assets/sass/datatable.scss
  assets/sass/error-page.scss
  assets/sass/footer.scss
  assets/sass/navbar.scss
  assets/sass/print.scss
  assets/sass/sidebar.scss
  assets/sass/toolbar.scss
  assets/sass/variables.scss
  config/serializer/App/Entity.Activity.yml
  config/serializer/App/Entity.Customer.yml
  config/serializer/App/Entity.Project.yml
  public/build/app.css
  public/build/manifest.json
  src/Calendar/TimesheetEntity.php
  src/Entity/Activity.php
  src/Entity/ColorTrait.php
  src/Entity/Customer.php
  src/Entity/Project.php
  src/Form/ActivityEditForm.php
  src/Form/CustomerEditForm.php
  src/Form/ProjectEditForm.php
  src/Form/Type/ColorPickerType.php
  src/Migrations/Version20190502161758.php
  src/Repository/Query/BaseQuery.php
  templates/activity/index.html.twig
  templates/customer/index.html.twig
  templates/macros/widgets.html.twig
  templates/project/index.html.twig
  tests/API/ActivityControllerTest.php
  tests/API/CustomerControllerTest.php
  tests/API/ProjectControllerTest.php
  tests/Calendar/TimesheetEntityTest.php
  tests/Entity/ActivityTest.php
  tests/Entity/CustomerTest.php
  tests/Entity/ProjectTest.php
  translations/messages.de.xliff
  translations/messages.en.xliff
  var/data/kimai_test.sqlite
Labels: feature request

#752 dynamically update title and visible durations for running records
  assets/app.js
  assets/js/KimaiActiveRecordsDuration.js
  assets/js/KimaiDatatableColumnView.js
  composer.lock
  public/build/app.css
  public/build/app.js
  public/build/manifest.json
  src/Twig/DateExtensions.php
  templates/base.html.twig
  templates/navbar/active-entries.html.twig
  templates/timesheet-team/index.html.twig
  templates/timesheet/index.html.twig
  tests/Twig/DateExtensionsTest.php
  yarn.lock
Labels: feature request

#756 Database interoperability
  src/Entity/Timesheet.php
  src/Repository/ActivityRepository.php
  src/Repository/CustomerRepository.php
  src/Repository/ProjectRepository.php
  src/Repository/TimesheetRepository.php
  src/Repository/UserRepository.php
Labels: technical debt

#758 fix toolbar requests for empty choice
  assets/js/kimai.js
  assets/js/toolbar.js
  public/build/app.css
  public/build/app.js
  public/build/manifest.json
  src/API/ActivityController.php
  src/API/ProjectController.php
  src/API/TimesheetController.php
  src/Command/KimaiImporterCommand.php
  src/Form/Extension/SelectWithApiDataExtension.php
  src/Form/Toolbar/AbstractToolbarForm.php
  src/Form/Type/ProjectType.php
Labels: bug

#759 refactored javascript to ES6 classes
  assets/app.js
  assets/js/KimaiActiveRecordsDuration.js
  assets/js/KimaiConfiguration.js
  assets/js/KimaiContainer.js
  assets/js/KimaiDatatableColumnView.js
  assets/js/KimaiLoader.js
  assets/js/KimaiPlugin.js
  assets/js/KimaiTranslation.js
  assets/js/KimaiWebLoader.js
  assets/js/kimai.js
  assets/js/plugins/KimaiAPI.js
  assets/js/plugins/KimaiActiveRecordsDuration.js
  assets/js/plugins/KimaiAjaxModalForm.js
  assets/js/plugins/KimaiAlternativeLinks.js
  assets/js/plugins/KimaiClickHandlerReducedInTableRow.js
  assets/js/plugins/KimaiDatatable.js
  assets/js/plugins/KimaiDatatableColumnView.js
  assets/js/plugins/KimaiDatePicker.js
  assets/js/plugins/KimaiDateRangePicker.js
  assets/js/plugins/KimaiDateTimePicker.js
  assets/js/plugins/KimaiJqueryPluginInitializer.js
  assets/js/plugins/KimaiPauseRecord.js
  assets/js/plugins/KimaiSelectDataAPI.js
  assets/js/plugins/KimaiThemeInitializer.js
  assets/js/plugins/KimaiToolbar.js
  assets/js/toolbar.js
  assets/sass/navbar.scss
  package.json
  public/build/app.css
  public/build/app.js
  public/build/manifest.json
  templates/base.html.twig
  templates/macros/datatables.html.twig
  templates/navbar/active-entries.html.twig
  templates/user/index.html.twig
  webpack.config.js
  yarn.lock
Labels: bug, technical debt

#761 recent activities via API
  assets/js/KimaiLoader.js
  assets/js/plugins/KimaiAjaxModalForm.js
  assets/js/plugins/KimaiDatatable.js
  assets/js/plugins/KimaiDatatableColumnView.js
  assets/js/plugins/KimaiEvent.js
  assets/js/plugins/KimaiRecentActivities.js
  assets/sass/navbar.scss
  assets/sass/variables.scss
  config/packages/nelmio_api_doc.yaml
  config/routes/test/test_routes.yaml
  config/serializer/App/Entity.Activity.yml
  config/serializer/App/Entity.Customer.yml
  config/serializer/App/Entity.Project.yml
  config/serializer/App/Entity.Timesheet.yml
  public/build/app.css
  public/build/app.js
  public/build/manifest.json
  src/API/TimesheetController.php
  src/Controller/NavbarController.php
  src/Controller/SystemConfigurationController.php
  src/Form/ActivityEditForm.php
  src/Form/CustomerEditForm.php
  src/Form/ProjectEditForm.php
  src/Repository/ActivityRepository.php
  src/Repository/TimesheetRepository.php
  src/Twig/Extensions.php
  templates/base.html.twig
  templates/navbar/recent-activities.html.twig
  tests/API/TimesheetControllerTest.php
  tests/Controller/NavbarControllerTest.php
  translations/messages.ar.xliff
  translations/messages.de.xliff
  translations/messages.en.xliff
  translations/messages.es.xliff
  translations/messages.fr.xliff
  translations/messages.hu.xliff
  translations/messages.it.xliff
  translations/messages.pt_BR.xliff
  translations/messages.ru.xliff
  translations/messages.sv.xliff
Labels: feature request

#757 added more entity actions
  src/Controller/ActivityController.php
  src/Controller/ProjectController.php
  src/Controller/TimesheetController.php
  src/Controller/TimesheetControllerTrait.php
  src/Controller/TimesheetTeamController.php
  templates/macros/actions.html.twig
  translations/actions.de.xliff
  translations/actions.en.xliff
Labels: feature request

#774 Add Japanese translation
  README.md
  config/packages/kimai.yaml
  config/services.yaml
  translations/about.ja.xliff
  translations/daterangepicker.ja.xliff
  translations/exceptions.ja.xliff
  translations/flashmessages.ja.xliff
  translations/invoice-calculator.ja.xliff
  translations/invoice-numbergenerator.ja.xliff
  translations/invoice-renderer.ja.xliff
  translations/messages.ja.xliff
  translations/pagerfanta.ja.xliff
  translations/plugins.ja.xliff
  translations/system-configuration.ja.xliff
  translations/validators.ja.xliff
Labels: translation i18n

#775 translate date picker and charts
  assets/app.js
  assets/js/plugins/KimaiDatePicker.js
  assets/js/plugins/KimaiDateRangePicker.js
  assets/js/plugins/KimaiDateTimePicker.js
  public/build/app.js
  public/build/manifest.json
  templates/dashboard/section-chart.html.twig
  templates/export/index.html.twig
  templates/invoice/index.html.twig
  templates/user/stats.html.twig
Labels: translation i18n

#776 delete timesheets via api
  src/API/TimesheetController.php
  src/Controller/TimesheetController.php
  src/Controller/TimesheetTeamController.php
  templates/macros/actions.html.twig
  templates/timesheet-team/delete.html.twig
  templates/timesheet/delete.html.twig
  tests/Controller/TimesheetControllerTest.php
  tests/Controller/TimesheetTeamControllerTest.php
Labels: API, feature request

#780 bugfix for API selects
  assets/js/plugins/KimaiAPI.js
  assets/js/plugins/KimaiAPILink.js
  assets/js/plugins/KimaiActiveRecords.js
  assets/js/plugins/KimaiAutocomplete.js
  assets/js/plugins/KimaiRecentActivities.js
  assets/js/plugins/KimaiSelectDataAPI.js
  composer.lock
  package.json
  public/build/app.css
  public/build/app.js
  public/build/manifest.json
  templates/invoice/renderer/freelancer.html.twig
  templates/invoice/renderer/timesheet.html.twig
  translations/messages.sv.xliff
  yarn.lock
Labels: bug

#782 restart via API allows to copy description
  assets/js/plugins/KimaiAPILink.js
  assets/js/plugins/KimaiRecentActivities.js
  config/serializer/App/Entity.Timesheet.yml
  public/build/app.js
  public/build/manifest.json
  src/API/TimesheetController.php
  src/Controller/TimesheetController.php
  src/Controller/TimesheetControllerTrait.php
  src/Form/TimesheetEditForm.php
  templates/base.html.twig
  templates/macros/actions.html.twig
  templates/macros/widgets.html.twig
  templates/navbar/recent-activities.html.twig
  tests/API/APIControllerBaseTest.php
  tests/API/TagControllerTest.php
  tests/API/TimesheetControllerTest.php
  tests/Controller/TimesheetControllerTest.php
  translations/flashmessages.ar.xliff
  translations/flashmessages.de.xliff
  translations/flashmessages.en.xliff
  translations/flashmessages.es.xliff
  translations/flashmessages.fr.xliff
  translations/flashmessages.hu.xliff
  translations/flashmessages.it.xliff
  translations/flashmessages.ja.xliff
  translations/flashmessages.pt_BR.xliff
  translations/flashmessages.ru.xliff
  translations/flashmessages.sv.xliff
Labels: feature request

#789 fix column and max key length
  src/Entity/Tag.php
  src/Migrations/Version20190510205245.php
  var/data/kimai_test.sqlite
Labels: bug

#794 fix phpunit annotations
  src/Form/TimesheetEditForm.php
  tests/API/ActivityControllerTest.php
  tests/API/ConfigurationControllerTest.php
  tests/API/CustomerControllerTest.php
  tests/API/Model/I18nTest.php
  tests/API/ProjectControllerTest.php
  tests/API/StatusControllerTest.php
  tests/API/TagControllerTest.php
  tests/API/TimesheetControllerTest.php
  tests/API/UserControllerTest.php
  tests/Calendar/GoogleTest.php
  tests/Calendar/SourceTest.php
  tests/Command/CreateUserCommandTest.php
  tests/Controller/AboutControllerTest.php
  tests/Controller/ActivityControllerTest.php
  tests/Controller/CalendarControllerTest.php
  tests/Controller/CustomerControllerTest.php
  tests/Controller/DashboardControllerTest.php
  tests/Controller/ExportControllerTest.php
  tests/Controller/HomepageControllerTest.php
  tests/Controller/InvoiceControllerTest.php
  tests/Controller/PluginControllerTest.php
  tests/Controller/ProfileControllerTest.php
  tests/Controller/ProjectControllerTest.php
  tests/Controller/SecurityControllerTest.php
  tests/Controller/SystemConfigurationControllerTest.php
  tests/Controller/TagControllerTest.php
  tests/Controller/TimesheetControllerTest.php
  tests/Controller/TimesheetTeamControllerTest.php
  tests/Controller/UserControllerTest.php
  tests/Entity/UserTest.php
  tests/Event/ThemeEventTest.php
  tests/Export/ServiceExportTest.php
  tests/Form/DataTransformer/TagArrayToStringTransformerTest.php
Labels: technical debt

#801 use dropdown for entity actions on detail pages
  assets/js/plugins/KimaiAPILink.js
  assets/js/plugins/KimaiClickHandlerReducedInTableRow.js
  assets/js/plugins/KimaiToolbarAction.js
  assets/sass/datatable-extensions.scss
  public/build/app.css
  public/build/app.js
  public/build/manifest.json
  src/Twig/EntityExtensions.php
  templates/macros/actions.html.twig
  templates/macros/widgets.html.twig
  translations/actions.de.xliff
  translations/actions.en.xliff
Labels: feature request

#798 lock exported timesheets
  .scrutinizer.yml
  UPGRADING.md
  assets/js/plugins/KimaiAjaxModalForm.js
  config/packages/kimai.yaml
  public/build/app.js
  public/build/manifest.json
  src/API/TimesheetController.php
  src/Command/CreateReleaseCommand.php
  src/Command/KimaiImporterCommand.php
  src/Command/ResetCommand.php
  src/Twig/Extensions.php
  src/Voter/TimesheetVoter.php
  templates/export/index.html.twig
  templates/macros/widgets.html.twig
  templates/timesheet-team/edit.html.twig
  templates/timesheet/edit.html.twig
  tests/API/TimesheetControllerTest.php
  tests/Doctrine/SqliteSessionInitSubscriberTest.php
  tests/Voter/AbstractVoterTest.php
  tests/Voter/TimesheetVoterTest.php
  translations/flashmessages.de.xliff
  translations/flashmessages.en.xliff
Labels: export, feature request

#802 improved html export
  src/Export/Renderer/RendererTrait.php
  templates/export/layout.html.twig
  templates/export/renderer/default.html.twig
  tests/Controller/ExportControllerTest.php
  tests/Export/Renderer/HtmlRendererTest.php
Labels: export, feature request

#805 added SECURITY.md
  SECURITY.md
Labels: security

#806 added phpstan for code analyzes
  .github/PULL_REQUEST_TEMPLATE.md
  .travis.yml
  SECURITY.md
  composer.json
  composer.lock
  phpstan.neon
  src/Command/BashExecutor.php
  src/Command/BashResult.php
  src/Command/RunCodestyleCommand.php
  src/Command/RunIntegrationTestsCommand.php
  src/Command/RunUnitTestsCommand.php
  symfony.lock
  tests/Command/RunCodestyleCommandTest.php
  tests/Command/RunIntegrationTestsCommandTest.php
  tests/Command/RunUnitTestsCommandTest.php
  tests/Command/TestBashExecutor.php
Labels: technical debt

#807 allow markdown for customer, project and activity comments
  src/Controller/SystemConfigurationController.php
  src/Twig/MarkdownExtension.php
  templates/activity/index.html.twig
  templates/customer/index.html.twig
  templates/project/index.html.twig
  tests/Controller/SystemConfigurationControllerTest.php
  tests/Twig/MarkdownExtensionTest.php
  translations/system-configuration.de.xliff
  translations/system-configuration.en.xliff
  translations/system-configuration.hu.xliff
  translations/system-configuration.ja.xliff
  translations/system-configuration.sv.xliff
Labels: feature request

#810 enhance tag query to show all tags of an item
  src/Controller/TimesheetAbstractController.php
  src/Repository/Query/TimesheetQuery.php
  src/Repository/TimesheetRepository.php
Labels: bug

#808 refactored permissions for simpler customizations
  UPGRADING.md
  assets/js/plugins/KimaiAPILink.js
  assets/js/plugins/KimaiAlert.js
  config/packages/kimai.yaml
  public/build/app.js
  public/build/manifest.json
  src/Controller/AboutController.php
  src/Controller/UserController.php
  src/DependencyInjection/AppExtension.php
  src/DependencyInjection/Configuration.php
  src/Form/UserCreateType.php
  src/Security/RolePermissionManager.php
  src/Twig/Extensions.php
  templates/about/system.html.twig
  templates/export/index.html.twig
  templates/invoice/index.html.twig
  templates/invoice/templates.html.twig
  templates/macros/actions.html.twig
  templates/macros/datatables.html.twig
  templates/macros/widgets.html.twig
  templates/user/permissions.html.twig
  tests/Controller/AboutControllerTest.php
  tests/Controller/UserControllerTest.php
  tests/Voter/AbstractVoterTest.php
Labels: security

#812 added punch-in punch-out / time-clock mode
  .github/PULL_REQUEST_TEMPLATE.md
  assets/js/plugins/KimaiAjaxModalForm.js
  config/packages/kimai.yaml
  public/build/app.js
  public/build/manifest.json
  src/API/TimesheetController.php
  src/Configuration/TimesheetConfiguration.php
  src/Controller/TimesheetAbstractController.php
  src/Controller/TimesheetTeamController.php
  src/DependencyInjection/Configuration.php
  src/Form/TimesheetAdminEditForm.php
  src/Form/TimesheetEditForm.php
  src/Form/Type/TimesheetModeType.php
  src/Twig/TimesheetConfigExtension.php
  templates/calendar/user.html.twig
  tests/Controller/TimesheetTeamControllerTest.php
  tests/Twig/TimesheetConfigExtensionTest.php
  translations/messages.sv.xliff
  translations/system-configuration.de.xliff
  translations/system-configuration.en.xliff
Labels: feature request
