Repository kimai/kimai, pull requests merged in 2019-08, with the labels that each got.

#924 testing with mysql
  .travis.yml
  public/.htaccess
  src/Migrations/Version20180715160326.php
Labels: technical debt

#1001 Fix activity import Kimai v1
  src/Command/KimaiImporterCommand.php
Labels: bug

#995 Fix english translation for 'info'
  translations/messages.en.xliff
Labels: translation i18n

#986 optimize composer and commands
  .travis.yml
  UPGRADING.md
  composer.json
  composer.lock
  src/Command/ConvertTimezoneCommand.php
  src/Command/CreateReleaseCommand.php
  src/Command/ResetCommand.php
  src/Entity/Timesheet.php
Labels: technical debt

#993 user roles selects
  src/Form/Type/UserRoleType.php
  src/Form/UserRolesType.php
  tests/Controller/ProfileControllerTest.php
Labels: technical debt

#994 added commands to further break down version infos
  src/Command/PluginCommand.php
  src/Plugin/PluginManager.php
  tests/Command/PluginCommandTest.php
Labels: feature request

#1002 Fix various minor English grammar translations
  tests/Controller/PluginControllerTest.php
  translations/messages.en.xliff
  translations/plugins.en.xliff
  translations/system-configuration.en.xliff
  translations/tags.en.xliff
Labels: translation i18n

#1030 Copy meta fields
  src/API/TimesheetController.php
  tests/API/TimesheetControllerTest.php
Labels: feature request

#1033 added invoice variable for numeric month
  src/Invoice/Renderer/RendererTrait.php
  tests/Invoice/Renderer/DebugRendererTest.php
Labels: feature request

#1037 added decimal format for invoice duration
  src/Invoice/Renderer/AbstractRenderer.php
  src/Invoice/Renderer/RendererTrait.php
  src/Twig/Extensions.php
  templates/invoice/index.html.twig
  templates/invoice/renderer/default.html.twig
  templates/invoice/renderer/freelancer.html.twig
  templates/invoice/renderer/timesheet.html.twig
  tests/Invoice/Renderer/DebugRenderer.php
  tests/Invoice/Renderer/DebugRendererTest.php
  tests/Twig/ExtensionsTest.php
Labels: feature request, invoice

#1041 fix team opens in modal
  templates/macros/actions.html.twig
Labels: bug

#1031 reduce field size to 150 chars to not break MySQL index length
  UPGRADING.md
  src/Entity/Activity.php
  src/Entity/Customer.php
  src/Entity/InvoiceTemplate.php
  src/Entity/Project.php
  src/Entity/Timesheet.php
  src/Migrations/Version20190706224219.php
  src/Migrations/Version20190813162649.php
  var/data/kimai_test.sqlite
Labels: bug

#1042 added css class to target running records in timesheet tables
  templates/timesheet-team/index.html.twig
  templates/timesheet/index.html.twig
  tests/Controller/TimesheetControllerTest.php
  tests/Controller/TimesheetTeamControllerTest.php
Labels: feature request

#1044 added manual links to all screens
  templates/export/index.html.twig
  templates/macros/actions.html.twig
  templates/system-configuration/index.html.twig
  tests/Controller/PluginControllerTest.php
  tests/Controller/TeamControllerTest.php
  tests/Controller/TimesheetControllerTest.php
  tests/Controller/TimesheetTeamControllerTest.php
Labels: feature request

#1050 support creating new roles
  config/services.yaml
  src/Security/RolePermissionManager.php
  src/Security/RoleService.php
  src/Validator/Constraints/RoleValidator.php
  tests/Mocks/Security/RoleServiceFactory.php
  tests/Validator/Constraints/RoleValidatorTest.php
  tests/Voter/AbstractVoterTest.php
Labels: feature request

#1053 do not delete team if linked entity is deleted
  src/Entity/Customer.php
  src/Entity/Project.php
  src/Entity/Timesheet.php
  src/Entity/User.php
Labels: bug

#1054 fix empty user language
  src/Command/KimaiImporterCommand.php
  src/Controller/HomepageController.php
Labels: bug

#1046 refactored invoice and export forms
  UPGRADING.md
  composer.lock
  config/packages/kimai.yaml
  phpstan.neon
  src/Controller/ExportController.php
  src/Controller/InvoiceController.php
  src/EventSubscriber/MenuSubscriber.php
  src/Export/Renderer/AbstractSpreadsheetRenderer.php
  src/Export/Renderer/CsvRenderer.php
  src/Export/Renderer/OdsRenderer.php
  src/Form/Toolbar/AbstractToolbarForm.php
  src/Form/Toolbar/ExportToolbarForm.php
  src/Form/Toolbar/InvoiceToolbarForm.php
  src/Form/Toolbar/TimesheetToolbarForm.php
  src/Invoice/Renderer/RendererTrait.php
  src/Repository/Query/BaseQuery.php
  src/Repository/Query/ExportQuery.php
  src/Repository/Query/InvoiceQuery.php
  src/Repository/Query/TimesheetQuery.php
  src/Repository/TimesheetRepository.php
  src/Voter/InvoiceTemplateVoter.php
  templates/base.html.twig
  templates/default/_form.html.twig
  templates/export/actions.html.twig
  templates/export/index.html.twig
  templates/export/renderer/default.html.twig
  templates/export/renderer/pdf.html.twig
  templates/invoice/actions.html.twig
  templates/invoice/index.html.twig
  templates/invoice/templates.html.twig
  templates/macros/actions.html.twig
  tests/Controller/ExportControllerTest.php
  tests/Controller/InvoiceControllerTest.php
  tests/Controller/UserControllerTest.php
  tests/Export/Renderer/AbstractRendererTest.php
  tests/Export/Renderer/CsvRendererTest.php
  tests/Export/Renderer/OdsRendererTest.php
  tests/Invoice/Renderer/DebugRendererTest.php
  tests/Repository/Query/ExportQueryTest.php
  tests/Repository/Query/InvoiceQueryTest.php
  tests/Repository/Query/TimesheetQueryTest.php
  tests/Voter/AbstractVoterTest.php
  tests/Voter/InvoiceTemplateVoterTest.php
  tests/Voter/RolePermissionVoterTest.php
  tests/phpstan.neon
  translations/messages.ar.xliff
  translations/messages.de.xliff
  translations/messages.en.xliff
  translations/messages.es.xliff
  translations/messages.fr.xliff
  translations/messages.hu.xliff
  translations/messages.ja.xliff
  translations/messages.pt_BR.xliff
  translations/messages.sk.xliff
  translations/messages.sv.xliff
Labels: feature request, invoice

#1058 improve invoice handling for different rates
  src/API/TimesheetController.php
  src/Controller/InvoiceController.php
  src/Invoice/Calculator/AbstractCalculator.php
  src/Invoice/Calculator/AbstractMergedCalculator.php
  src/Invoice/Calculator/AbstractSumInvoiceCalculator.php
  src/Invoice/Calculator/DateInvoiceCalculator.php
  src/Invoice/Calculator/DefaultCalculator.php
  src/Invoice/Calculator/ShortInvoiceCalculator.php
  src/Invoice/Calculator/UserInvoiceCalculator.php
  src/Invoice/CalculatorInterface.php
  src/Invoice/InvoiceItem.php
  src/Invoice/InvoiceModel.php
  src/Invoice/NumberGenerator/DateNumberGenerator.php
  src/Invoice/NumberGeneratorInterface.php
  src/Invoice/Renderer/AbstractSpreadsheetRenderer.php
  src/Invoice/Renderer/DocxRenderer.php
  src/Invoice/Renderer/RendererTrait.php
  src/Invoice/Renderer/TwigRenderer.php
  src/Invoice/RendererInterface.php
  templates/invoice/index.html.twig
  templates/invoice/renderer/default.html.twig
  templates/invoice/renderer/freelancer.html.twig
  tests/Invoice/Calculator/AbstractCalculatorTest.php
  tests/Invoice/Calculator/ActivityInvoiceCalculatorTest.php
  tests/Invoice/Calculator/DateInvoiceCalculatorTest.php
  tests/Invoice/Calculator/DefaultCalculatorTest.php
  tests/Invoice/Calculator/ProjectInvoiceCalculatorTest.php
  tests/Invoice/Calculator/ShortInvoiceCalculatorTest.php
  tests/Invoice/Calculator/UserInvoiceCalculatorTest.php
  tests/Invoice/InvoiceItemTest.php
  tests/Invoice/InvoiceModelTest.php
  tests/Invoice/NumberGenerator/DateNumberGeneratorTest.php
  tests/Invoice/Renderer/CsvRendererTest.php
  tests/Invoice/Renderer/DebugRenderer.php
  tests/Invoice/Renderer/DebugRendererTest.php
  tests/Invoice/Renderer/OdsRendererTest.php
  tests/Invoice/Renderer/RendererTestTrait.php
  tests/Invoice/Renderer/TwigRendererTest.php
  tests/Invoice/Renderer/XlsxRendererTest.php
  tests/Model/InvoiceModelTest.php
Labels: invoice, technical debt

#1063 added API functions to save meta fields
  src/API/ActivityController.php
  src/API/CustomerController.php
  src/API/ProjectController.php
  src/API/TimesheetController.php
  src/Repository/ActivityRepository.php
  src/Repository/CustomerRepository.php
  src/Repository/ProjectRepository.php
  src/Repository/TeamRepository.php
  src/Repository/TimesheetRepository.php
  tests/API/APIControllerBaseTest.php
  tests/API/ActivityControllerTest.php
  tests/API/CustomerControllerTest.php
  tests/API/ProjectControllerTest.php
  tests/API/TimesheetControllerTest.php
Labels: API, feature request

#1039 added korean messages
  assets/app.js
  config/packages/kimai.yaml
  config/services.yaml
  public/build/app.9530b7ca.js
  public/build/app.98c93d11.js
  public/build/entrypoints.json
  public/build/manifest.json
  translations/about.ko.xliff
  translations/actions.ko.xliff
  translations/daterangepicker.ko.xliff
  translations/exceptions.ko.xliff
  translations/flashmessages.ko.xliff
  translations/invoice-calculator.ko.xliff
  translations/invoice-numbergenerator.ko.xliff
  translations/invoice-renderer.ko.xliff
  translations/messages.ko.xliff
  translations/pagerfanta.ko.xliff
  translations/plugins.ko.xliff
  translations/system-configuration.ko.xliff
  translations/tags.ko.xliff
  translations/validators.ko.xliff
Labels: translation i18n

#1059 prepare release 1.2
  .github_changelog_generator
  CHANGELOG.md
  SECURITY.md
  UPGRADING.md
  src/Constants.php
  src/Migrations/Version20190729162655.php
Labels: release
