Repository kimai/kimai, pull requests merged in 2019-12, with the labels that each got.

#1224 loose email validation on customer
  src/Form/CustomerEditForm.php
  src/Form/Type/MailType.php
Labels: feature request

#1309 Changed Typo
  translations/system-configuration.de.xliff
Labels: translation i18n

#1308 simplify to add widgets via plugin
  src/Widget/Renderer/SimpleWidgetRenderer.php
  src/Widget/Type/SimpleWidget.php
  tests/Widget/Type/CounterTest.php
  tests/Widget/Type/MoreTest.php
Labels: feature request, technical debt

#1310 added chinese translations
  assets/app.js
  assets/calendar.js
  assets/js/KimaiLoader.js
  assets/js/plugins/KimaiFormSelect.js
  composer.lock
  config/packages/kimai.yaml
  config/services.yaml
  config/services_test.yaml
  public/build/app.23b99cbb.js
  public/build/app.e20e5313.js
  public/build/calendar.9e7cdb6a.js
  public/build/calendar.a5a217f4.js
  public/build/entrypoints.json
  public/build/manifest.json
  src/Configuration/LanguageFormattings.php
  src/Constants.php
  src/DependencyInjection/AppExtension.php
  src/Utils/LocaleSettings.php
  tests/DependencyInjection/AppExtensionTest.php
  translations/about.zh_CN.xliff
  translations/actions.zh_CN.xliff
  translations/daterangepicker.zh_CN.xliff
  translations/exceptions.zh_CN.xliff
  translations/flashmessages.zh_CN.xliff
  translations/invoice-calculator.zh_CN.xliff
  translations/invoice-numbergenerator.zh_CN.xliff
  translations/invoice-renderer.zh_CN.xliff
  translations/messages.zh_CN.xliff
  translations/pagerfanta.zh_CN.xliff
  translations/plugins.zh_CN.xliff
  translations/system-configuration.zh_CN.xliff
  translations/tags.zh_CN.xliff
  translations/teams.zh_CN.xliff
  translations/validators.zh_CN.xliff
Labels: translation i18n

#1321 fix daterange filter for multi-timezone setups
  README.md
  UPGRADING.md
  config/packages/doctrine/mysql.yaml
  config/packages/doctrine/sqlite.yaml
  src/DependencyInjection/Compiler/DoctrineCompilerPass.php
  src/Doctrine/Query/Sqlite/ConvertTz.php
  src/Repository/TimesheetRepository.php
  templates/export/index.html.twig
  templates/invoice/index.html.twig
Labels: bug

#1327 toolbar filter for exported timesheet records
  src/Form/Toolbar/TimesheetToolbarForm.php
Labels: feature request

#1326 set rates via batch update
  src/Controller/TimesheetAbstractController.php
  src/Form/MultiUpdate/TimesheetMultiUpdate.php
  src/Form/MultiUpdate/TimesheetMultiUpdateDTO.php
  src/Validator/Constraints/TimesheetMultiUpdate.php
  src/Validator/Constraints/TimesheetMultiUpdateValidator.php
  tests/Controller/PermissionControllerTest.php
  tests/Controller/TagControllerTest.php
  tests/Controller/TimesheetControllerTest.php
  tests/Controller/TimesheetTeamControllerTest.php
  tests/Controller/UserControllerTest.php
  tests/Form/MultiUpdate/TimesheetMultiUpdateDTOTest.php
  tests/Validator/Constraints/TimesheetMultiUpdateValidatorTest.php
Labels: feature request

#1338 allow empty date in export
  .editorconfig
  src/Controller/ExportController.php
  src/Form/Toolbar/AbstractToolbarForm.php
  templates/export/index.html.twig
  templates/invoice/index.html.twig
Labels: bug
