Repository kimai/kimai, pull requests merged in 2019-11, with the labels that each got.

#1214 prepare release 1.5
  .github_changelog_generator
  CHANGELOG.md
  SECURITY.md
  UPGRADING.md
  src/Constants.php
Labels: release

#1220 highlight menus on sub-pages
  src/EventSubscriber/MenuBuilderSubscriber.php
  src/EventSubscriber/MenuSubscriber.php
  src/Utils/MenuItemModel.php
Labels: feature request

#1231 User roles and permission management via Admin UI
  .gitignore
  UPGRADING.md
  assets/js/KimaiLoader.js
  assets/js/plugins/KimaiConfirmationLink.js
  config/packages/kimai.yaml
  config/packages/security.yaml
  config/routes/test/test_routes.yaml
  config/services.yaml
  public/build/app.52968b5f.js
  public/build/app.f4954bf5.js
  public/build/entrypoints.json
  public/build/manifest.json
  src/Configuration/StringAccessibleConfigTrait.php
  src/Controller/AbstractController.php
  src/Controller/CalendarController.php
  src/Controller/DashboardController.php
  src/Controller/HomepageController.php
  src/Controller/LayoutController.php
  src/Controller/PermissionController.php
  src/Controller/TimesheetController.php
  src/Controller/UserController.php
  src/DependencyInjection/Configuration.php
  src/Entity/Role.php
  src/Entity/RolePermission.php
  src/EventSubscriber/DashboardSubscriber.php
  src/Form/RoleType.php
  src/Form/Type/UserRoleType.php
  src/Migrations/Version20191108151534.php
  src/Repository/ConfigurationRepository.php
  src/Repository/RolePermissionRepository.php
  src/Repository/RoleRepository.php
  src/Security/RolePermissionManager.php
  src/Security/RoleService.php
  src/Twig/IconExtension.php
  src/Validator/Constraints/RoleValidator.php
  src/Voter/AbstractVoter.php
  src/Voter/RolePermissionVoter.php
  src/Voter/UserVoter.php
  templates/base.html.twig
  templates/dashboard/index.html.twig
  templates/macros/datatables.html.twig
  templates/user/actions.html.twig
  templates/user/edit_role.html.twig
  templates/user/permissions.html.twig
  tests/Controller/LayoutControllerTest.php
  tests/Controller/PermissionControllerTest.php
  tests/Controller/UserControllerTest.php
  tests/Entity/RolePermissionTest.php
  tests/Entity/RoleTest.php
  tests/Ldap/LdapManagerTest.php
  tests/Ldap/LdapUserHydratorTest.php
  tests/Mocks/Security/RoleServiceFactory.php
  tests/Security/RolePermissionManagerTest.php
  tests/Security/RoleServiceTest.php
  tests/Voter/AbstractVoterTest.php
  translations/messages.de.xliff
  translations/messages.en.xliff
  var/data/kimai_test.sqlite
Labels: feature request

#1251 fix reset input for forms
  assets/js/plugins/KimaiFormSelect.js
  public/build/app.09cc993e.js
  public/build/app.f4954bf5.js
  public/build/entrypoints.json
  public/build/manifest.json
Labels: bug

#1235 include bundle configuration in system configuration screen
  src/DependencyInjection/AppExtension.php
  src/Kernel.php
  src/Plugin/AbstractPluginExtension.php
  tests/DependencyInjection/AppExtensionTest.php
Labels: feature request

#1254 added money fields without currency for invoices
  src/Invoice/Renderer/AbstractSpreadsheetRenderer.php
  src/Invoice/Renderer/RendererTrait.php
  tests/Invoice/Renderer/DebugRendererTest.php
  tests/Invoice/Renderer/RendererTestTrait.php
  tests/Invoice/Renderer/TwigRendererTest.php
Labels: bug, feature request

#1261 fix the password reset page layout
  templates/bundles/FOSUserBundle/Resetting/reset.html.twig
Labels: bug

#1273 enable interactive features of Swagger UI
  config/packages/nelmio_api_doc.yaml
  src/API/ActivityController.php
  src/API/ConfigurationController.php
  src/API/CustomerController.php
  src/API/ProjectController.php
  src/API/StatusController.php
  src/API/TagController.php
  src/API/TeamController.php
  src/API/TimesheetController.php
  src/API/UserController.php
  tests/API/UserControllerTest.php
Labels: feature request

#1272 Translation: Add de_CH
  assets/app.js
  assets/calendar.js
  config/packages/kimai.yaml
  config/services.yaml
  public/build/app.b6f66654.js
  public/build/app.d5efed0e.js
  public/build/calendar.082ddfbb.js
  public/build/calendar.d3205b38.js
  public/build/entrypoints.json
  public/build/manifest.json
  translations/messages.de_CH.xliff
Labels: translation i18n

#1259 API: Allow to set user for timesheet
  src/API/TimesheetController.php
  src/Form/API/TimesheetApiEditForm.php
  src/Form/TimesheetEditForm.php
Labels: API, feature request

#1276 Select2 search enhancement
  assets/js/plugins/KimaiFormSelect.js
  public/build/app.654b112a.js
  public/build/app.b6f66654.js
  public/build/entrypoints.json
  public/build/manifest.json
Labels: feature request

#1216 added csv importer for timesheet and project data
  composer.json
  composer.lock
  src/Command/ImportProjectCommand.php
  src/Command/ImportTimesheetCommand.php
  src/Importer/InvalidFieldsException.php
  src/Importer/UnknownUserException.php
  symfony.lock
  tests/Importer/InvalidFieldsExceptionTest.php
  tests/Importer/UnknownUserExceptionTest.php
Labels: feature request

#1277 release 1.6
  .github_changelog_generator
  CHANGELOG.md
  UPGRADING.md
  assets/js/plugins/KimaiSelectDataAPI.js
  public/build/0.1a6ffb43.js
  public/build/0.a87622f3.js
  public/build/1.16767f92.js
  public/build/1.c1bee41f.js
  public/build/2.7be60d8d.js
  public/build/2.dad56560.js
  public/build/app.926c5dcb.js
  public/build/app.9b7fe418.js
  public/build/app.e5eb271e.css
  public/build/app.fe1cac78.css
  public/build/calendar.082ddfbb.js
  public/build/calendar.ade7bcdf.css
  public/build/calendar.bd4fe3ae.js
  public/build/chart.7f4d7f29.js
  public/build/entrypoints.json
  public/build/manifest.json
  public/build/runtime.6ca1eea5.js
  src/Command/CreateReleaseCommand.php
  yarn.lock
Labels: release

#1283 fix sqlite installer
  src/Command/CreateReleaseCommand.php
  src/Command/InstallCommand.php
Labels: bug, installation
