Repository kimai/kimai, pull requests merged in 2019-10, with the labels that each got.

#1154 prepare release 1.4
  .github_changelog_generator
  CHANGELOG.md
  README.md
  SECURITY.md
  UPGRADING.md
  src/Constants.php
Labels: release

#1167 Kimai 1.4.2
  CHANGELOG.md
  UPGRADING.md
  public/index.php
  src/Constants.php
  src/DependencyInjection/Configuration.php
  templates/export/index.html.twig
Labels: bug, release

#1183 Added some spanish new strings
  translations/actions.es.xliff
  translations/invoice-calculator.es.xliff
  translations/messages.es.xliff
  translations/system-configuration.es.xliff
Labels: translation i18n

#1186 added order-date field to project
  src/Entity/Project.php
  src/Form/ProjectEditForm.php
  src/Migrations/Version20191024100951.php
  tests/Entity/ProjectTest.php
  translations/messages.de.xliff
  translations/messages.en.xliff
  var/data/kimai_test.sqlite
Labels: feature request

#1160 Turkish Language Translations
  assets/app.js
  assets/calendar.js
  composer.lock
  config/packages/kimai.yaml
  config/services.yaml
  public/build/app.52968b5f.js
  public/build/app.a361daf0.js
  public/build/calendar.6f94d071.js
  public/build/calendar.c55aa90f.js
  public/build/entrypoints.json
  public/build/manifest.json
  translations/about.tr.xliff
  translations/actions.tr.xliff
  translations/daterangepicker.tr.xliff
  translations/exceptions.tr.xliff
  translations/flashmessages.tr.xliff
  translations/invoice-calculator.tr.xliff
  translations/invoice-numbergenerator.tr.xliff
  translations/invoice-renderer.tr.xliff
  translations/messages.tr.xliff
  translations/pagerfanta.tr.xliff
  translations/plugins.tr.xliff
  translations/system-configuration.tr.xliff
  translations/tags.tr.xliff
  translations/teams.tr.xliff
  translations/validators.tr.xliff
Labels: translation i18n

#1180 duration field in timesheet edit dialog
  config/serializer/App/Entity.Project.yml
  src/Form/TimesheetEditForm.php
  src/Invoice/Renderer/RendererTrait.php
  templates/default/_form.html.twig
  templates/default/_form_delete.html.twig
  templates/default/_form_modal.html.twig
  templates/embeds/modal.html.twig
  templates/form/kimai-theme.html.twig
  templates/timesheet/edit.html.twig
  tests/API/ProjectControllerTest.php
  tests/Invoice/Renderer/DebugRendererTest.php
Labels: feature request

#1191 improve list views
  src/Twig/DatatableExtensions.php
  src/Twig/IconExtension.php
  templates/activity/index.html.twig
  templates/customer/index.html.twig
  templates/macros/datatables.html.twig
  templates/project/index.html.twig
Labels: feature request

#1192 reformat edit forms
  src/Form/EntityFormTrait.php
  src/Form/Extension/IconExtension.php
  src/Form/Type/AvatarType.php
  src/Form/UserEditType.php
  templates/activity/edit.html.twig
  templates/customer/edit.html.twig
  templates/form/kimai-theme.html.twig
  templates/project/edit.html.twig
Labels: feature request

#1205 dynamic branding options
  src/Configuration/StringAccessibleConfigTrait.php
  src/Configuration/ThemeConfiguration.php
  src/Controller/SystemConfigurationController.php
  src/DependencyInjection/Compiler/TwigContextCompilerPass.php
  src/Form/Model/Configuration.php
  src/Form/Model/SystemConfiguration.php
  src/Form/Type/SystemConfigurationType.php
  src/Repository/ConfigurationRepository.php
  tests/Controller/SystemConfigurationControllerTest.php
  translations/system-configuration.de.xliff
  translations/system-configuration.en.xliff
Labels: feature request

#1210 Fix broken navigation and error pages
  src/EventSubscriber/MenuBuilderSubscriber.php
  templates/bundles/TwigBundle/Exception/error404.html.twig
  templates/error.html.twig
  tests/Controller/DashboardControllerTest.php
  tests/Controller/LayoutTest.php
  translations/exceptions.de.xliff
  translations/exceptions.en.xliff
Labels: bug
