Repository kimai/kimai, pull requests merged in 2019-09, with the labels that each got.

#1068 Post release 1.2
  UPGRADING.md
  assets/calendar.js
  public/build/calendar.5839778f.js
  public/build/calendar.e654bdd4.js
  public/build/entrypoints.json
  public/build/manifest.json
  src/Command/CreateReleaseCommand.php
  src/Controller/InvoiceController.php
  src/Form/Type/InvoiceTemplateType.php
  src/Invoice/InvoiceItem.php
  src/Invoice/Renderer/RendererTrait.php
  src/Repository/InvoiceTemplateRepository.php
  templates/invoice/renderer/default.html.twig
Labels: bug

#1077 added font-awesome paper-plane
  src/Twig/IconExtension.php
Labels: feature request

#1084 support multiple invoice repositories
  UPGRADING.md
  public/build/app.75bdc057.js
  public/build/entrypoints.json
  public/build/manifest.json
  src/Controller/InvoiceController.php
  src/DependencyInjection/Compiler/InvoiceServiceCompilerPass.php
  src/Entity/Timesheet.php
  src/Invoice/Calculator/AbstractMergedCalculator.php
  src/Invoice/Calculator/AbstractSumInvoiceCalculator.php
  src/Invoice/Calculator/ActivityInvoiceCalculator.php
  src/Invoice/Calculator/DateInvoiceCalculator.php
  src/Invoice/Calculator/DefaultCalculator.php
  src/Invoice/Calculator/ProjectInvoiceCalculator.php
  src/Invoice/Calculator/ShortInvoiceCalculator.php
  src/Invoice/Calculator/UserInvoiceCalculator.php
  src/Invoice/InvoiceItemInterface.php
  src/Invoice/InvoiceItemRepositoryInterface.php
  src/Invoice/InvoiceModel.php
  src/Invoice/Renderer/AbstractSpreadsheetRenderer.php
  src/Invoice/Renderer/DocxRenderer.php
  src/Invoice/Renderer/RendererTrait.php
  src/Invoice/ServiceInvoice.php
  src/Kernel.php
  src/Repository/Query/ActivityQuery.php
  src/Repository/Query/BaseQuery.php
  src/Repository/TimesheetInvoiceItemRepository.php
  src/Repository/TimesheetRepository.php
  translations/messages.de.xliff
  translations/messages.en.xliff
Labels: feature request, invoice

#1099 customer specific translations
  config/services.yaml
  src/DependencyInjection/AppExtension.php
  src/DependencyInjection/Configuration.php
  src/Entity/User.php
  src/Form/Type/UserType.php
  src/Utils/Translator.php
  templates/macros/widgets.html.twig
  tests/DependencyInjection/AppExtensionTest.php
  tests/DependencyInjection/ConfigurationTest.php
  tests/Entity/UserTest.php
  translations/messages.de.xliff
  translations/messages.en.xliff
Labels: feature request

#1102 release 1.3
  .github_changelog_generator
  CHANGELOG.md
  SECURITY.md
  src/Constants.php
Labels: release

#1104 Composer update
  composer.json
  composer.lock
  src/Twig/Extensions.php
  symfony.lock
  tests/Controller/ControllerBaseTest.php
  tests/Controller/ExportControllerTest.php
  tests/Controller/ProfileControllerTest.php
  tests/Controller/TimesheetControllerTest.php
  tests/Controller/TimesheetTeamControllerTest.php
  tests/Controller/UserControllerTest.php
Labels: technical debt

#1075 added czech translations
  assets/app.js
  assets/calendar.js
  config/packages/kimai.yaml
  config/services.yaml
  public/build/app.21c06505.js
  public/build/app.c72744db.js
  public/build/calendar.340fd7f1.js
  public/build/calendar.8464f183.js
  public/build/entrypoints.json
  public/build/manifest.json
  translations/about.cs.xliff
  translations/actions.cs.xliff
  translations/daterangepicker.cs.xliff
  translations/exceptions.cs.xliff
  translations/flashmessages.cs.xliff
  translations/invoice-calculator.cs.xliff
  translations/invoice-numbergenerator.cs.xliff
  translations/invoice-renderer.cs.xliff
  translations/messages.cs.xliff
  translations/pagerfanta.cs.xliff
  translations/plugins.cs.xliff
  translations/system-configuration.cs.xliff
  translations/tags.cs.xliff
  translations/validators.cs.xliff
Labels: translation i18n

#1148 fix migrations for older database versions
  src/Migrations/Version20180701120000.php
  src/Migrations/Version20180715160326.php
Labels: bug
