Repository kimai/kimai, pull requests merged in 2019-07, with the labels that each got.

#901 fix selectbox is not resettable
  src/Controller/SystemConfigurationController.php
  src/Form/Model/Configuration.php
  src/Form/Type/EnhancedSelectboxType.php
  src/Form/Type/SystemConfigurationType.php
  tests/Controller/SystemConfigurationControllerTest.php
Labels: bug

#885 Release 1.0
  .github_changelog_generator
  CHANGELOG.md
  README.md
  SECURITY.md
  UPGRADING.md
  src/Command/CreateReleaseCommand.php
  src/Constants.php
  src/Migrations/Version20190502161758.php
  tests/Command/InstallCommandTest.php
Labels: release

#915 remove scrutinizer
  .scrutinizer.yml
  src/Command/CreateReleaseCommand.php
Labels: technical debt

#913 use pre-defined icons in menu as well
  src/EventSubscriber/MenuSubscriber.php
  src/Twig/Extensions.php
  src/Twig/IconExtension.php
  tests/Twig/ExtensionsTest.php
  tests/Twig/IconExtensionTest.php
Labels: technical debt

#918 fix default calendar config
  src/DependencyInjection/Configuration.php
  tests/Controller/SystemConfigurationControllerTest.php
  tests/DependencyInjection/AppExtensionTest.php
Labels: bug

#914 fix 500 error happening in error pages
  src/Event/ThemeEvent.php
  templates/bundles/TwigBundle/Exception/error500.html.twig
  templates/error.html.twig
Labels: bug

#919 allow to configure default values for users
  config/packages/kimai.yaml
  src/Configuration/FormConfiguration.php
  src/Controller/CustomerController.php
  src/Controller/SystemConfigurationController.php
  src/DependencyInjection/Configuration.php
  src/EventSubscriber/UserPreferenceSubscriber.php
  src/Form/Model/SystemConfiguration.php
  tests/Controller/CustomerControllerTest.php
  tests/Controller/SystemConfigurationControllerTest.php
  tests/DependencyInjection/AppExtensionTest.php
  translations/system-configuration.de.xliff
  translations/system-configuration.en.xliff
Labels: feature request

#921 prod log config
  config/packages/prod/monolog.yaml
Labels: technical debt

#920 updated all composer packages
  composer.lock
  src/DependencyInjection/Compiler/DoctrineCompilerPass.php
Labels: technical debt

#922 prepare release 1.0.1
  .github_changelog_generator
  CHANGELOG.md
  SECURITY.md
  src/Constants.php
Labels: release

#931 fix LDAP edge-case initialization error
  src/Ldap/LdapDriver.php
  tests/Ldap/LdapDriverTest.php
Labels: bug

#932 allow non-interactive installation
  src/Command/InstallCommand.php
Labels: feature request

#927 performance improvements with new indices
  src/Entity/Activity.php
  src/Entity/ActivityMeta.php
  src/Entity/BudgetTrait.php
  src/Entity/Customer.php
  src/Entity/CustomerMeta.php
  src/Entity/MetaTableTypeTrait.php
  src/Entity/Project.php
  src/Entity/ProjectMeta.php
  src/Entity/Timesheet.php
  src/Entity/TimesheetMeta.php
  src/Migrations/Version20190706224211.php
  src/Migrations/Version20190706224219.php
  tests/Entity/ActivityTest.php
  tests/Entity/CustomerTest.php
  tests/Entity/ProjectTest.php
Labels: technical debt

#934 updated swedish translations
  translations/actions.sv.xliff
  translations/flashmessages.sv.xliff
  translations/messages.sv.xliff
  translations/system-configuration.sv.xliff
  translations/tags.sv.xliff
Labels: translation i18n

#940 fix changing project for existing entries
  src/Form/TimesheetEditForm.php
  tests/API/TimesheetControllerTest.php
Labels: bug

#952 added slovakian translations - by caprik
  assets/calendar.js
  config/packages/kimai.yaml
  config/services.yaml
  translations/about.sk.xliff
  translations/actions.sk.xliff
  translations/daterangepicker.sk.xliff
  translations/exceptions.sk.xliff
  translations/flashmessages.sk.xliff
  translations/invoice-calculator.sk.xliff
  translations/invoice-numbergenerator.sk.xliff
  translations/invoice-renderer.sk.xliff
  translations/messages.sk.xliff
  translations/pagerfanta.sk.xliff
  translations/plugins.sk.xliff
  translations/system-configuration.sk.xliff
  translations/tags.sk.xliff
  translations/validators.sk.xliff
Labels: translation i18n

#962 fix possible xss in timesheet description
  src/Twig/MarkdownExtension.php
  templates/export/renderer/default.html.twig
  templates/export/renderer/pdf.html.twig
  templates/invoice/index.html.twig
  templates/timesheet-team/export.html.twig
  templates/timesheet/export.html.twig
  templates/timesheet/index.html.twig
Labels: bug, security

#978 Fixes regexp for search timesheets by tag
  src/API/TimesheetController.php
  tests/API/TimesheetControllerTest.php
Labels: bug

#974 dashboard is missing in initial view
  src/Form/Type/InitialViewType.php
Labels: bug

#981 trigger template events in authentication layout as well
  templates/bundles/FOSUserBundle/Registration/confirmed.html.twig
  templates/bundles/FOSUserBundle/Registration/register.html.twig
  templates/bundles/FOSUserBundle/Resetting/request.html.twig
  templates/bundles/FOSUserBundle/Security/login.html.twig
  templates/bundles/FOSUserBundle/layout.html.twig
Labels: feature request

#983 Release 1.1
  .github_changelog_generator
  CHANGELOG.md
  SECURITY.md
  UPGRADING.md
  src/Constants.php
Labels: release

#985 fix migration for sqlite users
  src/Doctrine/AbstractMigration.php
  src/Migrations/Version20190706224219.php
Labels: bug

#989 added calendar slot_duration config
  config/packages/kimai.yaml
  src/Configuration/CalendarConfiguration.php
  src/DependencyInjection/Configuration.php
  templates/calendar/user.html.twig
  tests/Configuration/CalendarConfigurationTest.php
  tests/Controller/CalendarControllerTest.php
  tests/DependencyInjection/AppExtensionTest.php
Labels: feature request

#988 respect users timezone when populating working-time dashboard widget
  src/Repository/TimesheetRepository.php
  src/Widget/Type/DailyWorkingTimeChart.php
  templates/widget/widget-dailyworkingtimechart.html.twig
  tests/Widget/Type/DailyWorkingTimeChartTest.php
Labels: bug
