Repository kimai/kimai, pull requests merged in 2020-03, with the labels that each got.

#1505 Prepare release 1.8
  .github_changelog_generator
  CHANGELOG.md
  config/validator/validation.yaml
  src/Command/ReloadCommand.php
  src/Constants.php
  tests/Controller/SecurityControllerTest.php
  tests/Controller/UserControllerTest.php
  tests/Entity/UserValidationTest.php
Labels: release

#1521 fixing rates in kimai v1 import
  phpstan.neon
  src/Command/KimaiImporterCommand.php
Labels: bug

#1522 phpstan level 4
  .github/workflows/linting.yaml
  composer.json
  phpstan.neon
  src/API/TeamController.php
  src/Command/CreateReleaseCommand.php
  src/DependencyInjection/Compiler/ExportServiceCompilerPass.php
  src/DependencyInjection/Compiler/InvoiceServiceCompilerPass.php
  src/DependencyInjection/Compiler/WidgetCompilerPass.php
  src/EventSubscriber/TimezoneSubscriber.php
  src/EventSubscriber/UserPreferenceSubscriber.php
  src/Form/FormTrait.php
  src/Invoice/InvoiceFormatter.php
  src/Ldap/LdapUserHydrator.php
  src/Repository/Query/TimesheetQuery.php
  src/Saml/Provider/SamlProvider.php
  src/Security/DoctrineUserProvider.php
  tests/Command/CreateUserCommandTest.php
  tests/Repository/AbstractRepositoryTest.php
  tests/phpstan.neon
Labels: technical debt

#1526 inline css for html invoices
  assets/app.js
  assets/invoice.js
  assets/sass/app.scss
  assets/sass/bootstrap.scss
  assets/sass/daterangepicker.scss
  assets/sass/fontawesome.scss
  assets/sass/invoice.scss
  assets/sass/sweetalert.scss
  public/build/app.761d11cb.css
  public/build/app.a2f9e47b.js
  public/build/app.c145a319.js
  public/build/app.cc7cd665.css
  public/build/calendar.8ede69b5.css
  public/build/calendar.ed1bc977.js
  public/build/entrypoints.json
  public/build/invoice.3764169b.css
  public/build/invoice.50473330.js
  public/build/manifest.json
  src/Twig/EncoreExtension.php
  templates/invoice/layout.html.twig
  templates/invoice/renderer/timesheet.html.twig
  tests/Twig/EncoreExtensionTest.php
  tests/Twig/public/test.css
  tests/Twig/public/test1.css
  webpack.config.js
Labels: feature request, invoice

#1528 [BUGFIX] Escape distinguished name in ldap search
  src/Ldap/LdapManager.php
  tests/Ldap/LdapManagerTest.php
Labels: bug

#1533 fix pdf creation for very large exports
  src/Utils/MPdfConverter.php
  templates/export/renderer/pdf.html.twig
  tests/Controller/ExportControllerTest.php
  tests/Export/Renderer/HtmlRendererTest.php
  translations/messages.de.xlf
  translations/messages.en.xlf
Labels: bug

#1532 Import groups
  src/Command/KimaiImporterCommand.php
Labels: feature request, upgrade

#1538 Italian translations update
  .gitignore
  translations/about.it.xlf
  translations/email.it.xlf
  translations/flashmessages.it.xlf
  translations/messages.it.xlf
Labels: translation i18n

#1543 improve kimai v1 importer
  src/Command/KimaiImporterCommand.php
Labels: bug

#1530 Migrate from zend-ldap to laminas-ldap
  composer.json
  src/Ldap/LdapDriver.php
  tests/Ldap/LdapDriverTest.php
Labels: technical debt

#1544 fix deprecations in older migrations
  src/Doctrine/AbstractMigration.php
  src/Migrations/Version20180701120000.php
  src/Migrations/Version20180715160326.php
  src/Migrations/Version20180730044139.php
  src/Migrations/Version20180805183527.php
  src/Migrations/Version20180903202256.php
  src/Migrations/Version20180905190737.php
  src/Migrations/Version20180924111853.php
  src/Migrations/Version20181031220003.php
  src/Migrations/Version20190124004014.php
  src/Migrations/Version20190201150324.php
  src/Migrations/Version20190219200020.php
  src/Migrations/Version20190305152308.php
  src/Migrations/Version20190321181243.php
Labels: technical debt

#1547 show sum of duration and amount under export table
  README.md
  UPGRADING.md
  templates/export/index.html.twig
  tests/Controller/ExportControllerTest.php
Labels: export, feature request

#1545 update to latest libs
  .gitignore
  composer.json
  composer.lock
  symfony.lock
Labels: technical debt

#1542 fix timesheet permissions for non-admins
  src/Repository/TimesheetRepository.php
Labels: bug

#1548 support more columns in listings
  src/Utils/AvatarService.php
  templates/activity/index.html.twig
  templates/customer/index.html.twig
  templates/macros/widgets.html.twig
  templates/project/index.html.twig
  templates/timesheet/layout-listing.html.twig
  templates/user/index.html.twig
  translations/messages.de.xlf
  translations/messages.en.xlf
Labels: feature request

#1552 validate v1 data before import
  .gitignore
  src/Command/KimaiImporterCommand.php
Labels: feature request

#1568 switch to kimai specific user-bundle fork
  composer.json
  composer.lock
  config/packages/jms_serializer.yaml
  symfony.lock
Labels: technical debt

#1574 added command to create invoices via bash
  UPGRADING.md
  config/packages/test/security.yaml
  src/Command/InvoiceCreateCommand.php
  src/Controller/InvoiceController.php
  src/Entity/Invoice.php
  src/Entity/InvoiceTemplate.php
  src/Event/InvoiceCreatedEvent.php
  src/Form/Type/InvoiceTemplateType.php
  src/Invoice/Hydrator/InvoiceModelCustomerHydrator.php
  src/Invoice/Hydrator/InvoiceModelDefaultHydrator.php
  src/Invoice/InvoiceFilename.php
  src/Invoice/InvoiceModel.php
  src/Invoice/NumberGenerator/ConfigurableNumberGenerator.php
  src/Invoice/ServiceInvoice.php
  src/Utils/FileHelper.php
  templates/invoice/layout.html.twig
  templates/invoice/renderer/default.html.twig
  templates/invoice/renderer/freelancer.html.twig
  templates/invoice/renderer/timesheet.html.twig
  tests/Command/InvoiceCreateCommandTest.php
  tests/Controller/InvoiceControllerTest.php
  tests/Entity/InvoiceTemplateTest.php
  tests/Event/InvoiceCreatedEventTest.php
  tests/Invoice/Hydrator/InvoiceModelCustomerHydratorTest.php
  tests/Invoice/InvoiceModelTest.php
  tests/Invoice/NumberGenerator/IncrementingNumberGenerator.php
  tests/Invoice/Renderer/CsvRendererTest.php
  tests/Invoice/Renderer/DebugRendererTest.php
  tests/Invoice/Renderer/DocxRendererTest.php
  tests/Invoice/Renderer/OdsRendererTest.php
  tests/Invoice/Renderer/TwigRendererTest.php
  tests/Invoice/Renderer/XlsxRendererTest.php
  tests/Invoice/ServiceInvoiceTest.php
  tests/Invoice/templates/default.pdf.twig
  tests/KernelTestTrait.php
Labels: feature request, invoice

#1580 ensure user attributes are truncated
  composer.json
  composer.lock
  src/Entity/InvoiceTemplate.php
  src/Entity/User.php
  src/Export/Base/XlsxRenderer.php
  src/Utils/StringHelper.php
  symfony.lock
  tests/Entity/UserTest.php
  tests/Utils/StringHelperTest.php
Labels: bug

#1576 added json, xml and txt invoice renderer
  src/Constants.php
  src/Form/Type/LanguageType.php
  src/Invoice/NumberGenerator/ConfigurableNumberGenerator.php
  src/Invoice/Renderer/JsonRenderer.php
  src/Invoice/Renderer/TextRenderer.php
  src/Invoice/Renderer/XmlRenderer.php
  src/Twig/Extensions.php
  templates/doctor/index.html.twig
  templates/invoice/renderer/javascript.json.twig
  templates/invoice/renderer/text.txt.twig
  templates/invoice/renderer/xml.xml.twig
  tests/Command/InvoiceCreateCommandTest.php
  tests/Invoice/NumberGenerator/ConfigurableNumberGeneratorTest.php
  tests/Invoice/Renderer/JsonRendererTest.php
  tests/Invoice/Renderer/TextRendererTest.php
  tests/Invoice/Renderer/XmlRendererTest.php
  tests/KernelTestTrait.php
  tests/Repository/InvoiceDocumentRepositoryTest.php
  tests/Twig/ExtensionsTest.php
Labels: feature request, invoice

#1582 allow html and pdf export customization with twig templates
  .gitignore
  src/DependencyInjection/AppExtension.php
  src/DependencyInjection/Compiler/ExportServiceCompilerPass.php
  src/DependencyInjection/Compiler/TwigContextCompilerPass.php
  src/DependencyInjection/Configuration.php
  src/Export/Base/HtmlRenderer.php
  src/Export/Base/PDFRenderer.php
  src/Export/Base/RendererTrait.php
  src/Export/ExportRendererInterface.php
  src/Export/Renderer/HtmlRenderer.php
  src/Export/Renderer/HtmlRendererFactory.php
  src/Export/Renderer/PDFRenderer.php
  src/Export/Renderer/PdfRendererFactory.php
  src/Export/RendererInterface.php
  src/Export/ServiceExport.php
  src/Repository/ProjectRepository.php
  templates/export/index.html.twig
  templates/export/renderer/default-budget.pdf.twig
  templates/export/renderer/default.html.twig
  templates/export/renderer/default.pdf.twig
  templates/export/renderer/pdf.html.twig
  tests/Controller/ExportControllerTest.php
  tests/DependencyInjection/ConfigurationTest.php
  tests/Export/Renderer/AbstractRendererTest.php
  tests/Export/Renderer/HtmlRendererFactoryTest.php
  tests/Export/Renderer/HtmlRendererTest.php
  tests/Export/Renderer/PdfRendererFactoryTest.php
  tests/Export/Renderer/PdfRendererTest.php
  tests/Export/ServiceExportTest.php
  tests/Export/Timesheet/PdfRendererTest.php
  translations/export.de.xlf
  translations/export.en.xlf
Labels: export, feature request

#1592 fix non-ascii character break invoice download
  src/Invoice/InvoiceFilename.php
  tests/Invoice/InvoiceFilenameTest.php
Labels: bug

#1597 Search term fixes for API
  src/API/ActivityController.php
  src/API/CustomerController.php
  src/API/ProjectController.php
  src/API/TimesheetController.php
  src/API/UserController.php
  src/Form/ActivityEditForm.php
  templates/doctor/index.html.twig
Labels: API, bug

#1599 added event before rendering permissions
  src/Controller/PermissionController.php
  src/Event/PermissionsEvent.php
  templates/user/permissions.html.twig
  tests/Event/PermissionsEventTest.php
  translations/flashmessages.de.xlf
  translations/flashmessages.en.xlf
Labels: feature request
