Repository kimai/kimai, pull requests merged in 2020-01, with the labels that each got.

#1355 working on PHP 7.4 support
  .travis.yml
  composer.json
  composer.lock
Labels: feature request

#1372 Improve user role permissions
  src/Controller/PermissionController.php
  src/Event/PermissionSectionsEvent.php
  src/Model/PermissionSection.php
  src/Model/PermissionSectionInterface.php
  templates/user/permissions.html.twig
  tests/Controller/ControllerBaseTest.php
Labels: feature request

#1387 fix widgets imports
  templates/widget/widget-userteamprojects.html.twig
  templates/widget/widget-userteams.html.twig
Labels: bug

#1382 Basque language translation
  assets/app.js
  assets/calendar.js
  composer.lock
  config/packages/kimai.yaml
  config/services.yaml
  public/build/app.6ea4e95f.js
  public/build/app.6ece8872.js
  public/build/calendar.13664a8f.js
  public/build/calendar.9e7cdb6a.js
  public/build/entrypoints.json
  public/build/manifest.json
  translations/about.eu.xlf
  translations/actions.eu.xlf
  translations/daterangepicker.eu.xlf
  translations/exceptions.eu.xlf
  translations/flashmessages.eu.xlf
  translations/invoice-calculator.eu.xlf
  translations/invoice-numbergenerator.eu.xlf
  translations/invoice-renderer.eu.xlf
  translations/messages.eu.xlf
  translations/pagerfanta.eu.xlf
  translations/plugins.eu.xlf
  translations/system-configuration.eu.xlf
  translations/tags.eu.xlf
  translations/teams.eu.xlf
  translations/validators.eu.xlf
Labels: translation i18n

#1402 markdown autolink file urls
  src/Utils/ParsedownExtension.php
  tests/Utils/MarkdownTest.php
Labels: feature request

#1414 updated slovak translations
  composer.lock
  translations/about.sk.xlf
  translations/actions.sk.xlf
  translations/exceptions.sk.xlf
  translations/flashmessages.sk.xlf
  translations/invoice-calculator.sk.xlf
  translations/invoice-numbergenerator.sk.xlf
  translations/invoice-renderer.sk.xlf
  translations/messages.sk.xlf
  translations/plugins.sk.xlf
  translations/system-configuration.sk.xlf
  translations/teams.sk.xlf
Labels: translation i18n

#1384 API methods to handle teams and users
  config/packages/nelmio_api_doc.yaml
  config/serializer/App/Entity.Customer.yml
  config/serializer/App/Entity.Project.yml
  config/serializer/App/Entity.Team.yml
  src/API/TeamController.php
  src/API/UserController.php
  src/Controller/ProfileController.php
  src/Controller/UserController.php
  src/Entity/Team.php
  src/Entity/User.php
  src/Form/API/TeamApiEditForm.php
  src/Form/API/UserApiCreateForm.php
  src/Form/API/UserApiEditForm.php
  src/Form/TeamEditForm.php
  src/Form/UserCreateType.php
  src/Form/UserEditType.php
  src/Repository/UserRepository.php
  src/Voter/TeamVoter.php
  src/Voter/UserVoter.php
  tests/API/CustomerControllerTest.php
  tests/API/ProjectControllerTest.php
  tests/API/TeamControllerTest.php
  tests/API/UserControllerTest.php
  tests/Entity/TeamTest.php
Labels: API, feature request

#1419 Better handling of custom field columns in tables
  src/Controller/DoctorController.php
  templates/activity/index.html.twig
  templates/customer/index.html.twig
  templates/doctor/index.html.twig
  templates/project/index.html.twig
  templates/user/index.html.twig
Labels: bug

#1418 added pagination to working time widget
  config/packages/kimai.yaml
  src/Controller/WidgetController.php
  src/Repository/TimesheetRepository.php
  src/Widget/Type/DailyWorkingTimeChart.php
  src/Widget/Type/PaginatedWorkingTimeChart.php
  templates/widget/paginatedworkingtimechart.html.twig
  templates/widget/widget-dailyworkingtimechart.html.twig
  templates/widget/widget-paginatedworkingtimechart.html.twig
  tests/Widget/Type/DailyWorkingTimeChartTest.php
Labels: feature request

#1408 added support for saml login
  composer.json
  composer.lock
  config/packages/security.yaml
  config/services-saml.yaml
  config/services.yaml
  src/DependencyInjection/AppExtension.php
  src/DependencyInjection/Compiler/TwigContextCompilerPass.php
  src/DependencyInjection/Configuration.php
  src/Entity/User.php
  src/EventSubscriber/ResetPasswordSubscriber.php
  src/Kernel.php
  src/Ldap/FormLoginLdapFactory.php
  src/Ldap/LdapUserHydrator.php
  src/Ldap/LdapUserProvider.php
  src/Migrations/Version20200125123942.php
  src/Repository/UserRepository.php
  src/Saml/Controller/SamlController.php
  src/Saml/Logout/SamlLogoutHandler.php
  src/Saml/Provider/SamlProvider.php
  src/Saml/SamlAuth.php
  src/Saml/SamlTokenFactory.php
  src/Saml/Security/SamlAuthenticationSuccessHandler.php
  src/Saml/Security/SamlFactory.php
  src/Saml/User/SamlUserFactory.php
  src/Security/DoctrineUserProvider.php
  src/Voter/UserVoter.php
  symfony.lock
  templates/bundles/FOSUserBundle/Security/login.html.twig
  tests/DependencyInjection/AppExtensionTest.php
  tests/DependencyInjection/ConfigurationTest.php
  tests/Entity/UserTest.php
  tests/EventSubscriber/ResetPasswordSubscriberTest.php
  tests/Ldap/FormLoginLdapFactoryTest.php
  tests/Ldap/LdapManagerTest.php
  tests/Ldap/LdapUserProviderTest.php
  tests/Mocks/Saml/SamlAuthFactory.php
  tests/Saml/Controller/SamlControllerTest.php
  tests/Saml/Logout/SamlLogoutHandlerTest.php
  tests/Saml/Provider/SamlProviderTest.php
  tests/Saml/SamlTokenFactoryTest.php
  tests/Saml/Security/SamlAuthenticationSuccessHandlerTest.php
  tests/Saml/Security/SamlFactoryTest.php
  tests/Saml/User/SamlUserFactoryTest.php
  tests/Security/DoctrineUserProviderTest.php
  tests/Security/TestUserEntity.php
  tests/Voter/UserVoterTest.php
  var/data/kimai_test.sqlite
Labels: feature request
