Repository kimai/kimai, pull requests merged in 2020-07, with the labels that each got.

#1644 Timesheet lockdown with grace period
  config/packages/kimai.yaml
  config/services.yaml
  src/API/BaseApiController.php
  src/Configuration/TimesheetConfiguration.php
  src/Controller/SystemConfigurationController.php
  src/DependencyInjection/Configuration.php
  src/Kernel.php
  src/Validator/Constraints/Timesheet.php
  src/Validator/Constraints/TimesheetConstraint.php
  src/Validator/Constraints/TimesheetFutureTimes.php
  src/Validator/Constraints/TimesheetFutureTimesValidator.php
  src/Validator/Constraints/TimesheetLockdown.php
  src/Validator/Constraints/TimesheetLockdownValidator.php
  src/Validator/Constraints/TimesheetOverlapping.php
  src/Validator/Constraints/TimesheetOverlappingValidator.php
  src/Validator/Constraints/TimesheetRestart.php
  src/Validator/Constraints/TimesheetRestartValidator.php
  src/Validator/Constraints/TimesheetValidator.php
  tests/Configuration/TimesheetConfigurationTest.php
  tests/Controller/PermissionControllerTest.php
  tests/Controller/SystemConfigurationControllerTest.php
  tests/DependencyInjection/AppExtensionTest.php
  tests/DependencyInjection/ConfigurationTest.php
  tests/Validator/Constraints/TimesheetFutureTimesValidatorTest.php
  tests/Validator/Constraints/TimesheetLockdownValidatorTest.php
  tests/Validator/Constraints/TimesheetOverlappingValidatorTest.php
  tests/Validator/Constraints/TimesheetRestartValidatorTest.php
  tests/Validator/Constraints/TimesheetValidatorTest.php
  translations/system-configuration.de.xlf
  translations/system-configuration.en.xlf
  translations/validators.de.xlf
  translations/validators.en.xlf
Labels: feature request

#1803 Permissions
  src/Entity/Activity.php
  src/Entity/Customer.php
  src/Entity/EntityWithMetaFields.php
  src/Entity/Project.php
  src/Entity/Timesheet.php
  src/Entity/User.php
  src/EventSubscriber/AjaxAuthenticationSubscriber.php
  src/Form/Type/TeamMemberType.php
  src/Repository/ActivityRepository.php
  src/Repository/CustomerRepository.php
  src/Repository/InvoiceRepository.php
  src/Repository/ProjectRepository.php
  src/Repository/TeamRepository.php
  src/Repository/TimesheetRepository.php
  src/Repository/UserRepository.php
  tests/Entity/UserTest.php
Labels: technical debt

#1802 new translations to clarify working time periods
  templates/widget/widget-paginatedworkingtimechart.html.twig
  translations/messages.de.xlf
  translations/messages.en.xlf
Labels: technical debt, translation i18n

#1808 Enhancements
  config/serializer/App/Entity.Tag.yml
  config/validator/validation.yaml
  src/API/ConfigurationController.php
  src/API/Model/TimesheetConfig.php
  src/API/Model/Version.php
  src/API/UserController.php
  src/Controller/ProfileController.php
  src/Controller/TeamController.php
  src/Controller/UserController.php
  src/Form/API/TimesheetApiEditForm.php
  src/Form/UserApiTokenType.php
  src/Repository/Query/VisibilityTrait.php
  templates/activity/actions.html.twig
  templates/customer/actions.html.twig
  templates/project/actions.html.twig
  templates/team/actions.html.twig
  tests/API/ConfigurationControllerTest.php
  tests/API/Model/TimesheetConfigTest.php
  tests/API/TagControllerTest.php
  tests/Controller/ProfileControllerTest.php
  tests/Controller/TeamControllerTest.php
  tests/Repository/Query/VisibilityQueryTest.php
Labels: bug, feature request, technical debt

#1815 fixed team permissions on user queries
  UPGRADING.md
  config/packages/kimai.yaml
  src/Controller/PermissionController.php
  src/Entity/User.php
  src/EventSubscriber/UserEnvironmentSubscriber.php
  src/Repository/RoleRepository.php
  src/Repository/UserRepository.php
  src/Security/RolePermissionManager.php
  templates/user/permissions.html.twig
  tests/Controller/PermissionControllerTest.php
  tests/Entity/UserTest.php
Labels: bug, security

#1818 Preparations for coming features
  config/packages/doctrine/mysql.yaml
  config/packages/doctrine/sqlite.yaml
  config/services.yaml
  src/API/TimesheetController.php
  src/Doctrine/Query/Sqlite/ConvertTz.php
  src/Entity/Invoice.php
  src/Entity/Timesheet.php
  src/EventSubscriber/UserEnvironmentSubscriber.php
  src/Migrations/Version20200705152310.php
  src/Repository/Query/InvoiceQuery.php
  src/Repository/Query/TimesheetQuery.php
  src/Repository/TimesheetRepository.php
  src/Twig/LocaleExtensions.php
  tests/API/TimesheetControllerTest.php
  tests/Entity/TimesheetTest.php
  tests/Repository/Query/InvoiceQueryTest.php
  tests/Repository/Query/TimesheetQueryTest.php
  var/data/kimai_test.sqlite
Labels: feature request

#1827 added username to export
  src/Export/Base/AbstractSpreadsheetRenderer.php
  tests/Export/Renderer/CsvRendererTest.php
  tests/Export/Timesheet/CsvRendererTest.php
Labels: export, feature request

#1829 UI improvement
  src/Controller/ProfileController.php
  src/Entity/UserPreference.php
  src/EventSubscriber/UserPreferenceSubscriber.php
  src/Form/ProjectEditForm.php
  templates/activity/details.html.twig
  templates/activity/edit.html.twig
  templates/customer/actions.html.twig
  templates/customer/details.html.twig
  templates/embeds/comments.html.twig
  templates/project/actions.html.twig
  templates/project/details.html.twig
  templates/project/edit.html.twig
  templates/user/form.html.twig
  tests/Controller/ProjectControllerTest.php
  tests/Entity/UserPreferenceTest.php
Labels: bug, technical debt

#1830 Fix groupby
  src/Repository/ActivityRepository.php
  src/Repository/CustomerRepository.php
  src/Repository/InvoiceRepository.php
  src/Repository/ProjectRepository.php
Labels: bug

#1835 added some more tests
  src/Doctrine/AbstractMigration.php
  tests/Export/Spreadsheet/EntityWithMetaFieldsExporterTest.php
  tests/Mocks/Saml/SamlAuthFactory.php
  tests/Saml/Controller/SamlControllerTest.php
  tests/Saml/Provider/SamlProviderTest.php
  tests/Saml/SamlAuthTest.php
  tests/Utils/MenuItemModelTest.php
Labels: technical debt

#1836 invoice: allow to increase number, customer specific counter
  src/Invoice/NumberGenerator/ConfigurableNumberGenerator.php
  src/Repository/InvoiceRepository.php
  tests/Invoice/NumberGenerator/ConfigurableNumberGeneratorTest.php
Labels: feature request, invoice

#1837 prepare release 1.10
  .github_changelog_generator
  CHANGELOG.md
  README.md
  SECURITY.md
  UPGRADING.md
  src/Constants.php
Labels: release

#1841 Teams hidden user
  src/API/TeamController.php
  src/Form/TeamEditForm.php
  src/Form/Type/UserType.php
  src/Repository/Query/BaseFormTypeQuery.php
  src/Repository/Query/UserFormTypeQuery.php
  src/Repository/UserRepository.php
  tests/API/TeamControllerTest.php
  tests/Repository/Query/BaseFormTypeQueryTest.php
  tests/Repository/Query/UserFormTypeQueryTest.php
Labels: API, bug, technical debt

#1842 Reporting drilldown
  src/Controller/ProfileController.php
  src/Controller/ReportingController.php
  src/Form/Type/MonthPickerType.php
  src/Reporting/MonthByUserForm.php
  src/Reporting/MonthlyUserListForm.php
  src/Utils/LocaleHelper.php
  templates/form/kimai-theme.html.twig
  templates/user/actions.html.twig
  templates/user/stats.html.twig
Labels: feature request, reporting
