Repository kimai/kimai, pull requests merged in 2020-09, with the labels that each got.

#1922 bump tests to phpstan level 5
  .github/workflows/linting.yaml
  composer.json
  src/Export/Spreadsheet/Extractor/AnnotationExtractor.php
  src/Form/DataTransformer/SearchTermTransformer.php
  src/Form/DataTransformer/TagArrayToStringTransformer.php
  src/Model/TimesheetStatistic.php
  src/Twig/MarkdownExtension.php
  src/Validator/Constraints/TimesheetValidator.php
  tests/Event/SystemConfigurationEventTest.php
  tests/Export/Spreadsheet/Extractor/AnnotationExtractorTest.php
  tests/Export/Spreadsheet/Extractor/MetaFieldExtractorTest.php
  tests/Export/Spreadsheet/Extractor/UserPreferenceExtractorTest.php
  tests/Form/DataTransformer/SearchTermTransformerTest.php
  tests/Form/MultiUpdate/MultiUpdateTableDTOTest.php
  tests/Form/MultiUpdate/TimesheetMultiUpdateDTOTest.php
  tests/Mocks/Saml/SamlAuthFactory.php
  tests/Mocks/Security/CurrentUserFactory.php
  tests/Mocks/Security/RoleServiceFactory.php
  tests/Model/ActivityStatisticTest.php
  tests/Model/CustomerStatisticTest.php
  tests/Model/ProjectStatisticTest.php
  tests/Model/Statistic/DayTest.php
  tests/Model/Statistic/MonthTest.php
  tests/Model/Statistic/YearTest.php
  tests/Model/TimesheetStatisticTest.php
  tests/Repository/Query/TimesheetQueryTest.php
  tests/Repository/Query/VisibilityQueryTest.php
  tests/Security/RoleServiceTest.php
  tests/Twig/DateExtensionsTest.php
  tests/Twig/ExtensionsTest.php
  tests/Twig/LocaleExtensionsTest.php
  tests/Twig/WidgetExtensionTest.php
  tests/Utils/LocaleHelperTest.php
  tests/Validator/Constraints/TimesheetValidatorTest.php
  tests/Voter/TimesheetVoterTest.php
Labels: technical debt

#1952 User: configure first day of week
  assets/js/KimaiPlugin.js
  assets/js/KimaiTranslation.js
  assets/js/plugins/KimaiAutocomplete.js
  assets/js/plugins/KimaiDatatable.js
  assets/js/plugins/KimaiDatePicker.js
  assets/js/plugins/KimaiDateRangePicker.js
  assets/js/plugins/KimaiDateTimePicker.js
  assets/js/plugins/KimaiFormSelect.js
  assets/js/plugins/KimaiThemeInitializer.js
  public/build/app.27fcc913.js
  public/build/app.cafc411b.js
  public/build/entrypoints.json
  public/build/manifest.json
  src/Controller/HomepageController.php
  src/Controller/ProfileController.php
  src/Entity/User.php
  src/Entity/UserPreference.php
  src/EventSubscriber/UserPreferenceSubscriber.php
  src/Form/Type/FirstWeekDayType.php
  src/Mail/UserMails.php
  src/Twig/Extensions.php
  templates/base.html.twig
  templates/calendar/user.html.twig
  templates/user/form.html.twig
  tests/Controller/ProfileControllerTest.php
  tests/EventSubscriber/UserPreferenceSubscriberTest.php
  tests/Timesheet/DateTimeFactoryTest.php
  tests/Twig/ExtensionsTest.php
  translations/system-configuration.de.xlf
  translations/system-configuration.en.xlf
Labels: feature request

#1943 cleanup global context
  src/API/BaseApiController.php
  src/API/ProjectController.php
  src/API/TimesheetController.php
  src/Controller/CalendarController.php
  src/Controller/InvoiceController.php
  src/Controller/TimesheetAbstractController.php
  src/Form/Extension/UserExtension.php
  src/Invoice/ServiceInvoice.php
  tests/Invoice/ServiceInvoiceTest.php
Labels: technical debt

#1966 Translation fixes
  translations/about.he.xlf
  translations/about.ro.xlf
  translations/actions.he.xlf
  translations/actions.ro.xlf
  translations/daterangepicker.he.xlf
  translations/daterangepicker.ro.xlf
  translations/email.he.xlf
  translations/email.ro.xlf
  translations/exceptions.he.xlf
  translations/exceptions.ro.xlf
  translations/export.he.xlf
  translations/flashmessages.he.xlf
  translations/flashmessages.ro.xlf
  translations/invoice-calculator.ro.xlf
  translations/invoice-numbergenerator.ro.xlf
  translations/invoice-renderer.ro.xlf
  translations/messages.he.xlf
  translations/messages.ro.xlf
  translations/plugins.he.xlf
  translations/plugins.ro.xlf
  translations/security.vi.xlf
  translations/system-configuration.he.xlf
  translations/system-configuration.ro.xlf
  translations/tags.vi.xlf
  translations/teams.he.xlf
  translations/teams.ro.xlf
  translations/validators.he.xlf
  translations/validators.ro.xlf
Labels: technical debt, translation i18n

#1968 fixing "translation id" in hebrew and romanian
  translations/about.he.xlf
  translations/about.ro.xlf
  translations/actions.he.xlf
  translations/actions.ro.xlf
  translations/daterangepicker.he.xlf
  translations/daterangepicker.ro.xlf
  translations/email.he.xlf
  translations/email.ro.xlf
  translations/exceptions.he.xlf
  translations/exceptions.ro.xlf
  translations/export.he.xlf
  translations/flashmessages.he.xlf
  translations/flashmessages.ro.xlf
  translations/invoice-calculator.ro.xlf
  translations/invoice-numbergenerator.ro.xlf
  translations/invoice-renderer.ro.xlf
  translations/messages.he.xlf
  translations/messages.ro.xlf
  translations/plugins.he.xlf
  translations/plugins.ro.xlf
  translations/system-configuration.he.xlf
  translations/system-configuration.ro.xlf
  translations/teams.he.xlf
  translations/teams.ro.xlf
  translations/validators.he.xlf
  translations/validators.ro.xlf
Labels: translation i18n

#1969 weblate compatibility
  translations/actions.zh_CN.xlf
  translations/reporting.en.xlf
  translations/validators.eu.xlf
Labels: translation i18n

#1970 weblate compatibility
  translations/actions.ko.xlf
Labels: translation i18n

#1947 Decrement invoice counter
  src/Invoice/NumberGenerator/ConfigurableNumberGenerator.php
  tests/Invoice/NumberGenerator/ConfigurableNumberGeneratorTest.php
Labels: feature request, invoice

#1953 plugin installation command
  src/Command/AbstractBundleInstallerCommand.php
  tests/Command/BundleInstallerCommandTest.php
Labels: technical debt

#1951 Fix cwd in kimai reload
  src/Command/ReloadCommand.php
Labels: feature request

#1980 ascending order for invoice items in command
  src/Command/InvoiceCreateCommand.php
Labels: bug, invoice

#1993 fix restart timesheet with meta-fields
  src/API/TimesheetController.php
Labels: bug

#1995 Simpler configurations
  src/Command/ReloadCommand.php
  src/Configuration/StringAccessibleConfigTrait.php
  src/Controller/SystemConfigurationController.php
  src/Form/Model/SystemConfiguration.php
  src/Invoice/InvoiceModel.php
  tests/Configuration/FormConfigurationTest.php
  tests/Configuration/SystemConfigurationTest.php
  tests/Configuration/TimesheetConfigurationTest.php
  tests/Form/Model/SystemConfigurationTest.php
  tests/Invoice/InvoiceModelTest.php
Labels: technical debt

#2004 Fix user-email validation
  src/Form/UserCreateType.php
  tests/Controller/UserControllerTest.php
  tests/Timesheet/DateTimeFactoryTest.php
Labels: bug

#2005 highlight reporting in navigation for user-by-week report
  src/EventSubscriber/MenuSubscriber.php
Labels: bug
