Repository kimai/kimai, pull requests merged in 2020-10, with the labels that each got.

#2006 explain limited access if project or customer has team permission
  src/Form/Toolbar/ActivityToolbarForm.php
  templates/activity/details.html.twig
  templates/timesheet/layout-listing.html.twig
  translations/teams.de.xlf
  translations/teams.en.xlf
Labels: technical debt, translation i18n

#2007 add a i18n api field for the users "now" datetime
  src/API/ConfigurationController.php
  src/API/Model/I18nConfig.php
  tests/API/ConfigurationControllerTest.php
Labels: API, feature request

#2013 lifecycle events for projects
  config/services.yaml
  src/API/ProjectController.php
  src/Controller/ProjectController.php
  src/Event/AbstractProjectEvent.php
  src/Event/ProjectCreateEvent.php
  src/Event/ProjectCreatePostEvent.php
  src/Event/ProjectCreatePreEvent.php
  src/Event/ProjectUpdatePostEvent.php
  src/Event/ProjectUpdatePreEvent.php
  src/Project/ProjectDuplicationService.php
  src/Project/ProjectService.php
  src/Security/AccessDeniedException.php
  src/Timesheet/TimesheetService.php
  tests/Event/AbstractProjectEventTest.php
  tests/Event/ProjectCreateEventTest.php
  tests/Event/ProjectCreatePostEventTest.php
  tests/Event/ProjectCreatePreEventTest.php
  tests/Event/ProjectUpdatePostEventTest.php
  tests/Event/ProjectUpdatePreEventTest.php
  tests/Project/ProjectServiceTest.php
Labels: feature request

#2025 open create form for activity/project/customer in modals
  src/Controller/ActivityController.php
  src/Controller/ProjectController.php
  src/Form/API/ActivityApiEditForm.php
  src/Form/API/ProjectApiEditForm.php
  src/Form/ActivityEditForm.php
  src/Form/ProjectEditForm.php
  templates/activity/actions.html.twig
  templates/activity/edit.html.twig
  templates/customer/actions.html.twig
  templates/customer/edit.html.twig
  templates/project/actions.html.twig
  templates/project/edit.html.twig
  templates/user/actions.html.twig
  templates/user/edit.html.twig
  tests/Controller/ActivityControllerTest.php
  tests/Controller/CustomerControllerTest.php
  tests/Controller/ProjectControllerTest.php
Labels: feature request

#2032 Some arbitrary changes 1.11
  src/Command/KimaiImporterCommand.php
  templates/doctor/index.html.twig
Labels: feature request

#2042 added dateformat and timezone options to project importer
  src/Command/ImportProjectCommand.php
  src/Importer/AbstractProjectImporter.php
  src/Importer/DefaultProjectImporter.php
  src/Importer/ProjectImporterInterface.php
Labels: feature request

#2049 improved timesheet importer
  src/Command/ImportTimesheetCommand.php
  tests/Command/ImportTimesheetCommandTest.php
Labels: feature request

#2017 SQL performance improvements
  src/Controller/PermissionController.php
  src/Form/FormTrait.php
  src/Repository/ActivityRepository.php
  src/Repository/CustomerRepository.php
  src/Repository/InvoiceRepository.php
  src/Repository/Loader/ActivityIdLoader.php
  src/Repository/ProjectRepository.php
  src/Repository/TagRepository.php
  src/Repository/TimesheetRepository.php
  src/Repository/UserRepository.php
  src/Security/CurrentUser.php
  src/Timesheet/UserDateTimeFactory.php
  tests/Mocks/Security/CurrentUserFactory.php
  tests/Repository/Loader/ActivityLoaderTest.php
Labels: bug, technical debt

#2054 prevent spreadsheet export and invoice from breaking
  src/Export/Base/AbstractSpreadsheetRenderer.php
  src/Invoice/Renderer/AbstractSpreadsheetRenderer.php
  tests/Export/Renderer/AbstractRendererTest.php
  tests/Invoice/Renderer/RendererTestTrait.php
Labels: bug, export, invoice

#2056 Fix Composer 2 compatibility
  composer.json
  composer.lock
  src/Form/Type/DateRangeType.php
  symfony.lock
  tests/DataFixtures/TimesheetFixtures.php
Labels: technical debt

#2055 allow to configured database version via ENV var
  config/packages/doctrine.yaml
  src/DependencyInjection/Compiler/DoctrineCompilerPass.php
Labels: feature request

#2046 Finnish translations
  assets/app.js
  assets/calendar.js
  config/packages/kimai.yaml
  config/services.yaml
  public/build/app.4754599e.js
  public/build/calendar.f458a712.js
  public/build/entrypoints.json
  public/build/manifest.json
  translations/about.fi.xlf
  translations/actions.fi.xlf
  translations/daterangepicker.fi.xlf
  translations/email.fi.xlf
  translations/exceptions.fi.xlf
  translations/export.fi.xlf
  translations/flashmessages.fi.xlf
  translations/invoice-calculator.fi.xlf
  translations/invoice-numbergenerator.fi.xlf
  translations/invoice-renderer.fi.xlf
  translations/messages.fi.xlf
  translations/plugins.fi.xlf
  translations/reporting.fi.xlf
  translations/system-configuration.fi.xlf
  translations/teams.fi.xlf
  translations/validators.fi.xlf
Labels: translation i18n

#2058 Dutch translation update 1.10.2 stable
  translations/actions.nl.xlf
  translations/messages.nl.xlf
  translations/teams.nl.xlf
Labels: translation i18n

#2061 CI workflows
  .github/workflows/coverage.yaml
  .github/workflows/linting.yaml
  .github/workflows/testing.yaml
Labels: technical debt

#2060 Fix xss
  assets/js/plugins/KimaiFormSelect.js
  public/build/app.dc6c3f34.js
  public/build/calendar.541a15eb.js
  public/build/entrypoints.json
  public/build/manifest.json
  src/Twig/Extensions.php
  src/Twig/MarkdownExtension.php
  templates/activity/delete.html.twig
  templates/activity/embed_budget.html.twig
  templates/customer/delete.html.twig
  templates/customer/embed_budget.html.twig
  templates/default/_form_delete.html.twig
  templates/default/_form_delete_modal.html.twig
  templates/export/index.html.twig
  templates/export/pdf-layout.html.twig
  templates/export/renderer/default.html.twig
  templates/invoice/index.html.twig
  templates/invoice/renderer/default-pdf.pdf.twig
  templates/invoice/renderer/default.html.twig
  templates/invoice/renderer/freelancer.html.twig
  templates/project/delete.html.twig
  templates/project/embed_budget.html.twig
  templates/project/index.html.twig
  templates/timesheet/export.html.twig
  templates/timesheet/layout-listing.html.twig
  templates/user/delete.html.twig
  tests/Twig/ExtensionsTest.php
  tests/Twig/MarkdownExtensionTest.php
Labels: bug, security

#2063 prepare release 1.11
  .github_changelog_generator
  CHANGELOG.md
  SECURITY.md
  src/Constants.php
Labels: release

#2067 fix auto-stop when starting timesheet with tags
  src/Repository/TimesheetRepository.php
  src/Timesheet/TimesheetService.php
  tests/Timesheet/TimesheetServiceTest.php
Labels: bug

#2068 fix assertion deprecation
  src/Entity/ColorTrait.php
  src/Entity/Invoice.php
  src/Entity/Role.php
Labels: technical debt

#2072 validate color
  src/Entity/ColorTrait.php
  src/Form/EntityFormTrait.php
  src/Form/Type/ColorPickerType.php
  src/Utils/Color.php
  src/Validator/Constraints/HexColor.php
  src/Validator/Constraints/HexColorValidator.php
  tests/Utils/ColorTest.php
  tests/Validator/Constraints/HexColorValidatorTest.php
Labels: bug, technical debt

#2073 prepare release 1.11.1
  .github_changelog_generator
  CHANGELOG.md
  src/Constants.php
Labels: release

#2071 Translations update from Weblate
  translations/about.es.xlf
  translations/about.nl.xlf
  translations/actions.es.xlf
  translations/actions.nl.xlf
  translations/daterangepicker.es.xlf
  translations/email.es.xlf
  translations/email.pt.xlf
  translations/exceptions.es.xlf
  translations/exceptions.nl.xlf
  translations/export.es.xlf
  translations/flashmessages.es.xlf
  translations/flashmessages.nl.xlf
  translations/messages.es.xlf
  translations/messages.nl.xlf
  translations/messages.pt_BR.xlf
  translations/plugins.es.xlf
  translations/plugins.nl.xlf
  translations/reporting.es.xlf
  translations/system-configuration.es.xlf
  translations/system-configuration.nl.xlf
  translations/teams.es.xlf
  translations/teams.nl.xlf
  translations/validators.es.xlf
  translations/validators.nl.xlf
Labels: translation i18n
