Repository kimai/kimai, pull requests merged in 2020-04, with the labels that each got.

#1607 Esperanto translation
  assets/app.js
  assets/calendar.js
  composer.lock
  config/packages/kimai.yaml
  config/services.yaml
  public/build/app.803caee0.js
  public/build/app.d8c0b5e5.js
  public/build/calendar.d2540934.js
  public/build/calendar.ed1bc977.js
  public/build/entrypoints.json
  public/build/manifest.json
  translations/about.eo.xlf
  translations/actions.eo.xlf
  translations/daterangepicker.eo.xlf
  translations/email.eo.xlf
  translations/exceptions.eo.xlf
  translations/export.eo.xlf
  translations/flashmessages.eo.xlf
  translations/invoice-calculator.eo.xlf
  translations/invoice-numbergenerator.eo.xlf
  translations/invoice-renderer.eo.xlf
  translations/messages.eo.xlf
  translations/plugins.eo.xlf
  translations/system-configuration.eo.xlf
  translations/tags.eo.xlf
  translations/teams.eo.xlf
  translations/validators.eo.xlf
Labels: translation i18n

#1631 Add color to tags
  src/Entity/Tag.php
  src/Form/TagEditForm.php
  src/Migrations/Version20200413133226.php
  src/Repository/TagRepository.php
  templates/macros/widgets.html.twig
  templates/tags/index.html.twig
  tests/API/TagControllerTest.php
  tests/Entity/TagTest.php
  var/data/kimai_test.sqlite
Labels: feature request

#1640 remove roles from users when role is deleted
  src/Controller/PermissionController.php
  src/Repository/UserRepository.php
  tests/Controller/PermissionControllerTest.php
Labels: bug

#1641 show expired projects in search filter
  src/Form/ActivityEditForm.php
  src/Form/Toolbar/ActivityToolbarForm.php
  src/Form/Toolbar/TimesheetToolbarForm.php
Labels: bug

#1598 add event for updated timesheet entites
  src/API/TimesheetController.php
  src/Controller/TimesheetAbstractController.php
  src/Event/AbstractTimesheetEvent.php
  src/Event/AbstractTimesheetMultipleEvent.php
  src/Event/TimesheetCreatePostEvent.php
  src/Event/TimesheetCreatePreEvent.php
  src/Event/TimesheetDeleteMultiplePreEvent.php
  src/Event/TimesheetDeletePreEvent.php
  src/Event/TimesheetStopPostEvent.php
  src/Event/TimesheetStopPreEvent.php
  src/Event/TimesheetUpdateMultiplePostEvent.php
  src/Event/TimesheetUpdateMultiplePreEvent.php
  src/Event/TimesheetUpdatePostEvent.php
  src/Event/TimesheetUpdatePreEvent.php
  src/Timesheet/TimesheetService.php
  tests/Event/AbstractTimesheetEventTest.php
  tests/Event/AbstractTimesheetMultipleEventTest.php
  tests/Event/TimesheetCreatePostEventTest.php
  tests/Event/TimesheetCreatePreEventTest.php
  tests/Event/TimesheetDeleteMultiplePreEventTest.php
  tests/Event/TimesheetDeletePreEventTest.php
  tests/Event/TimesheetStopPostEventTest.php
  tests/Event/TimesheetStopPreEventTest.php
  tests/Event/TimesheetUpdateMultiplePostEventTest.php
  tests/Event/TimesheetUpdateMultiplePreEventTest.php
  tests/Event/TimesheetUpdatePostEventTest.php
  tests/Event/TimesheetUpdatePreEventTest.php
Labels: feature request

#1635 prepare release 1.9
  SECURITY.md
  src/Command/CreateReleaseCommand.php
  src/Constants.php
  src/Doctrine/SqliteSessionInitSubscriber.php
Labels: release

#1652 Delete Invoices
  UPGRADING.md
  src/Command/InvoiceCreateCommand.php
  src/Controller/InvoiceController.php
  src/Entity/InvoiceTemplate.php
  src/Invoice/Hydrator/InvoiceItemDefaultHydrator.php
  src/Invoice/Hydrator/InvoiceModelCustomerHydrator.php
  src/Invoice/Hydrator/InvoiceModelDefaultHydrator.php
  src/Invoice/ServiceInvoice.php
  src/Repository/InvoiceRepository.php
  src/Utils/FileHelper.php
  templates/invoice/actions.html.twig
  templates/invoice/renderer/text.txt.twig
  tests/Command/InvoiceCreateCommandTest.php
  tests/Controller/InvoiceControllerTest.php
  tests/Entity/InvoiceTemplateTest.php
  tests/Entity/UserTest.php
  tests/Invoice/Hydrator/InvoiceModelDefaultHydratorTest.php
  tests/Invoice/Renderer/DebugRendererTest.php
  tests/Invoice/Renderer/RendererTestTrait.php
  tests/Invoice/Renderer/TextRendererTest.php
Labels: feature request, invoice

#1654 fix annotation for collections
  src/API/CustomerController.php
Labels: API, bug

#1655 added translate filter for meta-fields in detail pages
  templates/activity/details.html.twig
  templates/customer/details.html.twig
  templates/project/details.html.twig
Labels: bug

#1658 support budget and timeBudget in API calls
  src/API/ActivityController.php
  src/API/CustomerController.php
  src/API/ProjectController.php
  tests/API/ActivityControllerTest.php
  tests/API/CustomerControllerTest.php
  tests/API/ProjectControllerTest.php
Labels: API

#1661 fix removing single permissions from event
  src/Event/PermissionsEvent.php
  tests/Event/PermissionsEventTest.php
Labels: bug

#1663 display more columns in invoice template listing
  templates/invoice/actions.html.twig
  templates/invoice/templates.html.twig
Labels: feature request

#1669 fixed multilineIndent
  UPGRADING.md
  src/Invoice/Renderer/CsvRenderer.php
  src/Twig/Extensions.php
  tests/Invoice/Renderer/CsvRendererTest.php
  tests/Invoice/Renderer/RendererTestTrait.php
  tests/Invoice/Renderer/TextRendererTest.php
  tests/Invoice/Renderer/TwigRendererTest.php
  tests/Invoice/templates/export.csv
  tests/Twig/ExtensionsTest.php
Labels: bug

#1672 include project name in invoice name
  src/Invoice/InvoiceFilename.php
  tests/Invoice/InvoiceFilenameTest.php
Labels: feature request, invoice
