Repository kimai/kimai, pull requests merged in 2020-11, with the labels that each got.

#2083 improve customer validation
  src/Entity/Customer.php
  tests/Entity/CustomerTest.php
Labels: bug

#2081 Translations update from Weblate
  translations/messages.es.xlf
  translations/messages.tr.xlf
Labels: translation i18n

#2085 Api doc
  config/packages/nelmio_api_doc.yaml
  templates/bundles/NelmioApiDocBundle/SwaggerUi/index.html.twig
Labels: API, feature request

#2089 sort composer packages
  src/Controller/DoctorController.php
Labels: feature request

#2097 fix styling issues in PDF invoice
  assets/sass/invoice-pdf.scss
  public/build/entrypoints.json
  public/build/invoice-pdf.340721a4.css
  public/build/invoice-pdf.cdf28364.css
  public/build/manifest.json
  src/Twig/EncoreExtension.php
  templates/invoice/renderer/default-pdf.pdf.twig
Labels: bug, invoice

#2093 Translations update from Weblate
  translations/about.ko.xlf
  translations/actions.ko.xlf
  translations/email.ko.xlf
  translations/exceptions.ko.xlf
  translations/export.ko.xlf
  translations/flashmessages.ko.xlf
  translations/messages.ko.xlf
  translations/reporting.ko.xlf
  translations/system-configuration.ko.xlf
  translations/teams.ko.xlf
  translations/validators.ko.xlf
Labels: translation i18n

#2102 Translations update from Weblate
  translations/messages.he.xlf
Labels: translation i18n

#2104 added event to manage javascript translations
  src/Event/ThemeJavascriptTranslationsEvent.php
  src/Twig/EventExtensions.php
  src/Twig/Runtime/ThemeEventExtension.php
  templates/base.html.twig
  tests/Event/ThemeJavascriptTranslationsEventTest.php
  tests/Twig/EventExtensionsTest.php
  tests/Twig/Runtime/ThemeEventExtensionTest.php
Labels: feature request

#2098 fix timesheet importer for entries passing midnight
  src/Command/ImportTimesheetCommand.php
Labels: bug

#2119 sort teams alphabetically in team_list
  templates/macros/widgets.html.twig
Labels: feature request

#2120 Re-order search form
  src/Form/Toolbar/TimesheetToolbarForm.php
  templates/export/index.html.twig
  templates/invoice/index.html.twig
Labels: bug

#2125 Updating dependencies & fixing deprecations
  composer.json
  composer.lock
  config/bundles.php
  config/packages/fos_rest.yaml
  config/packages/twig.yaml
  src/API/ActivityController.php
  src/API/CustomerController.php
  src/API/ProjectController.php
  src/API/TagController.php
  src/API/TeamController.php
  src/API/TimesheetController.php
  src/API/UserController.php
  symfony.lock
  tests/DependencyInjection/AppExtensionTest.php
  tests/DependencyInjection/ConfigurationTest.php
Labels: API, technical debt

#1509 fix timezone for timesheet created by other users
  src/Entity/Timesheet.php
  src/Timesheet/TimesheetService.php
  tests/Timesheet/TimesheetServiceTest.php
Labels: bug

#2106 Translations update from Weblate
  translations/actions.ro.xlf
  translations/actions.sk.xlf
  translations/email.sk.xlf
  translations/export.sk.xlf
  translations/flashmessages.ro.xlf
  translations/messages.ro.xlf
  translations/reporting.ro.xlf
  translations/reporting.sk.xlf
  translations/system-configuration.ro.xlf
  translations/system-configuration.sk.xlf
  translations/teams.de.xlf
  translations/teams.ro.xlf
  translations/validators.ro.xlf
Labels: translation i18n

#2135 Translations update from Weblate
  translations/actions.pl.xlf
  translations/flashmessages.pl.xlf
  translations/messages.pl.xlf
  translations/system-configuration.pl.xlf
  translations/teams.pl.xlf
  translations/validators.pl.xlf
Labels: translation i18n

#2151 fixed broken test
  tests/Invoice/Calculator/WeeklyInvoiceCalculatorTest.php
Labels: bug

#2150 overwritten console application …
  bin/console
  src/ConsoleApplication.php
Labels: feature request
