Repository kimai/kimai, pull requests merged in 2020-08, with the labels that each got.

#1861 remove usage of getenv from codebase
  UPGRADING.md
  bin/console
  config/services.yaml
  public/index.php
  src/Command/CreateReleaseCommand.php
  src/Command/ResetCommand.php
  src/Configuration/MailConfiguration.php
  src/Controller/DoctorController.php
  src/DependencyInjection/Compiler/DoctrineCompilerPass.php
  templates/doctor/index.html.twig
  tests/Command/CreateReleaseCommandTest.php
  tests/Command/ResetCommandTest.php
  tests/Configuration/MailConfigurationTest.php
  tests/Controller/DoctorControllerTest.php
Labels: technical debt

#1866 fix batch update resets export state
  src/Form/MultiUpdate/TimesheetMultiUpdate.php
Labels: bug

#1883 assign existing tag on timesheet import (#1877)
  src/Command/ImportTimesheetCommand.php
  tests/Command/ImportTimesheetCommandTest.php
Labels: bug

#1888 Fix serialize dates
  src/Entity/Activity.php
  src/Entity/Customer.php
  src/Entity/Project.php
  src/Entity/Timesheet.php
  tests/API/ProjectControllerTest.php
  tests/API/TimesheetControllerTest.php
Labels: bug

#1895 added form type to select a daytime and to prevent invalid config values
  src/Controller/SystemConfigurationController.php
  src/Form/Type/DayTimeType.php
  src/Validator/Constraints/TimeFormat.php
  src/Validator/Constraints/TimeFormatValidator.php
  tests/Controller/SystemConfigurationControllerTest.php
  tests/Validator/Constraints/TimeFormatValidatorTest.php
  translations/validators.de.xlf
  translations/validators.en.xlf
Labels: bug

#1901 the never ending group_by pagination issue
  src/Repository/ActivityRepository.php
  src/Repository/CustomerRepository.php
  src/Repository/InvoiceRepository.php
  src/Repository/ProjectRepository.php
Labels: technical debt

#1902 allow to order tables by more fields
  src/Repository/Query/ActivityQuery.php
  src/Repository/Query/CustomerQuery.php
  src/Repository/Query/ProjectQuery.php
  templates/activity/index.html.twig
  templates/customer/index.html.twig
  templates/project/index.html.twig
Labels: feature request

#1917 query widget data with user if requested
  src/Controller/WidgetController.php
  src/Repository/WidgetRepository.php
  src/Widget/Type/SimpleStatisticChart.php
  tests/Widget/Type/AbstractSimpleStatisticsWidgetTypeTest.php
  tests/Widget/Type/CounterTest.php
Labels: bug

#1927 prepare release 1.10.1
  .github_changelog_generator
  src/Constants.php
Labels: release

#1929 Update italian translations (1.10)
  translations/about.it.xlf
  translations/actions.it.xlf
  translations/email.it.xlf
  translations/exceptions.it.xlf
  translations/export.it.xlf
  translations/flashmessages.it.xlf
  translations/messages.it.xlf
  translations/plugins.it.xlf
  translations/reporting.it.xlf
  translations/system-configuration.it.xlf
  translations/validators.it.xlf
Labels: translation i18n

#1940 added support for ordering meta fields
  src/Entity/MetaTableTypeInterface.php
  src/Entity/MetaTableTypeTrait.php
  templates/activity/details.html.twig
  templates/activity/edit.html.twig
  templates/customer/details.html.twig
  templates/customer/edit.html.twig
  templates/project/details.html.twig
  templates/project/edit.html.twig
  tests/Entity/AbstractMetaEntityTest.php
Labels: feature request

#1942 bugfix release 1.10.2
  .github_changelog_generator
  CHANGELOG.md
  src/Constants.php
Labels: release
