Repository kimai/kimai, pull requests merged in 2020-02, with the labels that each got.

#1435 fixed glyphs in pdf export table header
  templates/export/renderer/pdf.html.twig
Labels: bug, export

#1437 Missing italian translations files added.
  translations/actions.it.xlf
  translations/daterangepicker.it.xlf
  translations/plugins.it.xlf
  translations/system-configuration.it.xlf
  translations/tags.it.xlf
  translations/teams.it.xlf
Labels: translation i18n

#1275 Prepare update to Symfony 4.4
  UPGRADING.md
  bin/console
  composer.json
  composer.lock
  config/packages/dev/easy_log_handler.yaml
  config/packages/twig.yaml
  config/routes/annotations.yaml
  config/routes/dev/twig.yaml
  phpunit.xml.dist
  public/index.php
  src/API/BaseApiController.php
  src/API/CustomerController.php
  src/API/ProjectController.php
  src/API/TeamController.php
  src/API/TimesheetController.php
  src/Controller/InvoiceController.php
  src/Entity/Role.php
  src/Form/Type/SearchTermType.php
  src/Invoice/Calculator/AbstractCalculator.php
  src/Invoice/CalculatorInterface.php
  src/Invoice/InvoiceModel.php
  src/Repository/TimesheetRepository.php
  symfony.lock
  templates/export/index.html.twig
  templates/invoice/index.html.twig
  templates/plugin/index.html.twig
  tests/API/TagControllerTest.php
  tests/API/TeamControllerTest.php
  tests/API/TimesheetControllerTest.php
  tests/Controller/AboutControllerTest.php
  tests/Controller/ActivityControllerTest.php
  tests/Controller/ControllerBaseTest.php
  tests/Controller/CustomerControllerTest.php
  tests/Controller/ExportControllerTest.php
  tests/Controller/InvoiceControllerTest.php
  tests/Controller/ProfileControllerTest.php
  tests/Controller/ProjectControllerTest.php
  tests/Controller/TagControllerTest.php
  tests/Controller/UserControllerTest.php
  tests/Event/ThemeEventTest.php
  tests/Event/UserPreferenceEventTest.php
  tests/EventSubscriber/RegistrationSubscriberTest.php
  tests/Invoice/Calculator/AbstractCalculatorTest.php
  tests/Invoice/Calculator/ActivityInvoiceCalculatorTest.php
  tests/Invoice/Calculator/DateInvoiceCalculatorTest.php
  tests/Invoice/Calculator/DefaultCalculatorTest.php
  tests/Invoice/Calculator/ProjectInvoiceCalculatorTest.php
  tests/Invoice/Calculator/ShortInvoiceCalculatorTest.php
  tests/Invoice/Calculator/UserInvoiceCalculatorTest.php
  tests/Invoice/InvoiceModelTest.php
  tests/Invoice/Renderer/RendererTestTrait.php
  tests/KernelTestTrait.php
  tests/Repository/WidgetRepositoryTest.php
Labels: technical debt

#1452 added github action to check code styles
  .github/workflows/coverage.yaml
  .github/workflows/linting.yaml
  .github/workflows/testing.yaml
  .travis.yml
  tests/.env.dist.mysql
  tests/.env.dist.sqlite
  tests/Invoice/Renderer/CsvRendererTest.php
  tests/Invoice/Renderer/DocxRendererTest.php
  tests/Invoice/Renderer/OdsRendererTest.php
  tests/Invoice/Renderer/TwigRendererTest.php
  tests/Invoice/Renderer/XlsxRendererTest.php
Labels: technical debt

#1451 fix passing date objects to project API
  src/API/ProjectController.php
  src/Form/ProjectEditForm.php
  tests/API/ProjectControllerTest.php
  tests/Widget/Type/DailyWorkingTimeChartTest.php
Labels: API, bug

#1426 Polish Language Translation
  assets/app.js
  assets/calendar.js
  assets/js/KimaiLoader.js
  assets/js/plugins/KimaiDatePicker.js
  assets/js/plugins/KimaiDateRangePicker.js
  assets/js/plugins/KimaiDateTimePicker.js
  assets/js/plugins/KimaiDateUtils.js
  config/packages/kimai.yaml
  config/services.yaml
  public/build/app.04b966cf.js
  public/build/app.480acc52.js
  public/build/calendar.5cc27719.js
  public/build/calendar.75c80d8f.js
  public/build/entrypoints.json
  public/build/manifest.json
  translations/about.pl.xlf
  translations/actions.pl.xlf
  translations/daterangepicker.pl.xlf
  translations/exceptions.pl.xlf
  translations/flashmessages.pl.xlf
  translations/invoice-calculator.pl.xlf
  translations/invoice-numbergenerator.pl.xlf
  translations/invoice-renderer.pl.xlf
  translations/messages.pl.xlf
  translations/pagerfanta.pl.xlf
  translations/plugins.pl.xlf
  translations/system-configuration.pl.xlf
  translations/tags.pl.xlf
  translations/teams.pl.xlf
  translations/validators.pl.xlf
Labels: translation i18n

#1458 remove pagerfanta bundle
  composer.json
  composer.lock
  config/bundles.php
  src/Twig/PaginationExtension.php
  src/Utils/Translator.php
  symfony.lock
  templates/customer/embed_projects.html.twig
  templates/macros/datatables.html.twig
  templates/project/embed_activities.html.twig
  tests/Twig/PaginationExtensionTest.php
  translations/pagerfanta.ar.xlf
  translations/pagerfanta.cs.xlf
  translations/pagerfanta.da.xlf
  translations/pagerfanta.de.xlf
  translations/pagerfanta.en.xlf
  translations/pagerfanta.es.xlf
  translations/pagerfanta.eu.xlf
  translations/pagerfanta.fr.xlf
  translations/pagerfanta.hu.xlf
  translations/pagerfanta.it.xlf
  translations/pagerfanta.ja.xlf
  translations/pagerfanta.ko.xlf
  translations/pagerfanta.nl.xlf
  translations/pagerfanta.pl.xlf
  translations/pagerfanta.pt_BR.xlf
  translations/pagerfanta.ru.xlf
  translations/pagerfanta.sk.xlf
  translations/pagerfanta.sv.xlf
  translations/pagerfanta.tr.xlf
  translations/pagerfanta.zh_CN.xlf
Labels: technical debt

#1463 added option to use only pre-defined tags
  src/Command/ImportCustomerCommand.php
  src/Configuration/ThemeConfiguration.php
  src/Controller/SystemConfigurationController.php
  src/DependencyInjection/Configuration.php
  src/Form/API/TimesheetApiEditForm.php
  src/Form/FormTrait.php
  src/Form/MultiUpdate/TimesheetMultiUpdate.php
  src/Form/Toolbar/AbstractToolbarForm.php
  src/Form/Type/TagsInputType.php
  src/Form/Type/TagsSelectType.php
  src/Form/Type/TagsType.php
  tests/Configuration/ThemeConfigurationTest.php
  tests/DependencyInjection/AppExtensionTest.php
  tests/DependencyInjection/ConfigurationTest.php
  translations/system-configuration.de.xlf
  translations/system-configuration.en.xlf
Labels: feature request

#1462 Replaced mailer library, added first templates
  .env.dist
  UPGRADING.md
  assets/css/emails.css
  composer.json
  composer.lock
  config/bundles.php
  config/packages/dev/mailer.yaml
  config/packages/dev/swiftmailer.yaml
  config/packages/fos_user.yaml
  config/packages/mailer.yaml
  config/packages/swiftmailer.yaml
  config/packages/test/mailer.yaml
  config/packages/test/swiftmailer.yaml
  config/packages/twig.yaml
  phpunit.xml.dist
  src/Configuration/MailConfiguration.php
  src/Controller/DoctorController.php
  src/EventSubscriber/RegistrationSubscriber.php
  src/Mail/KimaiMailer.php
  src/Mail/UserMails.php
  symfony.lock
  templates/emails/confirmation.html.twig
  templates/emails/layout.html.twig
  templates/emails/password-reset.html.twig
  tests/Configuration/MailConfigurationTest.php
  tests/EventSubscriber/RegistrationSubscriberTest.php
  tests/Mail/KimaiMailerTest.php
  tests/Mail/UserMailsTest.php
  translations/email.de.xlf
  translations/email.en.xlf
Labels: feature request, technical debt

#1465 feature: duplicate projects with all settings
  src/Controller/ProjectController.php
  src/Entity/Activity.php
  src/Entity/MetaTableTypeTrait.php
  src/Entity/Project.php
  src/Entity/Rate.php
  src/Project/ProjectDuplicationService.php
  src/Repository/ActivityRepository.php
  templates/activity/actions.html.twig
  templates/project/actions.html.twig
  templates/project/embed_activities.html.twig
  tests/API/APIControllerBaseTest.php
  tests/API/ActivityControllerTest.php
  tests/API/CustomerControllerTest.php
  tests/API/ProjectControllerTest.php
  tests/API/TeamControllerTest.php
  tests/API/TimesheetControllerTest.php
  tests/Controller/ActivityControllerTest.php
  tests/Controller/CalendarControllerTest.php
  tests/Controller/ControllerBaseTest.php
  tests/Controller/CustomerControllerTest.php
  tests/Controller/ExportControllerTest.php
  tests/Controller/HomepageControllerTest.php
  tests/Controller/InvoiceControllerTest.php
  tests/Controller/LayoutControllerTest.php
  tests/Controller/PermissionControllerTest.php
  tests/Controller/ProfileControllerTest.php
  tests/Controller/ProjectControllerTest.php
  tests/Controller/SystemConfigurationControllerTest.php
  tests/Controller/TagControllerTest.php
  tests/Controller/TeamControllerTest.php
  tests/Controller/TimesheetControllerTest.php
  tests/Controller/TimesheetTeamControllerTest.php
  tests/Controller/UserControllerTest.php
  tests/KernelTestTrait.php
Labels: feature request

#1472 Improve firewall
  config/packages/security.yaml
  src/Repository/ConfigurationRepository.php
Labels: feature request

#1478 action to duplicate timesheet record
  src/API/TimesheetController.php
  src/Entity/Timesheet.php
  src/Voter/TimesheetVoter.php
  templates/timesheet/actions.html.twig
  tests/API/TimesheetControllerTest.php
Labels: feature request

#1490 allow to edit single system config section in modal
  src/Controller/SystemConfigurationController.php
  templates/system-configuration/index.html.twig
  tests/Controller/SystemConfigurationControllerTest.php
Labels: feature request

#1491 human friendly name for bundles
  src/Controller/PermissionController.php
  src/Plugin/Plugin.php
  src/Plugin/PluginManager.php
  templates/plugin/index.html.twig
  tests/Command/PluginCommandTest.php
  tests/Plugin/PluginManagerTest.php
  tests/Plugin/PluginTest.php
Labels: feature request

#1489 Use decimal format in user timesheet export
  src/DataFixtures/TimesheetFixtures.php
  src/EventSubscriber/UserPreferenceSubscriber.php
  src/Export/Base/HtmlRenderer.php
  src/Export/Base/PDFRenderer.php
  src/Export/Timesheet/HtmlRenderer.php
  templates/export/renderer/default.html.twig
  templates/export/renderer/pdf.html.twig
  templates/timesheet-team/actions.html.twig
  templates/timesheet/actions.html.twig
  templates/timesheet/export.html.twig
  templates/user/layout.html.twig
  translations/messages.de.xlf
  translations/messages.en.xlf
Labels: feature request

#1495 Upload invoice documents via UI
  UPGRADING.md
  config/packages/kimai.yaml
  src/Controller/InvoiceController.php
  src/Entity/InvoiceDocument.php
  src/Form/InvoiceDocumentUploadForm.php
  src/Repository/InvoiceDocumentRepository.php
  src/Twig/IconExtension.php
  templates/invoice/actions.html.twig
  templates/invoice/document_upload.html.twig
  tests/Controller/InvoiceControllerTest.php
  tests/Controller/PermissionControllerTest.php
  tests/Entity/InvoiceDocumentTest.php
  translations/invoice-renderer.de.xlf
  translations/invoice-renderer.en.xlf
  translations/messages.de.xlf
  translations/messages.en.xlf
Labels: feature request

#1506 added configuration for default start-time
  src/Controller/SystemConfigurationController.php
  src/Form/Type/DateTimeTextType.php
  src/Validator/Constraints/DateTimeFormat.php
  src/Validator/Constraints/DateTimeFormatValidator.php
  tests/Controller/SystemConfigurationControllerTest.php
  tests/Validator/Constraints/DateTimeFormatValidatorTest.php
  translations/system-configuration.de.xlf
  translations/system-configuration.en.xlf
Labels: feature request

#1507 format excel cell types in invoices
  UPGRADING.md
  src/Invoice/Renderer/AbstractSpreadsheetRenderer.php
  src/Invoice/Renderer/AdvancedValueBinder.php
  tests/Invoice/Renderer/CsvRendererTest.php
  tests/Invoice/Renderer/RendererTestTrait.php
  tests/Invoice/Renderer/XlsxRendererTest.php
Labels: bug
