Repository kimai/kimai, pull requests merged in 2021-08, with the labels that each got.

#2698 Add a calendar configuration event
  src/Calendar/CalendarService.php
  src/Controller/CalendarController.php
  src/Event/CalendarConfigurationEvent.php
  tests/Event/CalendarConfigurationEventTest.php
Labels: calendar

#2701 move supported languages logic to service
  config/services.yaml
  src/Controller/HomepageController.php
  src/EventSubscriber/RedirectToLocaleSubscriber.php
  src/Form/Type/LanguageType.php
  src/Utils/LanguageService.php
  tests/EventSubscriber/RedirectToLocaleSubscriberTest.php
  tests/Utils/LanguageServiceTest.php
Labels: technical debt

#2700 Classical cleanup PR
  src/Entity/Timesheet.php
  src/EventSubscriber/LastLoginSubscriber.php
  src/Form/ActivityRateForm.php
  src/Form/CustomerRateForm.php
  src/Form/ProjectRateForm.php
  src/Invoice/ServiceInvoice.php
  src/Model/Statistic/BudgetStatistic.php
  tests/Configuration/SystemConfigurationTest.php
  tests/Invoice/ServiceInvoiceTest.php
Labels: technical debt

#2704 Fixes for 1.15
  composer.json
  composer.lock
  phpstan.neon
  src/DataFixtures/CustomerFixtures.php
  src/DataFixtures/InvoiceFixtures.php
  src/DataFixtures/TeamFixtures.php
  src/Entity/Team.php
  src/Entity/User.php
  src/Form/Toolbar/AbstractToolbarForm.php
  src/Migrations/Version20210719123928.php
  symfony.lock
  tests/DataFixtures/ActivityFixtures.php
  tests/DataFixtures/CustomerFixtures.php
  tests/DataFixtures/InvoiceTemplateFixtures.php
  tests/DataFixtures/ProjectFixtures.php
  tests/DataFixtures/TeamFixtures.php
  tests/DataFixtures/TimesheetFixtures.php
  tests/Entity/TeamTest.php
  tests/phpstan.neon
Labels: technical debt

#2712 fix user stats in profile for first year
  src/Controller/ProfileController.php
  src/Timesheet/DateTimeFactory.php
  tests/Timesheet/DateTimeFactoryTest.php
Labels: bug

#2672 Translations update from Weblate
  tests/TranslationsTest.php
  translations/actions.sv.xlf
  translations/email.el.xlf
  translations/email.pt_BR.xlf
  translations/email.sv.xlf
  translations/export.pt_BR.xlf
  translations/export.zh_CN.xlf
  translations/flashmessages.sv.xlf
  translations/messages.cs.xlf
  translations/messages.el.xlf
  translations/messages.fr.xlf
  translations/messages.he.xlf
  translations/messages.pt_BR.xlf
  translations/messages.ru.xlf
  translations/messages.sv.xlf
  translations/messages.tr.xlf
  translations/messages.zh_CN.xlf
  translations/reporting.el.xlf
  translations/reporting.fr.xlf
  translations/reporting.he.xlf
  translations/reporting.it.xlf
  translations/reporting.pt_BR.xlf
  translations/reporting.sv.xlf
  translations/reporting.tr.xlf
  translations/system-configuration.el.xlf
  translations/system-configuration.it.xlf
  translations/system-configuration.sv.xlf
  translations/system-configuration.zh_CN.xlf
  translations/teams.pt_BR.xlf
  translations/teams.sv.xlf
  translations/validators.he.xlf
  translations/validators.it.xlf
  translations/validators.pt_BR.xlf
  translations/validators.sv.xlf
  translations/validators.tr.xlf
  translations/validators.zh_CN.xlf
Labels: translation i18n

#2716 fix team edit with deactivated users
  src/Form/TeamEditForm.php
  src/Form/Type/TeamMemberType.php
  templates/form/kimai-theme.html.twig
Labels: bug

#2730 prevent email or username becoming non-unique
  src/Repository/UserRepository.php
  src/User/UserService.php
  src/Validator/Constraints/User.php
  src/Validator/Constraints/UserValidator.php
  tests/Validator/Constraints/UserValidatorTest.php
  translations/validators.de.xlf
  translations/validators.en.xlf
Labels: bug
