Repository kimai/kimai, pull requests merged in 2021-11, with the labels that each got.

#2893 fix weekly view day format
  src/Controller/QuickEntryController.php
  src/EventSubscriber/Actions/ProjectSubscriber.php
  src/EventSubscriber/Actions/QuickEntrySubscriber.php
  src/EventSubscriber/Actions/TimesheetsSubscriber.php
  src/EventSubscriber/MenuSubscriber.php
  src/Twig/LocaleFormatExtensions.php
  templates/form/kimai-theme.html.twig
  templates/quick-entry/index.html.twig
  templates/reporting/report_by_user.html.twig
  templates/reporting/report_user_list.html.twig
  tests/Controller/QuickEntryControllerTest.php
  tests/Controller/TimesheetControllerTest.php
  tests/Twig/LocaleFormatExtensionsTest.php
  translations/messages.de.xlf
Labels: bug, technical debt

#2898 activate bleeding edge rules for phpstan and fix problems
  composer.lock
  phpstan.neon
  src/API/ActivityController.php
  src/API/Model/I18nConfig.php
  src/API/Model/TimesheetConfig.php
  src/API/ProjectController.php
  src/API/TimesheetController.php
  src/Activity/ActivityStatisticService.php
  src/Command/InstallCommand.php
  src/Command/KimaiImporterCommand.php
  src/Command/UpdateCommand.php
  src/Controller/Reporting/ReportByUserController.php
  src/Controller/Reporting/ReportUsersListController.php
  src/Controller/TeamController.php
  src/Customer/CustomerStatisticService.php
  src/Doctrine/AbstractMigration.php
  src/Entity/Configuration.php
  src/Entity/Invoice.php
  src/Entity/Role.php
  src/Entity/RolePermission.php
  src/Entity/Tag.php
  src/Entity/TeamMember.php
  src/Entity/User.php
  src/Form/Extension/SelectWithApiDataExtension.php
  src/Form/QuickEntryForm.php
  src/Form/TimesheetEditForm.php
  src/Invoice/ServiceInvoice.php
  src/Ldap/LdapAuthenticationProvider.php
  src/Repository/ConfigurationRepository.php
  src/Widget/Type/UserTeamProjects.php
  tests/Command/InstallCommandTest.php
  tests/Command/UpdateCommandTest.php
Labels: technical debt

#2899 added invoice replacer for currently logged-in user
  src/Invoice/NumberGenerator/ConfigurableNumberGenerator.php
  src/Repository/InvoiceRepository.php
  tests/Invoice/NumberGenerator/ConfigurableNumberGeneratorTest.php
Labels: feature request, invoice

#2900 composer upgrade
  composer.json
  composer.lock
  phpstan.neon
  tests/Export/Spreadsheet/Entities/DemoFull.php
  tests/Export/Spreadsheet/Entities/ExpressionOnProperty.php
  tests/Saml/Security/SamlAuthenticationSuccessHandlerTest.php
  tests/phpstan.neon
Labels: technical debt

#2901 prevent empty migration warning
  src/Doctrine/AbstractMigration.php
  src/Migrations/Version20190219200020.php
  src/Migrations/Version20190706224211.php
  src/Migrations/Version20190729162655.php
  src/Migrations/Version20191113132640.php
  src/Migrations/Version20200323163039.php
  src/Migrations/Version20210802152814.php
  src/Migrations/Version20210802174319.php
Labels: technical debt

#2849 include roles and teams in user create form
  src/Controller/UserController.php
  src/Form/UserCreateType.php
  templates/user/create.html.twig
Labels: feature request

#2904 optimizations
  assets/js/plugins/KimaiDatePicker.js
  assets/js/plugins/KimaiDateRangePicker.js
  assets/js/plugins/KimaiDateTimePicker.js
  config/packages/kimai.yaml
  package.json
  public/build/app.3947eaef.js
  public/build/app.3947eaef.js.LICENSE.txt
  public/build/app.da44b7f8.js
  public/build/entrypoints.json
  public/build/manifest.json
  src/Controller/QuickEntryController.php
  src/EventSubscriber/MenuSubscriber.php
  src/EventSubscriber/ThemeOptionsSubscriber.php
  src/Form/Type/SkinType.php
  src/Twig/LocaleFormatExtensions.php
  src/Utils/LocaleFormatter.php
  templates/macros/widgets.html.twig
  templates/project/details.html.twig
  templates/project/index.html.twig
  tests/Controller/PermissionControllerTest.php
  yarn.lock
Labels: feature request

#2850 Translations update from Weblate
  translations/messages.de.xlf
  translations/messages.de_CH.xlf
  translations/messages.en.xlf
  translations/messages.fr.xlf
  translations/messages.he.xlf
  translations/messages.hr.xlf
  translations/messages.it.xlf
  translations/messages.nb-NO.xlf
  translations/messages.pt.xlf
  translations/messages.pt_BR.xlf
  translations/messages.ro.xlf
  translations/messages.ru.xlf
  translations/messages.sv.xlf
  translations/messages.tr.xlf
  translations/messages.zh_CN.xlf
  translations/validators.ar.xlf
  translations/validators.fr.xlf
  translations/validators.he.xlf
  translations/validators.pt.xlf
  translations/validators.pt_BR.xlf
  translations/validators.ro.xlf
  translations/validators.tr.xlf
Labels: translation i18n

#2916 do not reset password for LDAP and SAML users unless needed
  src/Ldap/LdapUserHydrator.php
  src/Saml/User/SamlUserFactory.php
  src/Security/TokenAuthenticator.php
  tests/Security/TokenAuthenticatorTest.php
Labels: bug, security, API

#2922 added new invoice status: canceled
  src/Controller/ExportController.php
  src/Entity/Invoice.php
  src/EventSubscriber/Actions/InvoiceSubscriber.php
  src/Invoice/ServiceInvoice.php
  templates/invoice/listing.html.twig
  templates/invoice/macros.html.twig
  translations/actions.de.xlf
  translations/actions.en.xlf
  translations/messages.de.xlf
  translations/messages.en.xlf
Labels: feature request, invoice

#2736 PDF memory optimizations
  SECURITY.md
  src/Utils/MPdfConverter.php
  templates/export/pdf-layout.html.twig
  templates/invoice/renderer/default-pdf.pdf.twig
  templates/invoice/renderer/freelancer.pdf.twig
Labels: help wanted, technical debt

#2747 added ProjectConstraint to add dynamic project validation
  config/services.yaml
  src/Kernel.php
  src/Validator/Constraints/ProjectConstraint.php
  src/Validator/Constraints/ProjectValidator.php
Labels: feature request

#2789 allow to set 24 hour format as user preference
  .env.dist
  UPGRADING.md
  composer.json
  config/packages/kimai.yaml
  src/API/ConfigurationController.php
  src/API/Model/I18nConfig.php
  src/Configuration/LanguageFormattings.php
  src/DependencyInjection/Configuration.php
  src/Entity/User.php
  src/Entity/UserPreference.php
  src/EventSubscriber/UserPreferenceSubscriber.php
  src/Form/Type/DateTimePickerType.php
  src/Twig/LocaleFormatExtensions.php
  src/Utils/DateFormatConverter.php
  src/Utils/LocaleFormats.php
  src/Utils/LocaleFormatter.php
  src/Utils/MomentFormatConverter.php
  templates/base.html.twig
  templates/export/renderer/default.html.twig
  tests/API/ConfigurationControllerTest.php
  tests/API/Model/I18nConfigTest.php
  tests/Configuration/LanguageFormattingsTest.php
  tests/Controller/ProfileControllerTest.php
  tests/Entity/UserTest.php
  tests/EventSubscriber/UserPreferenceSubscriberTest.php
  tests/Export/Renderer/AbstractRendererTest.php
  tests/Export/Renderer/HtmlRendererTest.php
  tests/Export/Timesheet/AbstractRendererTest.php
  tests/Twig/LocaleFormatExtensionsTest.php
  tests/Utils/LocaleFormatsTest.php
  translations/messages.de.xlf
  translations/messages.en.xlf
Labels: feature request, technical debt

#2930 link to doctor
  src/Controller/DoctorController.php
  templates/doctor/index.html.twig
Labels: bug, security

#2931 submit invoice search after changing the template
  templates/invoice/index.html.twig
Labels: feature request, invoice

#2915 Translations update from Weblate
  translations/actions.el.xlf
  translations/actions.fr.xlf
  translations/actions.he.xlf
  translations/actions.it.xlf
  translations/actions.pt.xlf
  translations/actions.pt_BR.xlf
  translations/actions.ro.xlf
  translations/actions.tr.xlf
  translations/flashmessages.zh_CN.xlf
  translations/messages.de.xlf
  translations/messages.de_CH.xlf
  translations/messages.el.xlf
  translations/messages.es.xlf
  translations/messages.fr.xlf
  translations/messages.he.xlf
  translations/messages.hr.xlf
  translations/messages.it.xlf
  translations/messages.pt.xlf
  translations/messages.pt_BR.xlf
  translations/messages.ro.xlf
  translations/messages.tr.xlf
  translations/system-configuration.de.xlf
  translations/system-configuration.el.xlf
  translations/system-configuration.en.xlf
  translations/system-configuration.fr.xlf
  translations/system-configuration.he.xlf
  translations/system-configuration.hr.xlf
  translations/system-configuration.it.xlf
  translations/system-configuration.pt.xlf
  translations/system-configuration.pt_BR.xlf
  translations/system-configuration.ro.xlf
  translations/system-configuration.tr.xlf
  translations/system-configuration.zh_CN.xlf
  translations/validators.el.xlf
  translations/validators.hr.xlf
  translations/validators.it.xlf
  translations/validators.zh_CN.xlf
Labels: translation i18n

#2932 improve error handling during invoice generation
  config/packages/kimai.yaml
  src/Command/InvoiceCreateCommand.php
  src/EventSubscriber/Actions/InvoiceSubscriber.php
  src/Invoice/DuplicateInvoiceNumberException.php
  src/Invoice/NumberGenerator/ConfigurableNumberGenerator.php
  src/Invoice/ServiceInvoice.php
  tests/Controller/PermissionControllerTest.php
Labels: bug, feature request, invoice

#2905 Fetch user preferences via API
  config/packages/nelmio_api_doc.yaml
  src/API/UserController.php
  src/Entity/User.php
  src/Entity/UserPreference.php
  tests/API/APIControllerBaseTest.php
Labels: feature request, API

#2936 improve csrf handling
  src/Controller/CustomerController.php
  src/Controller/DoctorController.php
  src/Controller/InvoiceController.php
  src/Controller/PermissionController.php
  src/Controller/ProjectController.php
  src/EventSubscriber/Actions/InvoiceTemplateSubscriber.php
  templates/customer/details.html.twig
  templates/embeds/comments.html.twig
  templates/invoice/actions.html.twig
  templates/project/details.html.twig
  tests/Controller/CustomerControllerTest.php
  tests/Controller/InvoiceControllerTest.php
  tests/Controller/ProjectControllerTest.php
  translations/flashmessages.de.xlf
  translations/flashmessages.en.xlf
Labels: bug, security

#2929 Release 1.16
  .github_changelog_generator
  SECURITY.md
  src/Constants.php
  src/DependencyInjection/Compiler/ExportServiceCompilerPass.php
  src/Kernel.php
  src/Twig/LocaleFormatExtensions.php
  translations/actions.de.xlf
  translations/actions.el.xlf
  translations/actions.en.xlf
  translations/actions.fr.xlf
  translations/actions.he.xlf
  translations/actions.hr.xlf
  translations/actions.it.xlf
  translations/actions.pt.xlf
  translations/actions.pt_BR.xlf
  translations/actions.tr.xlf
  translations/messages.de.xlf
  translations/messages.de_CH.xlf
  translations/messages.el.xlf
  translations/messages.en.xlf
  translations/messages.es.xlf
  translations/messages.fr.xlf
  translations/messages.he.xlf
  translations/messages.hr.xlf
  translations/messages.it.xlf
  translations/messages.pt.xlf
  translations/messages.pt_BR.xlf
  translations/messages.tr.xlf
  translations/system-configuration.de.xlf
  translations/system-configuration.el.xlf
  translations/system-configuration.en.xlf
  translations/system-configuration.fr.xlf
  translations/system-configuration.he.xlf
  translations/system-configuration.hr.xlf
  translations/system-configuration.it.xlf
  translations/system-configuration.pt.xlf
  translations/system-configuration.pt_BR.xlf
  translations/system-configuration.ro.xlf
  translations/system-configuration.tr.xlf
Labels: release

#2937 deactivate patch percentage
  .codecov.yml
Labels: technical debt

#2938 1.16.1
  src/Repository/ProjectRepository.php
  src/Repository/TeamRepository.php
  src/Repository/TimesheetRepository.php
  templates/embeds/comments.html.twig
Labels: bug, release

#2942 1.16.2
  src/Constants.php
  src/Controller/ProjectController.php
  src/Controller/TeamController.php
  src/Controller/TimesheetAbstractController.php
  src/Controller/TimesheetController.php
  src/Controller/TimesheetTeamController.php
  src/EventSubscriber/Actions/AbstractTimesheetSubscriber.php
  src/EventSubscriber/Actions/ProjectSubscriber.php
  src/EventSubscriber/Actions/TeamSubscriber.php
  src/Migrations/Version20180701120000.php
  src/Migrations/Version20180715160326.php
  src/Migrations/Version20180730044139.php
  src/Migrations/Version20180924111853.php
  src/Migrations/Version20181031220003.php
  src/Migrations/Version20190305152308.php
  src/Migrations/Version20210802152814.php
  src/Migrations/Version20211008092010.php
  templates/form/kimai-theme.html.twig
  templates/project/actions.html.twig
  templates/team/actions.html.twig
  templates/timesheet-team/actions.html.twig
  templates/timesheet/actions.html.twig
  tests/Controller/ControllerBaseTest.php
  tests/Controller/DoctorControllerTest.php
  tests/Controller/ProjectControllerTest.php
  tests/Controller/TeamControllerTest.php
  tests/Controller/TimesheetControllerTest.php
  tests/Controller/TimesheetTeamControllerTest.php
  translations/about.ja.xlf
  translations/flashmessages.el.xlf
  translations/flashmessages.fr.xlf
  translations/flashmessages.he.xlf
  translations/flashmessages.pt.xlf
  translations/flashmessages.pt_BR.xlf
  translations/flashmessages.tr.xlf
  translations/messages.de.xlf
  translations/messages.en.xlf
Labels: bug

#2948 Update CSRF Token IDs for Issue kevinpapst/kimai2#2947
  src/Constants.php
  src/Controller/CustomerController.php
  src/Controller/DoctorController.php
  src/Controller/InvoiceController.php
  src/Controller/ProjectController.php
  src/Controller/TeamController.php
  src/Controller/TimesheetAbstractController.php
  src/Controller/TimesheetController.php
  src/Controller/TimesheetTeamController.php
  src/EventSubscriber/Actions/AbstractTimesheetSubscriber.php
  templates/timesheet-team/actions.html.twig
  templates/timesheet/actions.html.twig
  tests/Controller/CustomerControllerTest.php
  tests/Controller/ProjectControllerTest.php
  tests/Controller/TimesheetControllerTest.php
  tests/Controller/TimesheetTeamControllerTest.php
Labels: bug, security

#2958 improve export filename
  src/Export/Base/AbstractSpreadsheetRenderer.php
  src/Export/Base/PDFRenderer.php
  src/Export/ExportFilename.php
  tests/Export/ExportFilenameTest.php
  tests/Export/Renderer/CsvRendererTest.php
  tests/Export/Renderer/PdfRendererTest.php
  tests/Export/Renderer/XlsxRendererTest.php
  tests/Export/Timesheet/CsvRendererTest.php
  tests/Export/Timesheet/PdfRendererTest.php
  tests/Export/Timesheet/XlsxRendererTest.php
Labels: feature request, export

#2959 escape input from customer, project and activity
  assets/js/KimaiPlugin.js
  assets/js/plugins/KimaiRecentActivities.js
  public/build/app.3947eaef.js
  public/build/app.9e8f68cf.js
  public/build/app.9e8f68cf.js.LICENSE.txt
  public/build/entrypoints.json
  public/build/manifest.json
Labels: bug, security

#2960 escape data in calendar popover
  assets/js/KimaiLoader.js
  assets/js/KimaiPlugin.js
  assets/js/plugins/KimaiEscape.js
  public/build/app.920ba43e.js
  public/build/app.920ba43e.js.LICENSE.txt
  public/build/app.9e8f68cf.js
  public/build/entrypoints.json
  public/build/manifest.json
  templates/calendar/user.html.twig
Labels: bug, calendar

#2961 make sure that markdown uses safe mode
  src/Twig/Runtime/MarkdownExtension.php
  src/Utils/Markdown.php
  tests/Twig/Runtime/MarkdownExtensionTest.php
  tests/Utils/MarkdownTest.php
Labels: bug, security

#2965 improve permissison handling in invoice screen
  assets/js/plugins/KimaiForm.js
  public/build/app.8609d161.js
  public/build/app.8609d161.js.LICENSE.txt
  public/build/app.920ba43e.js
  public/build/entrypoints.json
  public/build/manifest.json
  src/Controller/InvoiceController.php
  src/Repository/CustomerRepository.php
  src/Repository/Query/CustomerFormTypeQuery.php
  src/Voter/CustomerVoter.php
  src/Voter/UserVoter.php
  templates/invoice/index.html.twig
  tests/Controller/InvoiceControllerTest.php
  tests/Repository/Query/CustomerFormTypeQueryTest.php
  tests/Voter/CustomerVoterTest.php
Labels: bug, security, invoice

#2968 allow to delete invoice documents from within kimai
  src/Controller/InvoiceController.php
  src/Event/InvoiceDocumentsEvent.php
  src/EventSubscriber/Actions/InvoiceDocumentSubscriber.php
  src/Form/InvoiceDocumentUploadForm.php
  src/Repository/InvoiceDocumentRepository.php
  templates/invoice/actions.html.twig
  templates/invoice/document_upload.html.twig
  tests/Event/InvoiceDocumentsEventTest.php
  tests/EventSubscriber/Actions/AbstractActionsSubscriberTest.php
  tests/EventSubscriber/Actions/InvoiceDocumentSubscriberTest.php
  translations/messages.de.xlf
  translations/messages.en.xlf
Labels: feature request, invoice

#2972 fix two opening form tags
  templates/macros/search.html.twig
  templates/macros/toolbar.html.twig
  templates/quick-entry/index.html.twig
Labels: bug

#2980 fix deleting invoice documents
  src/Constants.php
  src/Controller/InvoiceController.php
  src/Repository/InvoiceDocumentRepository.php
Labels: bug
