Repository kimai/kimai, pull requests merged in 2021-07, with the labels that each got.

#2655 Bugfixes
  README.md
  composer.json
  composer.lock
  src/Entity/Timesheet.php
  src/EventSubscriber/Actions/ProjectSubscriber.php
  src/Form/ActivityEditForm.php
  src/Reporting/ProjectDetails/ProjectDetailsForm.php
  templates/activity/details.html.twig
  templates/activity/edit.html.twig
  templates/embeds/rates-table.html.twig
  templates/project/details.html.twig
  templates/reporting/project_details.html.twig
  tests/API/ActivityControllerTest.php
  tests/Controller/ActivityControllerTest.php
  translations/messages.de.xlf
  translations/messages.de_CH.xlf
  translations/messages.en.xlf
Labels: bug

#2291 limit amount of items in calendar drag and drop boxes
  src/Calendar/CalendarService.php
  src/Configuration/SystemConfiguration.php
  src/Controller/CalendarController.php
  src/Controller/SystemConfigurationController.php
  src/DependencyInjection/Configuration.php
  src/Event/CalendarDragAndDropSourceEvent.php
  src/Repository/TimesheetRepository.php
  templates/calendar/user.html.twig
  tests/DependencyInjection/AppExtensionTest.php
  tests/DependencyInjection/ConfigurationTest.php
  tests/Event/CalendarDragAndDropSourceEventTest.php
  translations/system-configuration.de.xlf
  translations/system-configuration.en.xlf
Labels: calendar, feature request

#2658 improve permission checks for report access
  src/Controller/Reporting/ProjectDetailsController.php
  src/Reporting/ReportingService.php
  templates/reporting/project_details.html.twig
Labels: feature request, reporting

#2657 Configurable print export
  assets/app.js
  assets/js/widgets/KimaiStorage.js
  public/build/app.07c264a7.js
  public/build/app.07c264a7.js.LICENSE.txt
  public/build/app.1cecb23c.js
  public/build/entrypoints.json
  public/build/manifest.json
  src/Controller/ExportController.php
  src/Event/ExportItemsQueryEvent.php
  src/Export/ServiceExport.php
  src/Export/TooManyItemsExportException.php
  src/Repository/Query/TimesheetQuery.php
  src/Repository/TimesheetRepository.php
  templates/export/index.html.twig
  templates/export/renderer/default.html.twig
  tests/Controller/ExportControllerTest.php
  tests/Export/Renderer/HtmlRendererTest.php
  tests/Export/ServiceExportTest.php
  tests/Repository/Query/TimesheetQueryTest.php
  translations/messages.de.xlf
  translations/messages.en.xlf
Labels: export, feature request

#2660 bugfixes and improvements
  src/API/TimesheetController.php
  src/Command/ImportTimesheetCommand.php
  src/Controller/Reporting/ProjectViewController.php
  src/EventSubscriber/Actions/ProjectSubscriber.php
  src/Export/Base/AbstractSpreadsheetRenderer.php
  src/Migrations/Version20210605154245.php
  src/Migrations/Version20210704111542.php
  templates/activity/edit.html.twig
  templates/embeds/budgets.html.twig
  templates/project/edit.html.twig
  templates/reporting/project_view.html.twig
  translations/about.ar.xlf
  translations/email.cs.xlf
  translations/email.el.xlf
  translations/email.en.xlf
  translations/email.eo.xlf
  translations/email.fa.xlf
  translations/email.fi.xlf
  translations/email.he.xlf
  translations/email.hu.xlf
  translations/email.ko.xlf
  translations/email.nl.xlf
  translations/email.pl.xlf
  translations/email.pt-BR.xlf
  translations/email.pt.xlf
  translations/email.ro.xlf
  translations/email.ru.xlf
  translations/email.sk.xlf
  translations/email.sv.xlf
  translations/email.tr.xlf
  translations/email.vi.xlf
  translations/email.zh_CN.xlf
  translations/messages.ar.xlf
  translations/messages.cs.xlf
  translations/messages.el.xlf
  translations/messages.en.xlf
  translations/messages.eu.xlf
  translations/messages.fa.xlf
  translations/messages.fi.xlf
  translations/messages.fo.xlf
  translations/messages.hu.xlf
  translations/messages.ko.xlf
  translations/messages.nl.xlf
  translations/messages.pl.xlf
  translations/messages.pt.xlf
  translations/messages.pt_BR.xlf
  translations/messages.ro.xlf
  translations/messages.ru.xlf
  translations/messages.sk.xlf
  translations/messages.sv.xlf
  translations/messages.tr.xlf
  translations/messages.vi.xlf
  translations/messages.zh_CN.xlf
Labels: bug

#2663 make sure that timezone is properly validated
  src/Command/ImportTimesheetCommand.php
  src/Entity/Timesheet.php
  src/Validator/Constraints/TimesheetBudgetUsed.php
  src/Validator/Constraints/TimesheetBudgetUsedValidator.php
  src/Validator/Constraints/TimesheetLockdownValidator.php
  src/Validator/Constraints/TimesheetRestartValidator.php
  tests/Validator/Constraints/TimesheetBudgetUsedValidatorTest.php
  tests/Validator/Constraints/TimesheetLockdownValidatorTest.php
  tests/Validator/Constraints/TimesheetRestartValidatorTest.php
Labels: bug

#2671 added account number field to user
  src/Entity/User.php
  src/Form/UserEditType.php
  src/Migrations/Version20210717211144.php
  src/Repository/UserRepository.php
  templates/user/index.html.twig
  templates/user/profile.html.twig
  templates/user/stats.html.twig
  tests/API/APIControllerBaseTest.php
  tests/Entity/UserTest.php
  tests/Export/Spreadsheet/UserExporterTest.php
  translations/messages.de.xlf
  translations/messages.en.xlf
Labels: feature request

#2665 Translations update from Weblate
  translations/about.he.xlf
  translations/actions.pl.xlf
  translations/email.he.xlf
  translations/messages.el.xlf
  translations/messages.eo.xlf
  translations/messages.he.xlf
  translations/messages.hu.xlf
  translations/messages.it.xlf
  translations/messages.ja.xlf
  translations/messages.pl.xlf
  translations/messages.pt_BR.xlf
  translations/messages.tr.xlf
  translations/plugins.he.xlf
  translations/reporting.eo.xlf
  translations/reporting.he.xlf
  translations/reporting.pl.xlf
  translations/reporting.pt-BR.xlf
  translations/reporting.tr.xlf
  translations/system-configuration.eo.xlf
  translations/system-configuration.he.xlf
  translations/system-configuration.pl.xlf
  translations/system-configuration.pt_BR.xlf
  translations/system-configuration.tr.xlf
  translations/validators.pl.xlf
Labels: translation i18n

#2669 Bugfixes
  .gitignore
  README.md
  src/Project/ProjectStatisticService.php
  src/Repository/CustomerRepository.php
  templates/plugin/index.html.twig
  translations/about.cs.xlf
  translations/messages.cs.xlf
  translations/plugins.ar.xlf
  translations/plugins.cs.xlf
  translations/plugins.da.xlf
  translations/plugins.de.xlf
  translations/plugins.el.xlf
  translations/plugins.en.xlf
  translations/plugins.eo.xlf
  translations/plugins.es.xlf
  translations/plugins.eu.xlf
  translations/plugins.fi.xlf
  translations/plugins.fr.xlf
  translations/plugins.he.xlf
  translations/plugins.hu.xlf
  translations/plugins.it.xlf
  translations/plugins.ja.xlf
  translations/plugins.ko.xlf
  translations/plugins.nl.xlf
  translations/plugins.pl.xlf
  translations/plugins.pt.xlf
  translations/plugins.pt_BR.xlf
  translations/plugins.ro.xlf
  translations/plugins.ru.xlf
  translations/plugins.sk.xlf
  translations/plugins.sv.xlf
  translations/plugins.tr.xlf
  translations/plugins.vi.xlf
  translations/plugins.zh_CN.xlf
Labels: bug, technical debt

#2681 LDAP: fixing issues for re-authenticating users
  src/Ldap/FormLoginLdapFactory.php
  src/Ldap/LdapAuthenticationProvider.php
  src/Security/DoctrineUserProvider.php
  tests/Ldap/LdapAuthenticationProviderTest.php
Labels: bug

#2689 Ldap
  config/packages/security.yaml
  src/Ldap/FormLoginLdapFactory.php
  src/Ldap/LdapAuthenticationProvider.php
  src/Security/DoctrineUserProvider.php
  tests/Ldap/LdapAuthenticationProviderTest.php
  tests/Timesheet/DateTimeFactoryTest.php
Labels: bug

#2690 allow 65535 character in meta fields
  src/Entity/MetaTableTypeTrait.php
  src/Migrations/Version20210727104955.php
Labels: feature request

#2691 allow to merge multiple Kimai 1 installations
  src/Command/KimaiImporterCommand.php
Labels: feature request
