Repository kimai/kimai, pull requests merged in 2021-03, with the labels that each got.

#2391 refactored templates to match controller
  src/Controller/PermissionController.php
  src/Controller/UserController.php
  templates/permission/actions.html.twig
  templates/permission/edit_role.html.twig
  templates/permission/permissions.html.twig
  templates/user/create.html.twig
Labels: technical debt

#2394 remove redundant translation key
  templates/reporting/layout.html.twig
  translations/reporting.cs.xlf
  translations/reporting.de.xlf
  translations/reporting.en.xlf
  translations/reporting.es.xlf
  translations/reporting.fi.xlf
  translations/reporting.fr.xlf
  translations/reporting.he.xlf
  translations/reporting.hu.xlf
  translations/reporting.it.xlf
  translations/reporting.ko.xlf
  translations/reporting.nl.xlf
  translations/reporting.pl.xlf
  translations/reporting.ro.xlf
  translations/reporting.ru.xlf
  translations/reporting.sk.xlf
  translations/reporting.tr.xlf
Labels: technical debt

#2403 allow to select reports as initial view
  src/Form/Type/InitialViewType.php
  src/Reporting/ReportingService.php
  src/Twig/Runtime/ReportingExtension.php
  src/Twig/RuntimeExtensions.php
  tests/Reporting/ReportingServiceTest.php
  tests/Twig/Runtime/ReportingExtensionTest.php
  tests/Twig/RuntimeExtensionsTest.php
Labels: feature request

#2408 Invoice archive - search and export
  src/Controller/InvoiceController.php
  src/Entity/Invoice.php
  src/EventSubscriber/Actions/AbstractActionsSubscriber.php
  src/EventSubscriber/Actions/InvoiceArchiveSubscriber.php
  src/EventSubscriber/Actions/UserSubscriber.php
  src/Form/InvoiceTemplateForm.php
  src/Form/Toolbar/InvoiceArchiveForm.php
  src/Form/Type/InvoiceStatusType.php
  src/Invoice/NumberGenerator/ConfigurableNumberGenerator.php
  src/Repository/InvoiceRepository.php
  src/Repository/Query/DateRangeTrait.php
  src/Repository/Query/InvoiceArchiveQuery.php
  src/Repository/Query/InvoiceQuery.php
  src/Repository/Query/TimesheetQuery.php
  templates/invoice/actions.html.twig
  templates/invoice/listing.html.twig
  templates/invoice/templates.html.twig
  tests/Repository/Query/BaseQueryTest.php
  tests/Repository/Query/InvoiceArchiveQueryTest.php
  tests/Repository/Query/TimesheetQueryTest.php
  translations/messages.de.xlf
  translations/messages.en.xlf
Labels: feature request

#2429 Show budget and time-budget in listing views
  src/Controller/ActivityController.php
  src/Widget/Type/UserTeamProjects.php
  templates/activity/index.html.twig
  templates/customer/index.html.twig
  templates/project/index.html.twig
  templates/widget/widget-userteamprojects.html.twig
  tests/Controller/TimesheetControllerTest.php
Labels: feature request

#2430 Allow to configure default report per user
  src/Controller/ReportingController.php
  src/EventSubscriber/UserPreferenceSubscriber.php
  src/Form/Type/ReportType.php
  src/Invoice/Hydrator/InvoiceModelDefaultHydrator.php
  src/Reporting/ProjectView/ProjectViewService.php
  src/Reporting/ReportingService.php
  templates/activity/index.html.twig
  templates/customer/index.html.twig
  templates/project/index.html.twig
  templates/reporting/project_view.html.twig
  tests/EventSubscriber/UserPreferenceSubscriberTest.php
  tests/Reporting/ReportingServiceTest.php
  translations/messages.de.xlf
  translations/messages.en.xlf
  translations/reporting.de.xlf
  translations/reporting.en.xlf
Labels: feature request, reporting

#2433 allow increasing invoice numbers per day
  src/Invoice/Calculator/AbstractSumInvoiceCalculator.php
  src/Invoice/NumberGenerator/DateNumberGenerator.php
  src/Repository/InvoiceRepository.php
  tests/Entity/InvoiceTest.php
  tests/Invoice/InvoiceFilenameTest.php
  tests/Invoice/NumberGenerator/DateNumberGeneratorTest.php
  tests/Invoice/Renderer/RendererTestTrait.php
  tests/Invoice/ServiceInvoiceTest.php
Labels: bug, invoice

#2439 Added version ID for simpler comparison
  src/API/Model/Version.php
  src/Constants.php
  tests/API/StatusControllerTest.php
  tests/ConstantsTest.php
Labels: feature request

#2440 Fix deprecations
  config/routes/annotations.yaml
  config/services.yaml
  src/Configuration/SystemConfiguration.php
  src/Controller/Auth/SamlController.php
  src/Kernel.php
  tests/Configuration/SystemConfigurationTest.php
  tests/Controller/Auth/SamlControllerTest.php
  tests/EventSubscriber/Actions/TimesheetSubscriberTest.php
  tests/EventSubscriber/Actions/TimesheetTeamMultiUpdateSubscriberTest.php
  tests/EventSubscriber/Actions/TimesheetsSubscriberTest.php
  tests/EventSubscriber/Actions/TimesheetsTeamSubscriberTest.php
Labels: technical debt

#2441 improve project view table
  assets/sass/app.scss
  assets/sass/content.scss
  assets/sass/datatable.scss
  assets/sass/progressbar.scss
  public/build/app.186b6ae9.css
  templates/macros/progressbar.html.twig
  templates/project/actions.html.twig
  templates/reporting/project_view.html.twig
Labels: feature request

#2468 fix api 404 on page parameter
  config/packages/fos_rest.yaml
  tests/API/APIControllerBaseTest.php
  tests/API/TimesheetControllerTest.php
Labels: API, bug

#2450 add subtotal and payment date to invoices
  src/Controller/InvoiceController.php
  src/Entity/Invoice.php
  src/EventSubscriber/Actions/InvoiceSubscriber.php
  src/Form/InvoicePaymentDateForm.php
  src/Migrations/Version20210320162820.php
  templates/invoice/listing.html.twig
  templates/invoice/payment_date_edit.html.twig
  tests/Controller/InvoiceControllerTest.php
  tests/Entity/InvoiceTest.php
  translations/messages.de.xlf
  translations/messages.en.xlf
Labels: feature request, invoice
