Repository kimai/kimai, pull requests merged in 2021-09, with the labels that each got.

#2766 Api fixes
  config/packages/nelmio_api_doc.yaml
  src/API/TeamController.php
  src/Controller/ActivityController.php
  src/Entity/Team.php
  src/Entity/TeamMember.php
  src/Entity/User.php
  src/Form/ActivityEditForm.php
  tests/API/ActivityControllerTest.php
  tests/Form/ActivityEditFormTest.php
Labels: bug

#2707 prepare release 1.15
  .github/workflows/testing.yaml
  SECURITY.md
  composer.json
  src/Constants.php
  src/Controller/PermissionController.php
  src/Controller/UserController.php
  src/Migrations/Version20180715160326.php
  src/Migrations/Version20190201150324.php
  src/Migrations/Version20210802174320.php
  src/Model/TimesheetStatistic.php
  src/Repository/TimesheetRepository.php
  src/Timesheet/TimesheetService.php
  src/Utils/LocaleHelper.php
  templates/macros/widgets.html.twig
  templates/permission/permissions.html.twig
  templates/user/stats.html.twig
  tests/API/TimesheetControllerTest.php
  tests/Timesheet/TimesheetServiceTest.php
  tests/Twig/LocaleFormatExtensionsTest.php
  tests/Utils/LocaleHelperTest.php
  translations/messages.de.xlf
  translations/messages.de_CH.xlf
  translations/messages.en.xlf
Labels: release

#2773 fix api doc (teams)
  config/packages/nelmio_api_doc.yaml
  src/Constants.php
Labels: bug

#2775 added customer number in invoice export
  src/Entity/Invoice.php
Labels: feature request

#2776 remove duplicate statistic events
  src/Activity/ActivityStatisticService.php
  src/Project/ProjectStatisticService.php
Labels: bug

#2778 Add option to copy the billable status of the timesheet
  src/API/TimesheetController.php
Labels: bug

#2782 1.15.2
  config/packages/kimai.yaml
  src/Constants.php
  src/Controller/DoctorController.php
  src/Migrations/Version20210717211144.php
  templates/embeds/budgets.html.twig
Labels: bug

#2756 prevent whitespace on line endings
  src/Invoice/Renderer/DocxRenderer.php
Labels: bug

#2781 Translations update from Weblate
  translations/about.el.xlf
  translations/about.fa.xlf
  translations/messages.el.xlf
  translations/messages.fr.xlf
  translations/messages.he.xlf
  translations/messages.it.xlf
  translations/messages.pl.xlf
  translations/messages.pt.xlf
  translations/messages.pt_BR.xlf
  translations/messages.tr.xlf
  translations/messages.vi.xlf
  translations/reporting.it.xlf
  translations/system-configuration.it.xlf
  translations/system-configuration.pt.xlf
  translations/validators.it.xlf
  translations/validators.vi.xlf
Labels: translation i18n
