Repository kimai/kimai, pull requests merged in 2021-05, with the labels that each got.

#2551 do not include running entries in invoices
  src/Controller/InvoiceController.php
  src/Repository/Query/InvoiceQuery.php
  tests/Repository/Query/InvoiceQueryTest.php
Labels: bug, invoice

#2552 fix timesheet collection fetch via API with end datetime set
  src/API/TimesheetController.php
  src/Form/Model/DateRange.php
  src/Repository/Query/TimesheetQuery.php
Labels: bug

#2561 added API route to fetch infos about installed plugins
  README.md
  src/API/Model/Plugin.php
  src/API/StatusController.php
  src/API/TimesheetController.php
  src/Form/Toolbar/AbstractToolbarForm.php
  src/Form/Type/TeamType.php
  src/Repository/TagRepository.php
  tests/API/StatusControllerTest.php
Labels: API, feature request

#2567 Open dialog to duplicate timesheet
  src/API/TimesheetController.php
  src/Controller/TimesheetAbstractController.php
  src/Controller/TimesheetController.php
  src/Controller/TimesheetTeamController.php
  src/EventSubscriber/Actions/AbstractTimesheetSubscriber.php
  src/EventSubscriber/Actions/TimesheetSubscriber.php
  src/EventSubscriber/Actions/TimesheetTeamSubscriber.php
  src/Form/Type/SystemConfigurationType.php
  src/Voter/TimesheetVoter.php
  templates/customer/index.html.twig
  tests/API/APIControllerBaseTest.php
  tests/API/TimesheetControllerTest.php
  tests/Controller/TimesheetControllerTest.php
  tests/Controller/TimesheetTeamControllerTest.php
  tests/DataFixtures/TimesheetFixtures.php
  tests/Voter/TimesheetVoterTest.php
Labels: feature request

#2569 Improve progressbar values in report
  templates/macros/progressbar.html.twig
  templates/reporting/project_view.html.twig
Labels: feature request, reporting

#2568 Adding the greek language options to the actuall program
  assets/app.js
  assets/calendar.js
  composer.lock
  config/packages/kimai.yaml
  config/services.yaml
  public/build/app.3b90b56b.js
  public/build/app.3b90b56b.js.LICENSE.txt
  public/build/app.e4243154.js
  public/build/calendar.52d75f80.js
  public/build/calendar.52d75f80.js.LICENSE.txt
  public/build/calendar.6260174b.js
  public/build/entrypoints.json
  public/build/manifest.json
Labels: translation i18n

#2572 new permission to hide user choice in report
  src/Controller/Reporting/ReportByUserController.php
  src/EventSubscriber/Actions/UserSubscriber.php
Labels: bug, reporting

#2581 fix calendar totals for empty weeks
  templates/calendar/user.html.twig
Labels: bug

#2158 Support for PHP 8
  .github/workflows/coverage.yaml
  .github/workflows/linting.yaml
  .github/workflows/testing.yaml
  .gitignore
  .php-cs-fixer.dist.php
  UPGRADING.md
  composer.json
  composer.lock
  config/packages/doctrine.yaml
  config/packages/doctrine_migrations.yaml
  src/Command/ReloadCommand.php
  src/Controller/DoctorController.php
  src/Doctrine/AbstractMigration.php
  src/Form/DataTransformer/DurationStringToSecondsTransformer.php
  src/Ldap/LdapUserProvider.php
  src/Repository/RolePermissionRepository.php
  src/Security/DoctrineUserProvider.php
  src/Utils/LocaleHelper.php
  symfony.lock
  tests/Command/UpdateCommandTest.php
  tests/Ldap/LdapDriverTest.php
Labels: technical debt
