Repository kimai/kimai, pull requests merged in 2021-01, with the labels that each got.

#2238 make sure to generate a valid filename
  UPGRADING.md
  src/Export/Base/PDFRenderer.php
  src/Invoice/InvoiceFilename.php
  src/Utils/FileHelper.php
  tests/Command/InvoiceCreateCommandTest.php
  tests/Invoice/InvoiceFilenameTest.php
  tests/Utils/FileHelperTest.php
Labels: bug

#2239 fix first week in year shows wrong year
  src/Timesheet/DateTimeFactory.php
  src/Widget/Type/PaginatedWorkingTimeChart.php
Labels: bug

#2248 ISO week numbers in calendar
  templates/calendar/user.html.twig
Labels: bug, calendar

#2226 Translations update from Weblate
  translations/about.sk.xlf
  translations/exceptions.sk.xlf
  translations/flashmessages.sk.xlf
  translations/messages.pl.xlf
  translations/messages.pt_BR.xlf
  translations/messages.sk.xlf
  translations/messages.sv.xlf
  translations/system-configuration.sk.xlf
  translations/teams.sk.xlf
  translations/validators.sk.xlf
Labels: translation i18n

#2212 Fix dropdowns on the bottom of a page
  assets/js/plugins/KimaiDatatable.js
  public/build/app.315842a2.js
  public/build/entrypoints.json
  public/build/manifest.json
Labels: bug, technical debt

#2210 Tiny fix: use the correct name for the CustomEvent
  assets/js/plugins/KimaiEvent.js
  public/build/app.14359ac7.js
  public/build/entrypoints.json
  public/build/manifest.json
Labels: bug

#2254 Added event for recent activities
  src/API/TimesheetController.php
  src/Controller/CalendarController.php
  src/Controller/LayoutController.php
  src/Event/CalendarDragAndDropSourceEvent.php
  src/Event/RecentActivityEvent.php
  tests/Event/CalendarDragAndDropSourceEventTest.php
  tests/Event/RecentActivityEventTest.php
Labels: feature request

#2259 hide multi-update-form for tags if delete_tag permission is missing
  src/Controller/TagController.php
  src/Form/MultiUpdate/MultiUpdateTableDTO.php
  templates/tags/index.html.twig
  tests/Form/MultiUpdate/MultiUpdateTableDTOTest.php
Labels: bug

#2260 fix pagination on invoice templates page
  src/Controller/InvoiceController.php
  src/Repository/InvoiceTemplateRepository.php
  src/Repository/Query/BaseQuery.php
  src/Repository/UserRepository.php
Labels: bug

#2268 fix calendar UTC problem
  templates/calendar/user.html.twig
Labels: bug

#2271 improve permission checks for timesheets with activated lockdown
  src/Security/RolePermissionManager.php
  src/Timesheet/LockdownService.php
  src/Timesheet/UserDateTimeFactory.php
  src/Validator/Constraints/TimesheetLockdownValidator.php
  src/Voter/AbstractVoter.php
  src/Voter/ActivityVoter.php
  src/Voter/CustomerVoter.php
  src/Voter/ProjectVoter.php
  src/Voter/RolePermissionVoter.php
  src/Voter/TeamVoter.php
  src/Voter/TimesheetVoter.php
  src/Voter/UserVoter.php
  tests/Security/RolePermissionManagerTest.php
  tests/Timesheet/LockdownServiceTest.php
  tests/Validator/Constraints/TimesheetLockdownValidatorTest.php
  tests/Voter/AbstractVoterTest.php
  tests/Voter/ActivityVoterTest.php
  tests/Voter/CustomerVoterTest.php
  tests/Voter/DeprecatedAbstractVoterTest.php
  tests/Voter/ProjectVoterTest.php
  tests/Voter/RolePermissionVoterTest.php
  tests/Voter/TeamVoterTest.php
  tests/Voter/TimesheetVoterTest.php
  tests/Voter/UserVoterTest.php
Labels: bug

#2272 do not break excel invoice templates with replacer inside formulas
  src/Invoice/Renderer/AbstractSpreadsheetRenderer.php
Labels: bug, invoice

#2274 show calculated lockdown date in config screen
  src/Controller/SystemConfigurationController.php
  src/Timesheet/LockdownService.php
Labels: feature request, technical debt

#2278 improve API validation error messages
  config/packages/fos_rest.yaml
  config/services.yaml
  src/API/Serializer/ValidationFailedExceptionErrorHandler.php
  tests/API/Serializer/ValidationFailedExceptionErrorHandlerTest.php
Labels: technical debt

#2289 replace "freelancer" invoice template with pdf version
  assets/sass/invoice-pdf.scss
  public/build/entrypoints.json
  public/build/invoice-pdf.cdf28364.css
  public/build/invoice-pdf.d79f186b.css
  public/build/manifest.json
  templates/invoice/renderer/default-pdf.pdf.twig
  templates/invoice/renderer/freelancer.html.twig
  templates/invoice/renderer/freelancer.pdf.twig
  tests/Invoice/Renderer/PdfRendererTest.php
  tests/Invoice/Renderer/TwigRendererTest.php
  tests/Repository/InvoiceDocumentRepositoryTest.php
  translations/invoice-renderer.de.xlf
  translations/invoice-renderer.en.xlf
Labels: invoice
