Repository kimai/kimai, pull requests merged in 2021-04, with the labels that each got.

#2481 allow to pre-define colors to choose from
  UPGRADING.md
  assets/js/plugins/KimaiFormSelect.js
  public/build/app.0d1f3758.js
  public/build/app.cc583d15.js
  public/build/entrypoints.json
  public/build/manifest.json
  src/Configuration/SystemConfiguration.php
  src/Constants.php
  src/Controller/SystemConfigurationController.php
  src/DependencyInjection/Configuration.php
  src/Entity/Configuration.php
  src/Form/EntityFormTrait.php
  src/Form/Type/ArrayToCommaStringType.php
  src/Form/Type/ColorChoiceType.php
  src/Migrations/Version20210405105611.php
  src/Validator/Constraints/ColorChoices.php
  src/Validator/Constraints/ColorChoicesValidator.php
  tests/API/StatusControllerTest.php
  tests/Command/UpdateCommandTest.php
  tests/Command/VersionCommandTest.php
  tests/Configuration/SystemConfigurationTest.php
  tests/ConstantsTest.php
  tests/DependencyInjection/AppExtensionTest.php
  tests/DependencyInjection/ConfigurationTest.php
  tests/KernelTest.php
  tests/Validator/Constraints/ColorChoicesValidatorTest.php
  translations/system-configuration.de.xlf
  translations/system-configuration.en.xlf
Labels: feature request

#2493 Highlight invisible items
  composer.lock
  phpstan.neon
  src/Controller/ActivityController.php
  src/Controller/CustomerController.php
  src/Controller/ProjectController.php
  src/Repository/ActivityRepository.php
  src/Repository/CustomerRepository.php
  src/Repository/ProjectRepository.php
  src/Repository/Query/BaseQuery.php
  src/Repository/Query/VisibilityTrait.php
  templates/activity/details.html.twig
  templates/activity/index.html.twig
  templates/customer/details.html.twig
  templates/customer/embed_projects.html.twig
  templates/customer/index.html.twig
  templates/invoice/index.html.twig
  templates/macros/datatables.html.twig
  templates/macros/widgets.html.twig
  templates/project/details.html.twig
  templates/project/embed_activities.html.twig
  templates/project/index.html.twig
  templates/reporting/project_view.html.twig
  templates/timesheet/layout-listing.html.twig
  tests/Controller/ControllerBaseTest.php
  tests/Controller/TimesheetControllerTest.php
  tests/Controller/TimesheetTeamControllerTest.php
  tests/Repository/Query/BaseQueryTest.php
Labels: feature request

#2495 prepare release 1.14
  .github_changelog_generator
  CHANGELOG.md
  Dockerfile
  README.md
  SECURITY.md
  composer.json
  composer.lock
  config/packages/doctrine.yaml
  config/packages/fos_rest.yaml
  config/packages/nelmio_api_doc.yaml
  src/API/NotFoundException.php
  src/EventSubscriber/PagerfantaExceptionSubscriber.php
  src/Form/FormTrait.php
  src/Form/TimesheetEditForm.php
  src/Twig/Runtime/MarkdownExtension.php
  src/Twig/RuntimeExtensions.php
  symfony.lock
  templates/activity/index.html.twig
  templates/customer/embed_projects.html.twig
  templates/customer/index.html.twig
  templates/project/embed_activities.html.twig
  templates/project/index.html.twig
  templates/timesheet/layout-listing.html.twig
  tests/API/APIControllerBaseTest.php
  tests/API/ApiDocControllerTest.php
  tests/API/NotFoundExceptionTest.php
  tests/Controller/ControllerBaseTest.php
  tests/EventSubscriber/PagerfantaExceptionSubscriberTest.php
  tests/Twig/Runtime/MarkdownExtensionTest.php
  tests/Twig/RuntimeExtensionsTest.php
Labels: release

#2516 added activity events for plugins
  src/Activity/ActivityService.php
  src/Controller/ActivityController.php
  src/Customer/CustomerService.php
  src/Event/AbstractActivityEvent.php
  src/Event/ActivityCreateEvent.php
  src/Event/ActivityCreatePostEvent.php
  src/Event/ActivityCreatePreEvent.php
  src/Event/ActivityUpdatePostEvent.php
  src/Event/ActivityUpdatePreEvent.php
  src/Project/ProjectService.php
  tests/Activity/ActivityServiceTest.php
  tests/Event/AbstractActivityEventTest.php
  tests/Event/ActivityCreateEventTest.php
  tests/Event/ActivityCreatePostEventTest.php
  tests/Event/ActivityCreatePreEventTest.php
  tests/Event/ActivityUpdatePostEventTest.php
  tests/Event/ActivityUpdatePreEventTest.php
  tests/Event/ReportingEventTest.php
Labels: feature request, technical debt

#2520 bugfixes
  src/Calendar/TimesheetEntry.php
  src/Form/API/TimesheetApiEditForm.php
  templates/reporting/report_by_user.html.twig
  templates/reporting/report_user_list.html.twig
  templates/timesheet/layout-edit.html.twig
Labels: bug

#2474 Translations update from Weblate
  assets/app.js
  config/services.yaml
  public/build/app.30cfcd45.js
  public/build/app.78dd5afe.js
  public/build/entrypoints.json
  public/build/manifest.json
  translations/messages.cs.xlf
  translations/messages.da.xlf
  translations/messages.de.xlf
  translations/messages.de_CH.xlf
  translations/messages.eo.xlf
  translations/messages.eu.xlf
  translations/messages.fa.xlf
  translations/messages.fo.xlf
  translations/messages.fr.xlf
  translations/messages.he.xlf
  translations/messages.hu.xlf
  translations/messages.it.xlf
  translations/messages.ja.xlf
  translations/messages.nl.xlf
  translations/messages.pl.xlf
  translations/messages.pt_BR.xlf
  translations/messages.ro.xlf
  translations/messages.ru.xlf
  translations/messages.sk.xlf
  translations/messages.tr.xlf
  translations/messages.vi.xlf
Labels: translation i18n

#2526 support tags in invoices
  src/Invoice/Calculator/AbstractMergedCalculator.php
  src/Invoice/Hydrator/InvoiceItemDefaultHydrator.php
  src/Invoice/InvoiceItem.php
  templates/timesheet/layout-edit.html.twig
  tests/Invoice/Calculator/DefaultCalculatorTest.php
  tests/Invoice/Calculator/ShortInvoiceCalculatorTest.php
  tests/Invoice/Hydrator/InvoiceItemDefaultHydratorTest.php
  tests/Invoice/InvoiceItemTest.php
  tests/Invoice/Renderer/DebugRendererTest.php
Labels: feature request, invoice
