Repository kimai/kimai, pull requests merged in 2022-08, with the labels that each got.

#3447 Croatian translation 20220730
  assets/app.js
  assets/calendar.js
  config/packages/kimai.yaml
Labels: translation

#3451 rebuild assets for croatian
  public/build/app.429626c8.js
  public/build/app.74a74ff6.js
  public/build/app.74a74ff6.js.LICENSE.txt
  public/build/calendar.32dd2acd.js
  public/build/calendar.32dd2acd.js.LICENSE.txt
  public/build/calendar.ba553253.js
  public/build/entrypoints.json
  public/build/manifest.json
Labels: translation

#3436 Translations update from Hosted Weblate
  translations/actions.hr.xlf
  translations/flashmessages.hr.xlf
  translations/invoice-renderer.hr.xlf
  translations/invoice-renderer.pt.xlf
  translations/invoice-renderer.pt_BR.xlf
  translations/messages.cs.xlf
  translations/messages.fr.xlf
  translations/messages.he.xlf
  translations/messages.hr.xlf
  translations/messages.it.xlf
  translations/messages.pt.xlf
  translations/messages.pt_BR.xlf
  translations/messages.ru.xlf
  translations/messages.tr.xlf
  translations/messages.vi.xlf
  translations/reporting.cs.xlf
Labels: translation

#3455 bump composer packages
  composer.lock
  src/Constants.php
Labels: technical debt

#3474 do not require user_preference permission when creating new user
  src/API/UserController.php
  src/Controller/UserController.php
  templates/user/create.html.twig
Labels: bug

#3462 Translations update from Hosted Weblate
  translations/actions.zh_CN.xlf
  translations/email.zh_CN.xlf
  translations/export.zh_CN.xlf
  translations/flashmessages.zh_CN.xlf
  translations/invoice-calculator.ro.xlf
  translations/invoice-calculator.zh_CN.xlf
  translations/invoice-renderer.ro.xlf
  translations/invoice-renderer.zh_CN.xlf
  translations/messages.ar.xlf
  translations/messages.fa.xlf
  translations/messages.fi.xlf
  translations/messages.ro.xlf
  translations/messages.zh_CN.xlf
  translations/reporting.zh_CN.xlf
  translations/system-configuration.ro.xlf
  translations/system-configuration.zh_CN.xlf
  translations/teams.zh_CN.xlf
  translations/validators.zh_CN.xlf
Labels: translation

#3488 Order quick entries by project name
  src/Controller/QuickEntryController.php
Labels: feature request

#3489 fixed multiple budget validation checks
  src/Validator/Constraints/TimesheetBudgetUsedValidator.php
  tests/Validator/Constraints/TimesheetBudgetUsedValidatorTest.php
Labels: bug

#3482 Translations update from Hosted Weblate
  translations/actions.en.xlf
  translations/export.hr.xlf
  translations/export.sv.xlf
  translations/invoice-calculator.sv.xlf
  translations/invoice-numbergenerator.sv.xlf
  translations/invoice-renderer.sv.xlf
  translations/messages.hr.xlf
  translations/messages.ru.xlf
  translations/messages.sv.xlf
  translations/messages.vi.xlf
  translations/reporting.sv.xlf
  translations/system-configuration.hr.xlf
  translations/system-configuration.sv.xlf
  translations/validators.sv.xlf
Labels: translation

#3493 Prevent invoice template update
  src/Invoice/ServiceInvoice.php
  src/Repository/InvoiceRepository.php
Labels: technical debt, invoice

#3494 fix unit test failing on month borders
  tests/Controller/Reporting/ProjectDateRangeControllerTest.php
Labels: technical debt
