Repository kimai/kimai, pull requests merged in 2022-05, with the labels that each got.

#3276 Translations update from Hosted Weblate
  translations/invoice-calculator.pt.xlf
  translations/invoice-numbergenerator.pt.xlf
  translations/reporting.pt.xlf
  translations/system-configuration.de.xlf
  translations/system-configuration.fr.xlf
  translations/system-configuration.he.xlf
  translations/system-configuration.it.xlf
  translations/system-configuration.pt.xlf
  translations/system-configuration.pt_BR.xlf
  translations/system-configuration.tr.xlf
Labels: translation i18n

#3310 Translations update from Hosted Weblate
  translations/messages.ja.xlf
  translations/messages.pl.xlf
Labels: translation i18n

#3304 Prevent bookings with same start / stop time
  src/Configuration/SystemConfiguration.php
  src/Controller/SystemConfigurationController.php
  src/DependencyInjection/Configuration.php
  src/Validator/Constraints/TimesheetZeroDuration.php
  src/Validator/Constraints/TimesheetZeroDurationValidator.php
  tests/Configuration/SystemConfigurationTest.php
  tests/Controller/SystemConfigurationControllerTest.php
  tests/Controller/TimesheetControllerTest.php
  tests/DependencyInjection/AppExtensionTest.php
  tests/DependencyInjection/ConfigurationTest.php
  tests/Validator/Constraints/TimesheetZeroDurationValidatorTest.php
  translations/system-configuration.de.xlf
  translations/system-configuration.en.xlf
  translations/validators.de.xlf
  translations/validators.en.xlf
Labels: feature request

#3296 Release 1.19.8
  composer.json
  composer.lock
  config/packages/kimai.yaml
  config/services.yaml
  src/Constants.php
  src/Controller/DoctorController.php
  src/Controller/QuickEntryController.php
  src/Controller/SystemConfigurationController.php
  src/DependencyInjection/Configuration.php
  tests/Controller/SystemConfigurationControllerTest.php
  tests/DependencyInjection/ConfigurationTest.php
  translations/system-configuration.de.xlf
  translations/system-configuration.en.xlf
Labels: release

#3313 Permission check for "mark-as-exported" checkboxes
  src/Controller/ExportController.php
  src/Controller/InvoiceController.php
  src/Form/Toolbar/ExportToolbarForm.php
  src/Form/Toolbar/InvoiceToolbarSimpleForm.php
  src/Form/Type/MarkAsExportedType.php
  templates/export/index.html.twig
  templates/invoice/index.html.twig
Labels: bug, invoice, export

#3314 allow switching user displayed in calendar
  src/Controller/CalendarController.php
  src/Controller/TimesheetAbstractController.php
  src/Controller/TimesheetController.php
  src/Controller/TimesheetTeamController.php
  src/Form/CalendarForm.php
  src/Form/TimesheetPreCreateForm.php
  src/Validator/Constraints/TimesheetZeroDurationValidator.php
  templates/calendar/user.html.twig
Labels: feature request, calendar

#3317 Release 1.20.1
  src/Activity/ActivityStatisticService.php
  src/Constants.php
  src/Customer/CustomerStatisticService.php
  src/Doctrine/TimesheetSubscriber.php
  src/Entity/Timesheet.php
  src/Export/Base/RendererTrait.php
  src/Model/TimesheetCountedStatistic.php
  src/Project/ProjectStatisticService.php
  src/Timesheet/Calculator/BillableCalculator.php
  src/Timesheet/Calculator/DurationCalculator.php
  src/Timesheet/Calculator/RateCalculator.php
  src/Timesheet/CalculatorInterface.php
  templates/timesheet/layout-listing.html.twig
  tests/Entity/TimesheetTest.php
  tests/Model/AbstractTimesheetCountedStatisticTest.php
Labels: release

#3321 Translations update from Hosted Weblate
  translations/invoice-calculator.he.xlf
  translations/invoice-calculator.tr.xlf
  translations/invoice-renderer.he.xlf
  translations/reporting.hr.xlf
  translations/system-configuration.fr.xlf
  translations/system-configuration.he.xlf
  translations/system-configuration.hr.xlf
  translations/system-configuration.pt_BR.xlf
  translations/system-configuration.tr.xlf
Labels: translation i18n

#3328 Add css class for custom fields plugin item in timesheet list
  templates/timesheet/layout-listing.html.twig
Labels: feature request

#3337 pre-select an option if it is the only available one
  assets/js/plugins/KimaiFormSelect.js
  public/build/app.0cc41cd4.js
  public/build/app.0cc41cd4.js.LICENSE.txt
  public/build/app.a8c84f0c.js
  public/build/entrypoints.json
  public/build/manifest.json
Labels: bug

#3338 Code cleanup
  src/Command/AbstractResetCommand.php
  src/Command/ResetTestCommand.php
  src/Invoice/ServiceInvoice.php
  tests/Command/ResetDevelopmentCommandTest.php
  tests/Command/ResetTestCommandTest.php
Labels: technical debt
