Repository kimai/kimai, pull requests merged in 2022-09, with the labels that each got.

#3499 release 1.23.1
  SECURITY.md
  src/Constants.php
Labels: bug

#3504 Fixes #3495: Quick entry during grace period
  src/Timesheet/LockdownService.php
Labels: bug

#3511 fix datetime modify to now
  src/Controller/QuickEntryController.php
  src/Timesheet/TrackingMode/DurationFixedBeginMode.php
  src/Timesheet/TrackingMode/DurationOnlyMode.php
  tests/Timesheet/TrackingMode/DurationFixedBeginModeTest.php
  tests/Timesheet/TrackingMode/DurationOnlyModeTest.php
Labels: bug

#3509 Added possibility to add fonts to mpdf via twig template
  config/services.yaml
  src/Export/ExportContext.php
  src/Utils/MPdfConverter.php
  tests/Export/Renderer/PdfRendererTest.php
  tests/Export/Timesheet/PdfRendererTest.php
  tests/Invoice/Renderer/PdfRendererTest.php
  tests/Mocks/FileHelperFactory.php
  tests/Utils/MPdfConverterTest.php
Labels: feature request

#3484 Optimize invoice templates for better customizability (new twig blocks)
  src/Invoice/InvoiceModel.php
  templates/invoice/renderer/default-pdf.pdf.twig
  templates/invoice/renderer/default.html.twig
  templates/invoice/renderer/freelancer.pdf.twig
Labels: feature request, invoice

#3486 Added inline disposition for PDF previews
  src/Controller/ExportController.php
  src/Controller/InvoiceController.php
  src/Export/Base/DispositionInlineInterface.php
  src/Export/Base/DispositionInlineTrait.php
  src/Export/Base/PDFRenderer.php
  src/Invoice/Renderer/PdfRenderer.php
  src/Invoice/ServiceInvoice.php
  tests/Export/Renderer/PdfRendererTest.php
  tests/Invoice/Renderer/PdfRendererTest.php
Labels: feature request, invoice

#3496 Translations update from Hosted Weblate
  translations/actions.fo.xlf
  translations/daterangepicker.fo.xlf
  translations/messages.fo.xlf
Labels: translation

#3515 version 1.24.0
  SECURITY.md
  src/Constants.php
Labels: release

#3532 Translations update from Hosted Weblate
  translations/actions.vi.xlf
  translations/export.es.xlf
  translations/export.vi.xlf
  translations/flashmessages.vi.xlf
  translations/invoice-calculator.es.xlf
  translations/invoice-calculator.vi.xlf
  translations/invoice-numbergenerator.es.xlf
  translations/invoice-renderer.es.xlf
  translations/messages.vi.xlf
  translations/plugins.vi.xlf
  translations/reporting.es.xlf
  translations/system-configuration.es.xlf
  translations/system-configuration.vi.xlf
  translations/teams.vi.xlf
  translations/validators.es.xlf
  translations/validators.vi.xlf
Labels: translation

#3531 prepare release 1.25.0
  composer.lock
  src/Constants.php
  src/Entity/Team.php
  src/Form/Toolbar/AbstractToolbarForm.php
  src/Timesheet/TimesheetStatisticService.php
  templates/base.html.twig
Labels: bug, technical debt

#3537 configurable calendar drag and drop behavior
  src/Calendar/CalendarService.php
  src/Calendar/TimesheetEntry.php
  src/Configuration/SystemConfiguration.php
  src/Controller/SystemConfigurationController.php
  src/DependencyInjection/Configuration.php
  tests/Calendar/TimesheetEntryTest.php
  tests/DependencyInjection/AppExtensionTest.php
  tests/DependencyInjection/ConfigurationTest.php
  translations/system-configuration.de.xlf
  translations/system-configuration.en.xlf
Labels: feature request, calendar

#3543 make project and customer available in summaries
  src/Export/Base/RendererTrait.php
Labels: feature request, export

#3551 use saml config interface instead of generic system configuration
  config/services-saml.yaml
  src/Controller/Auth/SamlController.php
  src/Controller/Security/SecurityController.php
  src/Saml/Provider/SamlProvider.php
  templates/security/login.html.twig
  tests/Controller/Auth/SamlControllerTest.php
  tests/Controller/Security/SecurityControllerTest.php
  tests/Saml/Provider/SamlProviderTest.php
Labels: bug

#3502 update composer packages
  composer.lock
  src/Command/AbstractResetCommand.php
  src/Command/ResetTestCommand.php
  src/Migrations/Version20180701120000.php
Labels: technical debt
