Repository kimai/kimai, pull requests merged in 2022-07, with the labels that each got.

#3399 Translations update from Hosted Weblate
  translations/about.pl.xlf
  translations/actions.es.xlf
  translations/actions.pl.xlf
  translations/daterangepicker.pl.xlf
  translations/email.pl.xlf
  translations/exceptions.pl.xlf
  translations/export.pl.xlf
  translations/flashmessages.pl.xlf
  translations/invoice-calculator.pl.xlf
  translations/invoice-numbergenerator.pl.xlf
  translations/invoice-renderer.pl.xlf
  translations/messages.cs.xlf
  translations/messages.es.xlf
  translations/messages.ko.xlf
  translations/messages.pl.xlf
  translations/plugins.pl.xlf
  translations/reporting.ko.xlf
  translations/reporting.pl.xlf
  translations/system-configuration.ko.xlf
  translations/system-configuration.pl.xlf
  translations/teams.pl.xlf
  translations/validators.fi.xlf
  translations/validators.ko.xlf
  translations/validators.pl.xlf
Labels: translation

#3430 Project date-range report: allow budget-type independent project-listing
  src/Project/ProjectStatisticService.php
  src/Reporting/ProjectDateRange/ProjectDateRangeForm.php
  src/Reporting/ProjectDateRange/ProjectDateRangeQuery.php
  tests/Controller/Reporting/ProjectDateRangeControllerTest.php
  tests/Reporting/ProjectDateRange/ProjectDateRangeQueryTest.php
  translations/messages.de.xlf
  translations/messages.en.xlf
Labels: feature request

#3431 total sums for duration and rate in invoice and export preview
  templates/export/index.html.twig
  templates/invoice/index.html.twig
Labels: feature request, invoice, export

#3429 bump version for next release 1.22
  .github/release-drafter.yml
  src/Activity/ActivityService.php
  src/Command/KimaiImporterCommand.php
  src/Constants.php
  tests/Twig/LocaleFormatExtensionsTest.php
Labels: release

#3437 allow to restrict usage of global activities for projects
  src/Entity/Project.php
  src/Form/ProjectEditForm.php
  src/Migrations/Version20220722125847.php
  src/Repository/ActivityRepository.php
  src/Validator/Constraints/TimesheetBasic.php
  src/Validator/Constraints/TimesheetBasicValidator.php
  templates/project/details.html.twig
  templates/project/edit.html.twig
  tests/Entity/ProjectTest.php
  translations/messages.de.xlf
  translations/messages.en.xlf
  translations/validators.de.xlf
Labels: feature request

#3440 saml: allow to keep existing roles on login
  src/Configuration/SamlConfiguration.php
  src/Configuration/SamlConfigurationInterface.php
  src/Configuration/SystemConfiguration.php
  src/DependencyInjection/Configuration.php
  src/Saml/User/SamlUserFactory.php
  tests/DependencyInjection/ConfigurationTest.php
Labels: feature request, security

#3441 show total hourly rate in detail pages
  templates/embeds/budgets.html.twig
Labels: feature request

#3438 Cleanup
  .github/release-drafter.yml
  composer.lock
  config/packages/doctrine_migrations.yaml
  src/Entity/Activity.php
  src/Entity/Customer.php
  src/Entity/Project.php
  src/Migrations/Version20210320162820.php
  src/Migrations/Version20210719123928.php
  src/Migrations/Version20220531145920.php
Labels: technical debt
