Repository kimai/kimai, pull requests merged in 2022-11, with the labels that each got.

#3627 added permission check on project rates
  src/Voter/EntityMultiRoleVoter.php
  templates/reporting/project_daterange.html.twig
Labels: bug

#3621 improve user unique check
  src/Entity/User.php
  src/Validator/Constraints/UserValidator.php
  tests/Validator/Constraints/UserValidatorTest.php
Labels: bug

#3622 Release 1.29
  src/Constants.php
  src/Controller/InvoiceController.php
  tests/Security/ApiAuthenticatorTest.php
  tests/Security/TokenAuthenticatorTest.php
  translations/about.zh_Hant.xlf
  translations/messages.zh_Hant.xlf
Labels: release

#3636 added project + customer setting for calendar entry titles
  src/Form/Type/CalendarTitlePatternType.php
  templates/calendar/user.html.twig
Labels: feature request, calendar

#3638 added username parameter to export command
  src/Command/ExportCreateCommand.php
  tests/Command/ExportCreateCommandTest.php
Labels: feature request, export

#3642 fix project end-start dates in quick-entry form
  src/Controller/QuickEntryController.php
  src/Form/QuickEntryForm.php
  src/Form/Type/QuickEntryWeekType.php
  src/Model/QuickEntryModel.php
  src/Model/QuickEntryWeek.php
  tests/Model/QuickEntryModelTest.php
  tests/Model/QuickEntryWeekTest.php
Labels: bug

#3628 Translations update from Hosted Weblate
  translations/actions.ko.xlf
  translations/actions.ru.xlf
  translations/actions.uk.xlf
  translations/email.uk.xlf
  translations/exceptions.ru.xlf
  translations/exceptions.uk.xlf
  translations/export.ru.xlf
  translations/flashmessages.ru.xlf
  translations/flashmessages.uk.xlf
  translations/invoice-calculator.es.xlf
  translations/invoice-calculator.ru.xlf
  translations/invoice-calculator.uk.xlf
  translations/invoice-numbergenerator.es.xlf
  translations/invoice-renderer.es.xlf
  translations/invoice-renderer.ru.xlf
  translations/invoice-renderer.uk.xlf
  translations/messages.ru.xlf
  translations/messages.uk.xlf
  translations/plugins.uk.xlf
  translations/reporting.ru.xlf
  translations/reporting.uk.xlf
  translations/system-configuration.es.xlf
  translations/system-configuration.ko.xlf
  translations/system-configuration.ru.xlf
  translations/system-configuration.uk.xlf
  translations/validators.ru.xlf
Labels: translation

#3647 Add accessibility attributes to sortable table headers.
  templates/macros/datatables.html.twig
Labels: technical debt

#3648 Fix deprecations
  .github/release-drafter.yml
  src/Constants.php
  src/Controller/DoctorController.php
  src/Entity/InvoiceDocument.php
  src/EventSubscriber/RedirectToLocaleSubscriber.php
  src/Invoice/Renderer/AbstractSpreadsheetRenderer.php
  src/Invoice/ServiceInvoice.php
  src/Model/TimesheetCountedStatistic.php
  src/Utils/LocaleHelper.php
  src/Validator/Constraints/DateTimeFormatValidator.php
  tests/Entity/InvoiceDocumentTest.php
  tests/Invoice/Renderer/DocxRendererTest.php
  tests/Invoice/Renderer/JsonRendererTest.php
  tests/Invoice/Renderer/OdsRendererTest.php
  tests/Invoice/Renderer/PdfRendererTest.php
  tests/Invoice/Renderer/TextRendererTest.php
  tests/Invoice/Renderer/TwigRendererTest.php
  tests/Invoice/Renderer/XlsxRendererTest.php
  tests/Invoice/Renderer/XmlRendererTest.php
  tests/Validator/Constraints/DurationValidatorTest.php
Labels: technical debt

#3649 Translations update from Hosted Weblate
  translations/messages.zh_Hant.xlf
Labels: translation
