Repository kimai/kimai, pull requests merged in 2022-01, with the labels that each got.

#3047 1.16.10
  src/DataFixtures/AllFixtures.php
  src/DataFixtures/TeamFixtures.php
  src/DataFixtures/TimesheetFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Widget/Type/PaginatedWorkingTimeChart.php
Labels: release

#3077 Invoice meta fields
  src/Controller/InvoiceController.php
  src/Entity/Invoice.php
  src/Entity/InvoiceMeta.php
  src/Event/InvoiceMetaDefinitionEvent.php
  src/Event/InvoiceMetaDisplayEvent.php
  src/Export/ExportItemInterface.php
  src/Form/InvoiceEditForm.php
  src/Invoice/InvoiceItemWithAmountInterface.php
  src/Migrations/Version20220101204501.php
  src/Repository/Loader/InvoiceIdLoader.php
  templates/invoice/listing.html.twig
  tests/Controller/InvoiceControllerTest.php
  tests/Entity/InvoiceMetaTest.php
  tests/Entity/InvoiceTest.php
  tests/Repository/Loader/InvoiceLoaderTest.php
Labels: feature request, invoice

#3078 Bugfixes
  LICENSE
  composer.json
  phpunit.xml.dist
  src/Command/TranslationCommand.php
  src/Entity/Activity.php
  src/Entity/Customer.php
  src/Entity/Invoice.php
  src/Migrations/Version20211008092010.php
  src/Validator/Constraints/TimesheetExportedValidator.php
  tests/Validator/Constraints/TimesheetExportedValidatorTest.php
Labels: bug, technical debt

#3079 Better invoices
  src/Command/InvoiceCreateCommand.php
  src/Event/InvoiceCreatedEvent.php
  src/Invoice/DefaultInvoiceFormatter.php
  src/Invoice/InvoiceFormatter.php
  src/Invoice/ServiceInvoice.php
  tests/Event/InvoiceCreatedEventTest.php
  tests/EventSubscriber/Actions/InvoiceSubscriberTest.php
  tests/Invoice/DebugFormatter.php
Labels: feature request, invoice

#3081 improve permission handling for quick entry controller
  src/Controller/QuickEntryController.php
  src/EventSubscriber/MenuSubscriber.php
  src/Voter/QuickEntryVoter.php
Labels: technical debt

#3088 code improvements
  src/Configuration/StringAccessibleConfigTrait.php
  src/Export/ExportFilename.php
  src/Repository/ConfigurationRepository.php
  templates/reporting/project_details.html.twig
Labels: technical debt

#3082 new export template
  src/Export/Base/RendererTrait.php
  src/Invoice/Renderer/AbstractTwigRenderer.php
  src/Twig/LocaleFormatExtensions.php
  src/Twig/TwigRendererTrait.php
  templates/export/pdf-layout.html.twig
  templates/export/renderer/timesheet.pdf.twig
  translations/export.de.xlf
  translations/export.en.xlf
Labels: export

#3089 bump dependencies
  composer.json
  composer.lock
  src/Command/CreateUserCommand.php
  src/Utils/HtmlToPdfConverter.php
  src/Utils/MPdfConverter.php
  templates/plugin/index.html.twig
Labels: technical debt

#3090 release 1.17
  .github_changelog_generator
  SECURITY.md
  src/Constants.php
Labels: release

#3091 shrink prod error messages
  config/packages/prod/monolog.yaml
Labels: technical debt

#3092 phpstan improvements
  .github/workflows/testing.yaml
  composer.json
  composer.lock
  phpstan.neon
  src/DependencyInjection/AppExtension.php
  src/Entity/Activity.php
  src/Entity/BudgetTrait.php
  src/Entity/ColorTrait.php
  src/Entity/Configuration.php
  src/Entity/Customer.php
  src/Entity/Invoice.php
  src/Entity/InvoiceTemplate.php
  src/Entity/MetaTableTypeTrait.php
  src/Entity/Project.php
  src/Entity/Rate.php
  src/Entity/Role.php
  src/Entity/RolePermission.php
  src/Entity/Tag.php
  src/Entity/Team.php
  src/Entity/TeamMember.php
  src/Entity/Timesheet.php
  src/Entity/User.php
  src/Entity/UserPreference.php
  src/Plugin/AbstractPluginExtension.php
  tests/Command/ActivateUserCommandTest.php
  tests/Command/ChangePasswordCommandTest.php
  tests/Command/CreateUserCommandTest.php
  tests/Command/DeactivateUserCommandTest.php
  tests/Command/DemoteUserCommandTest.php
  tests/Command/ImportCustomerCommandTest.php
  tests/Command/ImportProjectCommandTest.php
  tests/Command/ImportTimesheetCommandTest.php
  tests/Command/InstallCommandTest.php
  tests/Command/InvoiceCreateCommandTest.php
  tests/Command/KimaiImporterCommandTest.php
  tests/Command/PromoteUserCommandTest.php
  tests/Command/ReloadCommandTest.php
  tests/Command/VersionCommandTest.php
  tests/Entity/UserPreferenceTest.php
  tests/Repository/AbstractRepositoryTest.php
  tests/phpstan-doctrine.php
  tests/phpstan.neon
Labels: technical debt

#3096 added invoice delete event
  src/Controller/InvoiceController.php
  src/Event/InvoiceDeleteEvent.php
  src/Invoice/ServiceInvoice.php
  tests/Event/InvoiceDeleteEventTest.php
Labels: feature request, invoice

#3097 fix team member handling via api
  src/API/TeamController.php
  src/Controller/ProfileController.php
  src/Entity/Team.php
  src/Entity/TeamMember.php
  src/Entity/User.php
  tests/API/TeamControllerTest.php
  tests/Entity/TeamTest.php
  tests/Entity/UserTest.php
Labels: bug

#3095 fix admin access for customer in invoice module
  src/Constants.php
  src/Voter/CustomerVoter.php
Labels: bug

#3093 Translations update from Hosted Weblate
  translations/export.pt_BR.xlf
  translations/export.ro.xlf
  translations/export.tr.xlf
  translations/export.zh_CN.xlf
  translations/messages.fa.xlf
  translations/messages.fo.xlf
Labels: translation i18n

#3106 unify access to custom fields
  src/Entity/Activity.php
  src/Entity/Customer.php
  src/Entity/Invoice.php
  src/Entity/MetaTableTypeInterface.php
  src/Entity/MetaTableTypeTrait.php
  src/Entity/Project.php
  src/Entity/Timesheet.php
  src/Entity/User.php
  src/Invoice/InvoiceItem.php
  tests/Entity/ActivityTest.php
  tests/Entity/CustomerTest.php
  tests/Entity/InvoiceTest.php
  tests/Entity/ProjectTest.php
  tests/Entity/TimesheetTest.php
  tests/Entity/UserTest.php
  tests/Invoice/InvoiceItemTest.php
Labels: technical debt
