Repository kimai/kimai, pull requests merged in 2022-03, with the labels that each got.

#3190 1.18.2
  assets/sass/invoice-pdf.scss
  assets/sass/invoice.scss
  public/build/entrypoints.json
  public/build/invoice-pdf.9a7468ef.css
  public/build/invoice-pdf.e73a6dda.css
  public/build/invoice.ccdecd42.css
  public/build/invoice.ff32661a.css
  public/build/manifest.json
  src/Command/VersionCommand.php
  src/ConsoleApplication.php
  src/Utils/StringHelper.php
  src/Utils/Translator.php
  templates/form.html.twig
  templates/invoice/renderer/default-pdf.pdf.twig
  templates/invoice/renderer/freelancer.pdf.twig
  templates/macros/widgets.html.twig
  templates/reporting/project_details.html.twig
  templates/reporting/user_list_period_data.html.twig
  tests/Command/VersionCommandTest.php
  tests/ConsoleApplicationTest.php
  tests/Utils/StringHelperTest.php
Labels: release

#3181 Translations update from Hosted Weblate
  translations/invoice-calculator.fr.xlf
  translations/invoice-calculator.hr.xlf
  translations/invoice-calculator.ro.xlf
  translations/invoice-numbergenerator.ro.xlf
  translations/invoice-renderer.ro.xlf
  translations/messages.ro.xlf
  translations/messages.zh_CN.xlf
  translations/reporting.ro.xlf
  translations/reporting.zh_CN.xlf
Labels: translation i18n

#3194 Translations update from Hosted Weblate
  translations/actions.el.xlf
  translations/email.el.xlf
  translations/export.el.xlf
  translations/invoice-calculator.el.xlf
  translations/invoice-calculator.ro.xlf
  translations/invoice-numbergenerator.el.xlf
  translations/invoice-renderer.el.xlf
  translations/messages.el.xlf
  translations/messages.en.xlf
  translations/reporting.el.xlf
  translations/system-configuration.el.xlf
Labels: translation i18n

#3209 added event to extend the detail pages from plugins
  src/Controller/ActivityController.php
  src/Controller/CustomerController.php
  src/Controller/ProjectController.php
  src/Event/ActivityDetailControllerEvent.php
  src/Event/CustomerDetailControllerEvent.php
  src/Event/ProjectDetailControllerEvent.php
  templates/activity/details.html.twig
  templates/customer/details.html.twig
  templates/project/details.html.twig
  tests/Event/ActivityDetailControllerEventTest.php
  tests/Event/CustomerDetailControllerEventTest.php
  tests/Event/ProjectDetailControllerEventTest.php
Labels: feature request

#3210 defensive javascript
  assets/js/plugins/KimaiFormSelect.js
  public/build/app.120bbf21.js
  public/build/app.120bbf21.js.LICENSE.txt
  public/build/app.7d469ea7.js
  public/build/entrypoints.json
  public/build/manifest.json
Labels: bug

#3208 Translations update from Hosted Weblate
  translations/about.ko.xlf
  translations/actions.ko.xlf
  translations/email.ko.xlf
  translations/export.ko.xlf
  translations/flashmessages.ko.xlf
  translations/invoice-calculator.el.xlf
  translations/invoice-calculator.ko.xlf
  translations/invoice-numbergenerator.ko.xlf
  translations/invoice-renderer.el.xlf
  translations/invoice-renderer.ko.xlf
  translations/messages.de_CH.xlf
  translations/messages.el.xlf
  translations/messages.es.xlf
  translations/messages.fr.xlf
  translations/messages.he.xlf
  translations/messages.it.xlf
  translations/messages.ko.xlf
  translations/messages.tr.xlf
  translations/plugins.ko.xlf
  translations/reporting.ko.xlf
  translations/system-configuration.ko.xlf
  translations/validators.ko.xlf
Labels: translation i18n

#3215 release 1.19
  .github_changelog_generator
  SECURITY.md
  composer.lock
  src/Constants.php
  src/DataFixtures/TagFixtures.php
  src/Model/MonthlyStatistic.php
  src/Validator/Constraints/HexColorValidator.php
  tests/Model/UserStatisticTest.php
Labels: release

#3221 Translations update from Hosted Weblate
  translations/actions.ar.xlf
  translations/daterangepicker.ar.xlf
  translations/invoice-renderer.ar.xlf
  translations/messages.ar.xlf
  translations/messages.hr.xlf
  translations/messages.zh_CN.xlf
  translations/system-configuration.zh_CN.xlf
  translations/teams.zh_CN.xlf
Labels: translation i18n

#3224 show user account number in report export
  templates/reporting/report_user_list_export.html.twig
  templates/reporting/report_user_list_monthly_export.html.twig
  templates/reporting/user_list_period_data.html.twig
Labels: feature request, reporting

#3225 fix billable calculation on timesheet restart
  src/Form/TimesheetEditForm.php
  src/Timesheet/Calculator/BillableCalculator.php
  src/Validator/Constraints/TimesheetLongRunningValidator.php
  tests/Timesheet/Calculator/BillableCalculatorTest.php
  tests/Validator/Constraints/TimesheetLongRunningValidatorTest.php
Labels: bug

#3229 bump version 1.19.1
  composer.lock
  src/Constants.php
  src/Repository/TimesheetRepository.php
  symfony.lock
Labels: release
