Repository kimai/kimai, pull requests merged in 2022-10, with the labels that each got.

#3554 prepare release 1.26.0
  composer.lock
  phpunit.xml.dist
  src/Configuration/ThemeConfiguration.php
  src/Constants.php
Labels: security, release

#3549 Translations update from Hosted Weblate
  translations/actions.ar.xlf
  translations/actions.cs.xlf
  translations/actions.ko.xlf
  translations/export.cs.xlf
  translations/export.nl.xlf
  translations/export.ru.xlf
  translations/invoice-calculator.cs.xlf
  translations/invoice-calculator.ko.xlf
  translations/invoice-calculator.ru.xlf
  translations/invoice-calculator.zh_CN.xlf
  translations/invoice-numbergenerator.cs.xlf
  translations/invoice-numbergenerator.ru.xlf
  translations/invoice-renderer.cs.xlf
  translations/invoice-renderer.en.xlf
  translations/invoice-renderer.es.xlf
  translations/invoice-renderer.ru.xlf
  translations/messages.ar.xlf
  translations/messages.cs.xlf
  translations/messages.en.xlf
  translations/messages.eu.xlf
  translations/messages.ja.xlf
  translations/messages.ko.xlf
  translations/messages.nl.xlf
  translations/messages.ru.xlf
  translations/messages.sk.xlf
  translations/messages.vi.xlf
  translations/messages.zh-Hant.xlf
  translations/reporting.nl.xlf
  translations/reporting.ru.xlf
  translations/system-configuration.cs.xlf
  translations/system-configuration.ko.xlf
  translations/system-configuration.pt.xlf
  translations/system-configuration.zh_CN.xlf
  translations/validators.cs.xlf
  translations/validators.de.xlf
  translations/validators.en.xlf
  translations/validators.fr.xlf
  translations/validators.ru.xlf
  translations/validators.zh_CN.xlf
Labels: translation

#3564 Project API and globalActivities flag
  src/Entity/Project.php
  src/Form/API/ProjectApiEditForm.php
  src/Form/Type/APITrueFalseType.php
  tests/API/APIControllerBaseTest.php
  tests/API/ProjectControllerTest.php
Labels: bug, API

#3565 added filter for globalActivities in project collection
  src/API/ProjectController.php
  src/Repository/ProjectRepository.php
  src/Repository/Query/ProjectQuery.php
  tests/Repository/Query/ProjectQueryTest.php
Labels: feature request, API

#3573 allow negative duration via internal API
  src/Entity/Timesheet.php
  src/Utils/Duration.php
  src/Utils/LocaleHelper.php
  src/Validator/Constraints/Duration.php
  src/Validator/Constraints/TimesheetBasicValidator.php
  tests/Entity/TimesheetValidationTest.php
  tests/Twig/LocaleFormatExtensionsTest.php
  tests/Utils/DurationTest.php
  tests/Utils/LocaleHelperTest.php
Labels: feature request

#3579 do not show potential invoices with a negative total
  src/Invoice/Calculator/AbstractCalculator.php
  src/Invoice/ServiceInvoice.php
  tests/Invoice/ServiceInvoiceTest.php
Labels: bug, feature request, invoice

#3580 fix one-minute rounding bug in quick-entries and more
  src/Controller/QuickEntryController.php
  src/Form/Type/QuickEntryTimesheetType.php
Labels: bug, technical debt

#3582 allow to order by hourlyRate
  src/Repository/Query/TimesheetQuery.php
Labels: bug

#3570 Translations update from Hosted Weblate
  translations/email.es.xlf
  translations/invoice-calculator.es.xlf
  translations/invoice-renderer.es.xlf
  translations/messages.es.xlf
  translations/messages.pl.xlf
  translations/system-configuration.pl.xlf
  translations/system-configuration.ro.xlf
  translations/validators.zh_CN.xlf
Labels: translation

#3571 Release 1.27.0
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/release-drafter.yml
  .gitignore
  SECURITY.md
  src/Constants.php
  src/Entity/User.php
  src/Form/API/TimesheetApiEditForm.php
  tests/Entity/UserTest.php
Labels: release

#3588 fix several rendering issues in markdown
  src/Twig/Runtime/MarkdownExtension.php
  src/Twig/RuntimeExtensions.php
  src/Utils/ParsedownExtension.php
  tests/Twig/RuntimeExtensionsTest.php
Labels: bug

#3589 allow to show customer name in project dropdown
  src/Form/Helper/ProjectHelper.php
  src/Form/Type/ProjectTypePatternType.php
Labels: feature request

#3590 added team filter
  src/Controller/Reporting/ReportUsersMonthController.php
  src/Controller/Reporting/ReportUsersWeekController.php
  src/Controller/Reporting/ReportUsersYearController.php
  src/Form/Extension/ToolbarFormExtension.php
  src/Form/Toolbar/ExportToolbarForm.php
  src/Form/Toolbar/InvoiceToolbarForm.php
  src/Form/Toolbar/TimesheetToolbarForm.php
  src/Reporting/AbstractUserList.php
  src/Reporting/MonthlyUserListForm.php
  src/Reporting/WeeklyUserListForm.php
  src/Reporting/YearlyUserListForm.php
  src/User/TeamService.php
  src/User/UserService.php
  templates/export/index.html.twig
  templates/invoice/index.html.twig
  templates/reporting/report_user_list.html.twig
  templates/reporting/report_user_list_monthly.html.twig
Labels: feature request

#3594 added first and last fields for invoices
  src/Invoice/Hydrator/InvoiceModelDefaultHydrator.php
  tests/Invoice/Hydrator/InvoiceModelDefaultHydratorTest.php
  tests/Invoice/Renderer/DebugRendererTest.php
  tests/Invoice/Renderer/RendererTestTrait.php
Labels: feature request

#3596 allow 4 decimals for rounded rates
  src/Timesheet/Util.php
  tests/API/TimesheetControllerTest.php
  tests/Timesheet/Calculator/RateCalculatorTest.php
  tests/Timesheet/RateServiceTest.php
  tests/Timesheet/UtilTest.php
Labels: bug

#3599 copy teams from logged-in user for new projects
  composer.json
  composer.lock
  src/Configuration/SystemConfiguration.php
  src/Controller/ProjectController.php
  src/Controller/SystemConfigurationController.php
  src/DependencyInjection/Configuration.php
  src/Project/ProjectService.php
  src/Utils/Context.php
  tests/DependencyInjection/ConfigurationTest.php
  tests/Project/ProjectServiceTest.php
  tests/Repository/Query/BaseFormTypeQueryTest.php
  tests/Repository/Query/BaseQueryTest.php
  translations/system-configuration.de.xlf
  translations/system-configuration.en.xlf
Labels: feature request

#3605 create exports via command
  src/Command/ExportCreateCommand.php
  src/Export/Base/AbstractSpreadsheetRenderer.php
  src/Mail/KimaiMailer.php
  src/Repository/CustomerRepository.php
  src/Repository/TeamRepository.php
  src/Repository/UserRepository.php
  templates/emails/default.html.twig
  tests/Command/ExportCreateCommandTest.php
  tests/Command/InvoiceCreateCommandTest.php
  tests/Export/Renderer/AbstractRendererTest.php
  tests/Export/Timesheet/AbstractRendererTest.php
Labels: feature request, export

#3586 Translations update from Hosted Weblate
  translations/about.fa.xlf
  translations/actions.fa.xlf
  translations/actions.ru.xlf
  translations/daterangepicker.fa.xlf
  translations/exceptions.fa.xlf
  translations/export.fa.xlf
  translations/flashmessages.fa.xlf
  translations/invoice-calculator.es.xlf
  translations/invoice-numbergenerator.es.xlf
  translations/invoice-renderer.de.xlf
  translations/invoice-renderer.es.xlf
  translations/messages.fa.xlf
  translations/messages.fo.xlf
  translations/plugins.fa.xlf
  translations/reporting.fa.xlf
  translations/system-configuration.fa.xlf
  translations/system-configuration.fr.xlf
  translations/system-configuration.he.xlf
  translations/system-configuration.hr.xlf
  translations/system-configuration.nb_NO.xlf
  translations/system-configuration.pt_BR.xlf
  translations/system-configuration.tr.xlf
  translations/system-configuration.zh_CN.xlf
  translations/teams.fa.xlf
  translations/validators.es.xlf
  translations/validators.fa.xlf
Labels: translation

#3606 bump dependencies and improved export command
  composer.json
  composer.lock
  src/Command/ExportCreateCommand.php
  src/Constants.php
  tests/Command/ExportCreateCommandTest.php
Labels: bug
