Repository kimai/kimai, pull requests merged in 2022-06, with the labels that each got.

#3352 added new permission to separate time and money budget
  config/packages/kimai.yaml
  src/API/ActivityController.php
  src/API/CustomerController.php
  src/API/ProjectController.php
  src/Controller/ActivityController.php
  src/Controller/CustomerController.php
  src/Controller/ProjectController.php
  src/Controller/Reporting/ProjectDateRangeController.php
  src/Controller/Reporting/ProjectDetailsController.php
  src/Controller/Reporting/ProjectInactiveController.php
  src/Controller/Reporting/ProjectViewController.php
  src/EventSubscriber/Actions/CustomerSubscriber.php
  src/Form/ActivityEditForm.php
  src/Form/CustomerEditForm.php
  src/Form/EntityFormTrait.php
  src/Form/ProjectEditForm.php
  src/Reporting/ReportingService.php
  src/Validator/Constraints/TimesheetBudgetUsed.php
  src/Validator/Constraints/TimesheetBudgetUsedValidator.php
  src/Voter/ActivityVoter.php
  src/Voter/CustomerVoter.php
  src/Voter/EntityMultiRoleVoter.php
  src/Voter/ProjectVoter.php
  src/Widget/Type/UserTeamProjects.php
  templates/activity/edit.html.twig
  templates/activity/index.html.twig
  templates/customer/edit.html.twig
  templates/customer/embed_projects.html.twig
  templates/customer/index.html.twig
  templates/embeds/budgets.html.twig
  templates/project/details.html.twig
  templates/project/edit.html.twig
  templates/project/index.html.twig
  templates/reporting/project_daterange.html.twig
  templates/reporting/project_details.html.twig
  templates/reporting/project_view.html.twig
  templates/widget/widget-userteamprojects.html.twig
  tests/Controller/PermissionControllerTest.php
  tests/Form/ActivityEditFormTest.php
  tests/Form/CustomerEditFormTest.php
  tests/Form/ProjectEditFormTest.php
  tests/Validator/Constraints/TimesheetBudgetUsedValidatorTest.php
  tests/Voter/AbstractVoterTest.php
  tests/Voter/EntityMultiRoleVoterTest.php
  translations/validators.de.xlf
  translations/validators.de_CH.xlf
  translations/validators.en.xlf
Labels: feature request

#3339 Translations update from Hosted Weblate
  translations/actions.fi.xlf
  translations/email.ar.xlf
  translations/export.fi.xlf
  translations/flashmessages.fi.xlf
  translations/invoice-calculator.ar.xlf
  translations/invoice-calculator.fi.xlf
  translations/invoice-calculator.pt.xlf
  translations/invoice-numbergenerator.zh_CN.xlf
  translations/invoice-renderer.ar.xlf
  translations/invoice-renderer.fi.xlf
  translations/messages.ar.xlf
  translations/messages.de_CH.xlf
  translations/messages.fi.xlf
  translations/messages.fo.xlf
  translations/messages.fr.xlf
  translations/messages.he.xlf
  translations/messages.hr.xlf
  translations/messages.it.xlf
  translations/messages.pt.xlf
  translations/messages.pt_BR.xlf
  translations/messages.ro.xlf
  translations/messages.tr.xlf
  translations/reporting.ar.xlf
  translations/reporting.fi.xlf
  translations/reporting.ro.xlf
  translations/system-configuration.fi.xlf
  translations/system-configuration.pt.xlf
  translations/system-configuration.ro.xlf
  translations/teams.fi.xlf
  translations/validators.ar.xlf
  translations/validators.fi.xlf
  translations/validators.hr.xlf
  translations/validators.pt.xlf
  translations/validators.ro.xlf
Labels: translation i18n

#3358 calendar: fix drag and drop for regular user
  src/Constants.php
  templates/calendar/user.html.twig
Labels: bug

#3363 Cleanup
  .github/release-drafter.yml
  translations/validators.hr.xlf
  translations/validators.nb_NO.xlf
Labels: technical debt

#3377 reoad permissions page after role was created
  templates/permission/permissions.html.twig
Labels: bug

#3380 allow to set api token when creating user via API
  src/API/UserController.php
  src/Entity/User.php
  src/Form/API/UserApiCreateForm.php
Labels: feature request

#3381 remove currency symbol if unknown
  src/Form/ActivityEditForm.php
  src/Form/ProjectEditForm.php
Labels: bug

#3387 require a language for invoice templates
  src/Form/InvoiceTemplateForm.php
Labels: technical debt, invoice

#3392 new command to delete empty translations
  composer.json
  composer.lock
  phpstan.neon
  src/Command/TranslationCommand.php
  src/Constants.php
  src/Export/Renderer/RendererTrait.php
  src/Repository/TimesheetRepository.php
Labels: feature request
