Repository kimai/kimai, pull requests merged in 2023-02, with the labels that each got.

#3808 2.0 release candidate
  composer.lock
  config/packages/framework.yaml
  config/packages/monolog.yaml
  config/packages/routing.yaml
  phpstan.neon
  src/Configuration/SamlConfiguration.php
  src/Configuration/SamlConfigurationInterface.php
  src/Configuration/SystemConfiguration.php
  src/Saml/SamlAuthenticator.php
  src/Voter/ActivityVoter.php
  src/Voter/CustomerVoter.php
  src/Voter/EntityMultiRoleVoter.php
  src/Voter/ProjectVoter.php
  src/Voter/QuickEntryVoter.php
  src/Voter/ReportingVoter.php
  src/Voter/RolePermissionVoter.php
  src/Voter/TeamVoter.php
  src/Voter/TimesheetVoter.php
  src/Voter/UserVoter.php
  tests/Controller/ControllerBaseTest.php
  tests/phpstan.neon
Labels: release

#3820 Translations update from Hosted Weblate
  translations/about.de.xlf
  translations/actions.fr.xlf
  translations/actions.sv.xlf
  translations/daterangepicker.fr.xlf
  translations/daterangepicker.sv.xlf
  translations/invoice-renderer.fr.xlf
  translations/invoice-renderer.sv.xlf
  translations/messages.fr.xlf
  translations/messages.pt.xlf
  translations/messages.sv.xlf
  translations/plugins.sv.xlf
  translations/system-configuration.sv.xlf
  translations/teams.sv.xlf
  translations/validators.fr.xlf
  translations/validators.sv.xlf
  translations/wizard.sv.xlf
Labels: translation

#3825 2.0 RC 2
  composer.json
  composer.lock
  config/packages/security.yaml
  src/EventSubscriber/MenuSubscriber.php
  templates/calendar/user.html.twig
Labels: bug, feature request

#3832 remove user registration settings
  composer.json
  composer.lock
  migrations/Version20230126002049.php
  phpstan.neon
  src/Controller/SystemConfigurationController.php
  src/DependencyInjection/AppExtension.php
  src/DependencyInjection/Configuration.php
  tests/DependencyInjection/AppExtensionTest.php
  tests/DependencyInjection/ConfigurationTest.php
Labels: feature request, security

#3854 Release 1.30.8
  composer.json
  composer.lock
  src/Command/KimaiImporterCommand.php
  src/Constants.php
  src/DataFixtures/TeamFixtures.php
  src/Entity/Timesheet.php
  src/Validator/Constraints/TimesheetBudgetUsedValidator.php
  tests/Export/TimesheetExportRepositoryTest.php
  tests/Repository/TimesheetInvoiceItemRepositoryTest.php
  tests/Validator/Constraints/TimesheetBudgetUsedValidatorTest.php
Labels: bug

#3853 Version 2.0.1
  composer.lock
  config/packages/framework.yaml
  phpstan.neon
  src/Constants.php
  src/Doctrine/UTCDateTimeType.php
  src/Entity/Project.php
  src/Entity/Timesheet.php
  src/Repository/TimesheetRepository.php
  src/Timesheet/Calculator/DurationCalculator.php
  src/Timesheet/RoundingService.php
  src/Timesheet/TimesheetService.php
  src/Validator/Constraints/TimesheetBudgetUsedValidator.php
  src/Validator/Constraints/TimesheetLongRunningValidator.php
  src/Validator/Constraints/TimesheetZeroDurationValidator.php
  symfony.lock
  templates/security/login.html.twig
  tests/Entity/TimesheetTest.php
  tests/Validator/Constraints/TimesheetBudgetUsedValidatorTest.php
  tests/Validator/Constraints/TimesheetLongRunningValidatorTest.php
  tests/phpstan.neon
Labels: bug

#3862 1.30.10 - fix invoice number handling for null fields
  src/Constants.php
  src/Invoice/NumberGenerator/ConfigurableNumberGenerator.php
  tests/Invoice/NumberGenerator/ConfigurableNumberGeneratorTest.php
Labels: bug

#3830 Translations update from Hosted Weblate
  translations/email.de.xlf
  translations/invoice-calculator.it.xlf
  translations/invoice-renderer.sv.xlf
  translations/messages.de.xlf
  translations/messages.de_CH.xlf
  translations/messages.it.xlf
  translations/messages.nl.xlf
Labels: translation

#3864 Move recent activities to modal
  assets/js/KimaiLoader.js
  assets/js/plugins/KimaiRecentActivities.js
  assets/js/plugins/KimaiRemoteModal.js
  assets/sass/layout.scss
  phpstan.neon
  public/build/app.46a6055b.js
  public/build/app.46a6055b.js.LICENSE.txt
  public/build/app.50e94a4a.js
  public/build/entrypoints.json
  public/build/manifest.json
  src/Controller/FavoriteController.php
  src/Timesheet/FavoriteRecordService.php
  templates/base.html.twig
  templates/favorite/index.html.twig
  templates/partials/recent-activities.html.twig
  tests/Controller/FavoriteControllerTest.php
Labels: feature request

#3865 Improve inline stats
  src/Repository/Result/TimesheetResult.php
  templates/export/index.html.twig
  templates/invoice/index.html.twig
  templates/timesheet/index.html.twig
Labels: bug

#3863 Translations update from Hosted Weblate
  translations/invoice-calculator.uk.xlf
  translations/invoice-renderer.uk.xlf
  translations/messages.es.xlf
  translations/messages.he.xlf
  translations/messages.tr.xlf
  translations/messages.uk.xlf
  translations/system-configuration.uk.xlf
Labels: translation

#3868 Cleanup after 2.0
  UPGRADING.md
  migrations/Version20230126002049.php
  migrations/Version20230126002050.php
  src/Entity/User.php
  src/Timesheet/TrackingMode/DurationOnlyMode.php
  translations/system-configuration.uk.xlf
Labels: technical debt

#3876 added action to reload twig invoice template
  phpstan.neon
  src/Controller/InvoiceController.php
  src/EventSubscriber/Actions/InvoiceDocumentSubscriber.php
  src/Model/InvoiceDocument.php
  templates/invoice/actions.html.twig
  templates/invoice/document_upload.html.twig
Labels: feature request, invoice

#3878 download invoice document
  src/Controller/InvoiceController.php
  src/EventSubscriber/Actions/InvoiceDocumentSubscriber.php
Labels: feature request, invoice

#3879 Release 2.0.3
  src/Constants.php
  src/Entity/Customer.php
Labels: release

#3867 Translations update from Hosted Weblate
  translations/actions.ro.xlf
  translations/daterangepicker.ro.xlf
  translations/messages.ar.xlf
  translations/messages.pl.xlf
  translations/messages.pt_BR.xlf
  translations/messages.ro.xlf
  translations/plugins.ro.xlf
  translations/teams.ro.xlf
  translations/validators.ro.xlf
Labels: translation

#3877 Added more caching
  phpstan.neon
  src/Controller/PermissionController.php
  src/Repository/RolePermissionRepository.php
  src/Security/RolePermissionManager.php
  src/User/PermissionService.php
  tests/Security/RolePermissionManagerTest.php
  tests/Voter/AbstractVoterTest.php
Labels: feature request
