Repository kimai/kimai, pull requests merged in 2023-01, with the labels that each got.

#3735 do not traverse into invoice template subdirectories
  src/Repository/InvoiceDocumentRepository.php
Labels: bug

#3744 added ukrainian
  assets/app.js
  assets/calendar.js
  config/services.yaml
  package.json
  public/build/app.74a74ff6.js
  public/build/app.adae4b3b.js
  public/build/app.adae4b3b.js.LICENSE.txt
  public/build/calendar.32dd2acd.js
  public/build/calendar.d31fcf6a.js
  public/build/calendar.d31fcf6a.js.LICENSE.txt
  public/build/entrypoints.json
  public/build/manifest.json
  src/Constants.php
  yarn.lock
Labels: translation

#3763 Release 1.30.3
  src/Constants.php
  src/Controller/TimesheetAbstractController.php
  src/Form/TimesheetPreCreateForm.php
  templates/calendar/user.html.twig
Labels: bug

#3760 Translations update from Hosted Weblate
  translations/actions.pl.xlf
  translations/daterangepicker.pl.xlf
  translations/invoice-calculator.es.xlf
  translations/invoice-renderer.pl.xlf
  translations/messages.fr.xlf
  translations/plugins.pl.xlf
  translations/system-configuration.pl.xlf
  translations/validators.pl.xlf
  translations/wizard.pl.xlf
Labels: translation

#3770 Release 1.30.4
  src/API/TimesheetController.php
  src/Constants.php
  src/Controller/InvoiceController.php
  src/Controller/SystemConfigurationController.php
  src/DependencyInjection/Configuration.php
  src/Form/InvoiceDocumentUploadForm.php
  src/Invoice/Renderer/PdfRenderer.php
  tests/API/TimesheetControllerTest.php
  tests/DependencyInjection/ConfigurationTest.php
  translations/invoice-renderer.ar.xlf
  translations/invoice-renderer.cs.xlf
  translations/invoice-renderer.de.xlf
  translations/invoice-renderer.de_CH.xlf
  translations/invoice-renderer.el.xlf
  translations/invoice-renderer.en.xlf
  translations/invoice-renderer.eo.xlf
  translations/invoice-renderer.es.xlf
  translations/invoice-renderer.fa.xlf
  translations/invoice-renderer.fi.xlf
  translations/invoice-renderer.fo.xlf
  translations/invoice-renderer.fr.xlf
  translations/invoice-renderer.he.xlf
  translations/invoice-renderer.hr.xlf
  translations/invoice-renderer.hu.xlf
  translations/invoice-renderer.ko.xlf
  translations/invoice-renderer.nb_NO.xlf
  translations/invoice-renderer.nl.xlf
  translations/invoice-renderer.pl.xlf
  translations/invoice-renderer.pt.xlf
  translations/invoice-renderer.pt_BR.xlf
  translations/invoice-renderer.ro.xlf
  translations/invoice-renderer.ru.xlf
  translations/invoice-renderer.sv.xlf
  translations/invoice-renderer.tr.xlf
  translations/invoice-renderer.uk.xlf
  translations/invoice-renderer.vi.xlf
  translations/invoice-renderer.zh_CN.xlf
Labels: bug, release

#3783 release 1.30.5
  composer.lock
  src/Constants.php
Labels: release

#3786 2.0 beta 3
  README.md
  composer.json
  composer.lock
  migrations/Version20230126002049.php
  templates/timesheet/edit-default.html.twig
Labels: bug, feature request, release
