Repository kimai/kimai, pull requests merged in 2023-05, with the labels that each got.

#4000 Allow 2FA for SAML and LDAP users
  config/packages/scheb_2fa.yaml
  src/Controller/ProfileController.php
  src/Security/TwoFactorCondition.php
  src/Voter/UserVoter.php
  templates/user/2fa.html.twig
  tests/Controller/ProfileControllerTest.php
Labels: feature request, security

#3992 Release 2.0.17
  assets/js/forms/KimaiFormSelect.js
  assets/sass/app.scss
  assets/sass/selectpicker.scss
  assets/sass/sweetalert.scss
  phpstan.neon
  public/build/app.902831bc.js
  public/build/app.b10b16e5.css
  public/build/app.c61734af.js
  public/build/app.c61734af.js.LICENSE.txt
  public/build/app.d3ccebf5.css
  public/build/entrypoints.json
  public/build/manifest.json
  src/Constants.php
  src/Controller/TimesheetAbstractController.php
  src/Entity/Timesheet.php
  src/Entity/User.php
  src/EventSubscriber/UserDetailsSubscriber.php
  src/Export/ExportFilename.php
  src/Timesheet/Calculator/RateResetCalculator.php
  src/Twig/LocaleFormatExtensions.php
  src/Utils/SearchTerm.php
  templates/plugin/index.html.twig
  translations/messages.ar.xlf
  translations/messages.cs.xlf
  translations/messages.de.xlf
  translations/messages.de_CH.xlf
  translations/messages.en.xlf
  translations/messages.es.xlf
  translations/messages.fa.xlf
  translations/messages.fr.xlf
  translations/messages.he.xlf
  translations/messages.hr.xlf
  translations/messages.it.xlf
  translations/messages.nb_NO.xlf
  translations/messages.pl.xlf
  translations/messages.pt.xlf
  translations/messages.pt_BR.xlf
  translations/messages.ro.xlf
  translations/messages.ru.xlf
  translations/messages.sv.xlf
  translations/messages.tr.xlf
  translations/messages.uk.xlf
  translations/messages.zh_CN.xlf
Labels: bug, feature request, technical debt, release

#4002 Translations update from Hosted Weblate
  translations/daterangepicker.it.xlf
  translations/reporting.it.xlf
  translations/teams.it.xlf
Labels: translation

#4010 Translations update from Hosted Weblate
  translations/messages.ar.xlf
  translations/messages.cs.xlf
  translations/messages.es.xlf
  translations/messages.fr.xlf
  translations/messages.he.xlf
  translations/messages.hr.xlf
  translations/messages.it.xlf
  translations/messages.pl.xlf
  translations/messages.pt_BR.xlf
  translations/messages.tr.xlf
  translations/messages.zh_CN.xlf
Labels: translation

#4022 Release 2.0.19
  README.md
  phpstan.neon
  src/API/ActionsController.php
  src/Constants.php
  src/Event/PageActionsEvent.php
  src/Event/ThemeEvent.php
  src/EventSubscriber/Actions/AbstractActionsSubscriber.php
  src/Invoice/ServiceInvoice.php
  src/Ldap/LdapDriver.php
  tests/Event/PageActionsEventTest.php
  tests/Event/ThemeEventTest.php
  tests/phpstan.neon
Labels: release

#4016 API for handling work contract times
  composer.lock
  config/packages/kimai.yaml
  config/packages/tabler.yaml
  config/services.yaml
  migrations/Version20230327143628.php
  src/Controller/ContractController.php
  src/Controller/ProfileController.php
  src/Entity/User.php
  src/Entity/UserPreference.php
  src/Entity/WorkingTime.php
  src/Event/WorkContractDetailControllerEvent.php
  src/Event/WorkingTimeYearSummaryEvent.php
  src/EventSubscriber/Actions/UserFormsSubscriber.php
  src/EventSubscriber/MenuSubscriber.php
  src/Form/ContractByUserForm.php
  src/Form/UserContractType.php
  src/Model/Day.php
  src/Model/Month.php
  src/Model/Year.php
  src/Repository/WorkingTimeRepository.php
  src/Voter/UserVoter.php
  src/WorkingTime/Model/BoxConfiguration.php
  src/WorkingTime/Model/Day.php
  src/WorkingTime/Model/Month.php
  src/WorkingTime/Model/MonthSummary.php
  src/WorkingTime/Model/Year.php
  src/WorkingTime/Model/YearPerUserSummary.php
  src/WorkingTime/Model/YearSummary.php
  src/WorkingTime/WorkingTimeService.php
  templates/contract/status.html.twig
  templates/macros/widgets.html.twig
  templates/user/contract.html.twig
  templates/user/form.html.twig
  tests/Controller/ContractControllerTest.php
  tests/Controller/PermissionControllerTest.php
  tests/Controller/ProfileControllerTest.php
  tests/Entity/UserTest.php
  tests/Entity/WorkingTimeTest.php
  tests/Event/WorkContractDetailControllerEventTest.php
  tests/Event/WorkingTimeYearSummaryEventTest.php
  tests/Model/DayTest.php
  tests/Model/MonthTest.php
  tests/Model/YearTest.php
  tests/WorkingTime/Model/BoxConfigurationTest.php
  tests/WorkingTime/Model/DayTest.php
  tests/WorkingTime/Model/MonthSummaryTest.php
  tests/WorkingTime/Model/MonthTest.php
  tests/WorkingTime/Model/YearPerUserSummaryTest.php
  tests/WorkingTime/Model/YearSummaryTest.php
  tests/WorkingTime/Model/YearTest.php
  tests/phpstan.neon
  translations/messages.de.xlf
  translations/messages.en.xlf
Labels: feature request

#4028 Release 2.0.20
  assets/js/forms/KimaiFormSelect.js
  assets/sass/content.scss
  composer.json
  composer.lock
  phpstan.neon
  public/build/app.45d541e0.js
  public/build/app.45d541e0.js.LICENSE.txt
  public/build/app.66162a27.css
  public/build/app.80fb16e8.css
  public/build/app.bed7a1bf.js
  public/build/entrypoints.json
  public/build/manifest.json
  src/Constants.php
  src/DependencyInjection/Configuration.php
  src/Invoice/Hydrator/InvoiceItemDefaultHydrator.php
  src/Model/Statistic/Timesheet.php
  src/Model/Statistic/UserYear.php
  src/Model/Statistic/Year.php
  src/Project/ProjectStatisticService.php
  src/Reporting/ProjectDetails/ProjectDetailsModel.php
  templates/reporting/project_details.html.twig
  tests/DependencyInjection/ConfigurationTest.php
  tests/Invoice/Hydrator/InvoiceItemDefaultHydratorTest.php
  tests/Invoice/Renderer/DebugRendererTest.php
  tests/Model/Statistic/YearTest.php
  tests/phpstan.neon
  translations/tasks.de.xlf
  translations/tasks.en.xlf
Labels: release

#4036 Translations update from Hosted Weblate
  translations/messages.fr.xlf
  translations/messages.he.xlf
  translations/messages.it.xlf
  translations/messages.nl.xlf
  translations/messages.pt_BR.xlf
  translations/messages.tr.xlf
  translations/tasks.he.xlf
  translations/tasks.pt_BR.xlf
  translations/tasks.tr.xlf
Labels: translation

#4037 show available github release only if newer version exists
  phpstan.neon
  src/Controller/DoctorController.php
  src/Utils/ReleaseVersion.php
  templates/doctor/index.html.twig
  tests/Controller/DoctorControllerTest.php
Labels: bug

#4038 Dynamic favicon
  SECURITY.md
  assets/js/plugins/KimaiActiveRecords.js
  public/build/app.70a820f6.js
  public/build/app.f0378e96.js
  public/build/app.f0378e96.js.LICENSE.txt
  public/build/entrypoints.json
  public/build/manifest.json
  src/Constants.php
  templates/partials/head.html.twig
Labels: feature request

#4040 allow to remove date from non-required field
  templates/form/blocks.html.twig
Labels: bug

#4063 Fix nullable parameter in work-contract API
  src/WorkingTime/Model/Month.php
Labels: bug

#4064 added JS api to access current user in frontend
  assets/js/KimaiContainer.js
  assets/js/KimaiLoader.js
  assets/js/plugins/KimaiUser.js
  public/build/app.79ed1fb4.js
  public/build/app.79ed1fb4.js.LICENSE.txt
  public/build/app.f0378e96.js
  public/build/entrypoints.json
  public/build/manifest.json
  src/Twig/LocaleFormatExtensions.php
  tests/Export/Renderer/HtmlRendererTest.php
  tests/Twig/LocaleFormatExtensionsTest.php
Labels: feature request

#4065 bump theme to get navigation id specific classes
  composer.json
  composer.lock
  phpstan.neon
  src/API/ProjectController.php
  src/Export/Base/AbstractSpreadsheetRenderer.php
Labels: feature request
