Repository kimai/kimai, pull requests merged in 2023-06, with the labels that each got.

#4066 Release 2.0.25
  composer.json
  composer.lock
  config/packages/tabler.yaml
  migrations/Version20210316224358.php
  phpstan.neon
  src/Constants.php
  src/Controller/ContractController.php
  src/Controller/DoctorController.php
  src/Controller/ProfileController.php
  src/Customer/CustomerService.php
  src/Doctrine/AbstractMigration.php
  src/Entity/User.php
  src/Form/InvoiceDocumentUploadForm.php
  src/Form/Model/Configuration.php
  src/Form/Type/DateRangeType.php
  src/Plugin/AbstractPluginExtension.php
  src/Timesheet/DateTimeFactory.php
  src/Utils/DataTable.php
  src/Utils/PageSetup.php
  symfony.lock
  templates/contract/status.html.twig
  templates/datatable.html.twig
  templates/export/pdf-layout.html.twig
  templates/form/blocks.html.twig
  templates/macros/datatables.html.twig
  templates/page_setup.html.twig
  templates/permission/edit_role.html.twig
  templates/user/2fa.html.twig
  tests/Controller/ProfileControllerTest.php
  tests/Entity/UserTest.php
  translations/actions.de.xlf
  translations/actions.en.xlf
  translations/messages.de.xlf
  translations/messages.en.xlf
Labels: release

#4087 Release 2.0.26
  composer.json
  composer.lock
  phpstan.neon
  src/Constants.php
  src/Controller/ProfileController.php
  src/Controller/SystemConfigurationController.php
  src/Entity/Timesheet.php
  src/Entity/User.php
  src/Entity/UserPreference.php
  src/Event/WorkingTimeYearEvent.php
  src/Form/UserContractType.php
  src/Model/Month.php
  src/Model/Year.php
  src/Repository/Loader/TimesheetLoader.php
  src/WorkingTime/Model/Day.php
  src/WorkingTime/Model/Month.php
  src/WorkingTime/WorkingTimeService.php
  templates/user/contract.html.twig
  tests/Entity/UserTest.php
  tests/Event/WorkingTimeYearEventTest.php
  tests/WorkingTime/Model/MonthTest.php
  tests/phpstan.neon
Labels: release

#4086 Set tag visibility
  migrations/Version20230606125948.php
  phpstan.neon
  src/API/TimesheetController.php
  src/Controller/TagController.php
  src/Entity/Tag.php
  src/Form/TagEditForm.php
  src/Form/Toolbar/TagToolbarForm.php
  src/Form/Type/TagsSelectType.php
  src/Repository/Query/TagQuery.php
  src/Repository/TagRepository.php
  templates/macros/widgets.html.twig
  templates/tags/index.html.twig
  tests/API/APIControllerBaseTest.php
  tests/API/TagControllerTest.php
  tests/phpstan.neon
  translations/messages.de.xlf
  translations/messages.en.xlf
Labels: feature request

#4096 use collapsible element instead of collapsible card
  templates/activity/edit.html.twig
  templates/customer/edit.html.twig
  templates/doctor/index.html.twig
  templates/project/edit.html.twig
  templates/timesheet/edit-default.html.twig
  tests/Controller/DoctorControllerTest.php
Labels: technical debt

#4098 Modernized flat form styles
  assets/js/forms/KimaiDatePicker.js
  public/build/app.1adbc54f.js
  public/build/app.1adbc54f.js.LICENSE.txt
  public/build/app.79ed1fb4.js
  public/build/entrypoints.json
  public/build/manifest.json
  src/Form/Extension/IconExtension.php
  src/Form/Type/DurationType.php
  src/Form/Type/QuickEntryTimesheetType.php
  templates/form/blocks.html.twig
Labels: feature request

#4099 Translations update from Hosted Weblate
  translations/actions.he.xlf
  translations/actions.pt_BR.xlf
  translations/messages.cs.xlf
  translations/messages.en.xlf
  translations/messages.fi.xlf
  translations/messages.he.xlf
  translations/messages.hr.xlf
  translations/messages.ja.xlf
  translations/messages.nl.xlf
  translations/messages.pt_BR.xlf
  translations/messages.zh_CN.xlf
  translations/tasks.hr.xlf
  translations/tasks.zh_CN.xlf
  translations/wizard.nl.xlf
Labels: translation
