Repository kimai/kimai, pull requests merged in 2024-01, with the labels that each got.

#4517 Translations update from Hosted Weblate
  translations/actions.it.xlf
  translations/daterangepicker.it.xlf
  translations/export.it.xlf
  translations/flashmessages.it.xlf
  translations/messages.es.xlf
  translations/messages.it.xlf
  translations/messages.pt_BR.xlf
  translations/messages.uk.xlf
  translations/teams.it.xlf
  translations/validators.es.xlf
  translations/validators.it.xlf
  translations/validators.pt_BR.xlf
Labels: translation

#4514 [BUGFIX] Fix wrong default protocol for homepage
  src/Form/CustomerEditForm.php
  templates/form/blocks.html.twig
Labels: bug

#4512 release-drafter: Adapt supported PHP versions
  .github/release-drafter.yml
Labels: waiting for feedback

#4508 Release 2.8.0
  .github/workflows/lockfiles.yaml
  composer.json
  composer.lock
  config/packages/framework.yaml
  src/API/ActionsController.php
  src/API/ActivityController.php
  src/API/ConfigurationController.php
  src/API/CustomerController.php
  src/API/Model/CalendarEvent.php
  src/API/ProjectController.php
  src/API/StatusController.php
  src/API/TagController.php
  src/API/TeamController.php
  src/API/TimesheetController.php
  src/API/UserController.php
  src/Constants.php
  src/Controller/AbstractController.php
  src/Controller/Reporting/CustomerMonthlyProjectsController.php
  src/Controller/Reporting/ReportUsersMonthController.php
  src/Controller/Reporting/ReportUsersWeekController.php
  src/Controller/Reporting/ReportUsersYearController.php
  symfony.lock
  templates/reporting/user_list_period_data.html.twig
  translations/messages.de.xlf
  translations/messages.en.xlf
  translations/validators.de.xlf
  translations/validators.en.xlf
Labels: release

#4541 Hotfix to re-enable PHP/Kimai test
  .docker/test-lite.sh
Labels: docker

#4531 Translations update from Hosted Weblate
  translations/invoice-calculator.pt.xlf
  translations/invoice-renderer.it.xlf
  translations/messages.es.xlf
  translations/messages.it.xlf
  translations/messages.pt.xlf
  translations/messages.uk.xlf
  translations/messages.zh_CN.xlf
  translations/plugins.it.xlf
  translations/validators.es.xlf
  translations/validators.it.xlf
  translations/validators.pt.xlf
  translations/validators.zh_CN.xlf
  translations/wizard.it.xlf
  translations/wizard.pt.xlf
  translations/wizard.zh_CN.xlf
Labels: translation

#4526 Release 2.9.0
  .docker/test-lite.sh
  .github/workflows/docker.yaml
  composer.json
  composer.lock
  config/packages/framework.yaml
  config/services.yaml
  phpstan.neon
  src/Activity/ActivityStatisticService.php
  src/Command/ExportCreateCommand.php
  src/Command/InvoiceCreateCommand.php
  src/Constants.php
  src/Controller/Reporting/ProjectDateRangeController.php
  src/Customer/CustomerStatisticService.php
  src/DependencyInjection/AppExtension.php
  src/Event/ActivityBudgetStatisticEvent.php
  src/Event/ActivityStatisticEvent.php
  src/Event/ProjectBudgetStatisticEvent.php
  src/Event/ProjectStatisticEvent.php
  src/Export/Base/AbstractSpreadsheetRenderer.php
  src/Export/Spreadsheet/CellFormatter/DateFormatter.php
  src/Export/Spreadsheet/CellFormatter/DateTimeFormatter.php
  src/Export/Spreadsheet/CellFormatter/TimeFormatter.php
  src/Form/Model/DateRange.php
  src/Form/Type/DatePickerType.php
  src/Invoice/Hydrator/InvoiceModelCustomerHydrator.php
  src/Invoice/Renderer/DocxRenderer.php
  src/Model/TimesheetCountedStatistic.php
  src/Project/ProjectStatisticService.php
  src/Repository/Query/DateRangeInterface.php
  src/Repository/Query/DateRangeTrait.php
  src/Repository/Query/InvoiceArchiveQuery.php
  src/Repository/Query/TimesheetQuery.php
  src/Twig/LocaleFormatExtensions.php
  src/Validator/Constraints/TimesheetBudgetUsedValidator.php
  src/Validator/Constraints/TimesheetLockdownValidator.php
  symfony.lock
  tests/Event/ActivityBudgetStatisticEventTest.php
  tests/Event/ActivityStatisticEventTest.php
  tests/Event/ProjectBudgetStatisticEventTest.php
  tests/Event/ProjectStatisticEventTest.php
  tests/Export/Spreadsheet/CellFormatter/DateFormatterTest.php
  tests/Export/Spreadsheet/CellFormatter/DateTimeFormatterTest.php
  tests/Export/Spreadsheet/CellFormatter/TimeFormatterTest.php
  tests/Invoice/Renderer/DocxRendererTest.php
  tests/Repository/Query/BaseQueryTest.php
  tests/phpstan.neon
Labels: release

#4561 Make 'pagebreak' optional in pdf layout exporter
  templates/export/pdf-layout.html.twig
Labels: feature request, export

#4559 allow to edit username
  src/Controller/ProfileController.php
  src/Form/UserEditType.php
  templates/user/layout.html.twig
  templates/user/profile.html.twig
  translations/messages.de.xlf
  translations/messages.en.xlf
Labels: feature request

#4576 Translations update from Hosted Weblate
  translations/daterangepicker.hu.xlf
  translations/email.es.xlf
  translations/email.it.xlf
  translations/invoice-calculator.hu.xlf
  translations/invoice-calculator.ru.xlf
  translations/invoice-renderer.hu.xlf
  translations/invoice-renderer.ru.xlf
  translations/messages.ar.xlf
  translations/messages.cs.xlf
  translations/messages.da.xlf
  translations/messages.de_CH.xlf
  translations/messages.el.xlf
  translations/messages.eo.xlf
  translations/messages.es.xlf
  translations/messages.eu.xlf
  translations/messages.fa.xlf
  translations/messages.fi.xlf
  translations/messages.fo.xlf
  translations/messages.fr.xlf
  translations/messages.he.xlf
  translations/messages.hr.xlf
  translations/messages.hu.xlf
  translations/messages.it.xlf
  translations/messages.ja.xlf
  translations/messages.ko.xlf
  translations/messages.nb_NO.xlf
  translations/messages.nl.xlf
  translations/messages.pl.xlf
  translations/messages.pt.xlf
  translations/messages.pt_BR.xlf
  translations/messages.ro.xlf
  translations/messages.ru.xlf
  translations/messages.sk.xlf
  translations/messages.sv.xlf
  translations/messages.tr.xlf
  translations/messages.uk.xlf
  translations/messages.vi.xlf
  translations/messages.zh_CN.xlf
  translations/messages.zh_Hant.xlf
  translations/plugins.ru.xlf
  translations/reporting.hu.xlf
  translations/system-configuration.it.xlf
  translations/tasks.ru.xlf
  translations/teams.hu.xlf
  translations/validators.he.xlf
  translations/validators.it.xlf
Labels: translation

#4579 support default time on date-time-picker
  src/Form/Type/DateTimePickerType.php
Labels: feature request

#4595 Split user language (UI translation) from locale (formatted values)
  config/locales.php
  config/services.yaml
  phpstan.neon
  src/API/Serializer/ValidationFailedExceptionErrorHandler.php
  src/Command/RegenerateLocalesCommand.php
  src/Command/UserLoginLinkCommand.php
  src/Configuration/LocaleService.php
  src/Controller/SystemConfigurationController.php
  src/Controller/WizardController.php
  src/DependencyInjection/AppExtension.php
  src/Entity/User.php
  src/Entity/UserPreference.php
  src/EventSubscriber/ThemeOptionsSubscriber.php
  src/EventSubscriber/UserEnvironmentSubscriber.php
  src/EventSubscriber/UserPreferenceSubscriber.php
  src/Form/Helper/ProjectHelper.php
  src/Form/Type/LanguageType.php
  src/Form/Type/TimePickerType.php
  src/Form/Type/UserLanguageType.php
  src/Form/Type/UserLocaleType.php
  src/Form/UserEditType.php
  src/Utils/FormFormatConverter.php
  templates/form/blocks.html.twig
  tests/API/APIControllerBaseTest.php
  tests/Configuration/LocaleServiceTest.php
  tests/Controller/ProfileControllerTest.php
  tests/DependencyInjection/AppExtensionTest.php
  tests/Entity/UserTest.php
  tests/EventSubscriber/RedirectToLocaleSubscriberTest.php
  tests/EventSubscriber/UserPreferenceSubscriberTest.php
  tests/Export/Renderer/AbstractRendererTest.php
  tests/Export/Timesheet/AbstractRendererTest.php
  tests/Form/Helper/ProjectHelperTest.php
  tests/Invoice/Renderer/RendererTestTrait.php
  tests/Invoice/ServiceInvoiceTest.php
  tests/Twig/LocaleFormatExtensionsTest.php
  tests/phpstan.neon
  translations/messages.de.xlf
  translations/messages.en.xlf
Labels: feature request
